//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package endian ;import (_e "encoding/binary";_eb "unsafe";);var (ByteOrder _e .ByteOrder ;_d bool ;);func init (){const _b =int (_eb .Sizeof (0));_gf :=1;_f :=(*[_b ]byte )(_eb .Pointer (&_gf ));if _f [0]==0{_d =true ;ByteOrder =_e .BigEndian ;}else {ByteOrder =_e .LittleEndian ;};};func IsBig ()bool {return _d };func IsLittle ()bool {return !_d };