//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package optimize ;import (_ab "bytes";_eda "crypto/md5";_ee "crypto/sha256";_dd "errors";_bd "fmt";_e "github.com/unidoc/unipdf/v5/common";_g "github.com/unidoc/unipdf/v5/contentstream";_bbc "github.com/unidoc/unipdf/v5/core";_eef "github.com/unidoc/unipdf/v5/extractor";
_bb "github.com/unidoc/unipdf/v5/internal/imageutil";_d "github.com/unidoc/unipdf/v5/internal/textencoding";_da "github.com/unidoc/unipdf/v5/model";_cb "github.com/unidoc/unitype";_ed "golang.org/x/image/draw";_b "math";_c "strings";);

// Optimize optimizes PDF objects to decrease PDF size.
func (_fd *CleanFonts )Optimize (objects []_bbc .PdfObject )(_af []_bbc .PdfObject ,_fg error ){var _aebd map[*_bbc .PdfObjectStream ]struct{};if _fd .Subset {var _ege error ;_aebd ,_ege =_bcg (objects );if _ege !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004fR\u003a\u0020\u0046\u0061\u0069\u006c\u0065\u0064\u0020\u0073u\u0062s\u0065\u0074\u0074\u0069\u006e\u0067\u003a \u0025\u0076",_ege );
return nil ,_ege ;};};for _ ,_fbe :=range objects {_gec ,_dage :=_bbc .GetStream (_fbe );if !_dage {continue ;};if _ ,_gdb :=_aebd [_gec ];_gdb {continue ;};_gccg ,_cdb :=_bbc .NewEncoderFromStream (_gec );if _cdb !=nil {_e .Log .Debug ("\u0045\u0052RO\u0052\u0020\u0067e\u0074\u0074\u0069\u006eg e\u006eco\u0064\u0065\u0072\u003a\u0020\u0025\u0076 -\u0020\u0069\u0067\u006e\u006f\u0072\u0069n\u0067",_cdb );
continue ;};_acag ,_cdb :=_gccg .DecodeStream (_gec );if _cdb !=nil {_e .Log .Debug ("\u0044\u0065\u0063\u006f\u0064\u0069\u006e\u0067\u0020\u0065r\u0072\u006f\u0072\u0020\u003a\u0020\u0025v\u0020\u002d\u0020\u0069\u0067\u006e\u006f\u0072\u0069\u006e\u0067",_cdb );
continue ;};if len (_acag )< 4{continue ;};_fff :=string (_acag [:4]);if _fff =="\u004f\u0054\u0054\u004f"{continue ;};if _fff !="\u0000\u0001\u0000\u0000"&&_fff !="\u0074\u0072\u0075\u0065"{continue ;};_dbbc ,_cdb :=_cb .Parse (_ab .NewReader (_acag ));
if _cdb !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020P\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_cdb );continue ;};_cdb =_dbbc .Optimize ();
if _cdb !=nil {_e .Log .Debug ("\u0045\u0052RO\u0052\u0020\u004fp\u0074\u0069\u006d\u0069zin\u0067 f\u006f\u006e\u0074\u003a\u0020\u0025\u0076 -\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067",_cdb );continue ;};var _feaf _ab .Buffer ;_cdb =_dbbc .Write (&_feaf );
if _cdb !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020W\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_cdb );continue ;};if _feaf .Len ()> len (_acag ){_e .Log .Debug ("\u0052\u0065-\u0077\u0072\u0069\u0074\u0074\u0065\u006e\u0020\u0066\u006f\u006e\u0074\u0020\u0069\u0073\u0020\u006c\u0061\u0072\u0067\u0065\u0072\u0020\u0074\u0068\u0061\u006e\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u002d\u0020\u0073\u006b\u0069\u0070");
continue ;};_gea ,_cdb :=_bbc .MakeStream (_feaf .Bytes (),_bbc .NewFlateEncoder ());if _cdb !=nil {continue ;};*_gec =*_gea ;_gec .Set ("\u004ce\u006e\u0067\u0074\u0068\u0031",_bbc .MakeInteger (int64 (_feaf .Len ())));};return objects ,nil ;};

// CleanFonts cleans up embedded fonts, reducing font sizes.
type CleanFonts struct{

// Subset embedded fonts if encountered (if true).
// Otherwise attempts to reduce the font program.
Subset bool ;};

// ImagePPI optimizes images by scaling images such that the PPI (pixels per inch) is never higher than ImageUpperPPI.
// TODO(a5i): Add support for inline images.
// It implements interface model.Optimizer.
type ImagePPI struct{ImageUpperPPI float64 ;};type imageInfo struct{BitsPerComponent int ;ColorComponents int ;Width int ;Height int ;Stream *_bbc .PdfObjectStream ;PPI float64 ;};func _dbc (_cab _bbc .PdfObject ,_fgbd map[_bbc .PdfObject ]struct{})error {if _fcad ,_eac :=_cab .(*_bbc .PdfIndirectObject );
_eac {_fgbd [_cab ]=struct{}{};_dggg :=_dbc (_fcad .PdfObject ,_fgbd );if _dggg !=nil {return _dggg ;};return nil ;};if _badg ,_fdec :=_cab .(*_bbc .PdfObjectStream );_fdec {_fgbd [_badg ]=struct{}{};_bag :=_dbc (_badg .PdfObjectDictionary ,_fgbd );if _bag !=nil {return _bag ;
};return nil ;};if _aaf ,_ffbg :=_cab .(*_bbc .PdfObjectDictionary );_ffbg {for _ ,_cba :=range _aaf .Keys (){_bcgd :=_aaf .Get (_cba );_ =_bcgd ;if _gcafd ,_fbdb :=_bcgd .(*_bbc .PdfObjectReference );_fbdb {_bcgd =_gcafd .Resolve ();_aaf .Set (_cba ,_bcgd );
};if _cba !="\u0050\u0061\u0072\u0065\u006e\u0074"{if _bfa :=_dbc (_bcgd ,_fgbd );_bfa !=nil {return _bfa ;};};};return nil ;};if _dfd ,_bca :=_cab .(*_bbc .PdfObjectArray );_bca {if _dfd ==nil {return _dd .New ("\u0061\u0072\u0072a\u0079\u0020\u0069\u0073\u0020\u006e\u0069\u006c");
};for _caf ,_fbba :=range _dfd .Elements (){if _aagb ,_cdf :=_fbba .(*_bbc .PdfObjectReference );_cdf {_fbba =_aagb .Resolve ();_dfd .Set (_caf ,_fbba );};if _cdbf :=_dbc (_fbba ,_fgbd );_cdbf !=nil {return _cdbf ;};};return nil ;};return nil ;};

// CombineDuplicateDirectObjects combines duplicated direct objects by its data hash.
// It implements interface model.Optimizer.
type CombineDuplicateDirectObjects struct{};

// Optimize optimizes PDF objects to decrease PDF size.
func (_gcaff *CombineIdenticalIndirectObjects )Optimize (objects []_bbc .PdfObject )(_ebff []_bbc .PdfObject ,_ccde error ){_cegc (objects );_cef :=make (map[_bbc .PdfObject ]_bbc .PdfObject );_agf :=make (map[_bbc .PdfObject ]struct{});_fdg :=make (map[string ][]*_bbc .PdfIndirectObject );
for _ ,_bccc :=range objects {_bcgf ,_bgfc :=_bccc .(*_bbc .PdfIndirectObject );if !_bgfc {continue ;};if _ffd ,_gffb :=_bcgf .PdfObject .(*_bbc .PdfObjectDictionary );_gffb {if _abc ,_eagd :=_ffd .Get ("\u0054\u0079\u0070\u0065").(*_bbc .PdfObjectName );
_eagd &&*_abc =="\u0050\u0061\u0067\u0065"{continue ;};if _gfea :=_ffd .Keys ();len (_gfea )==0{continue ;};_fda :=_eda .New ();_fda .Write (_ffd .Write ());_bcb :=string (_fda .Sum (nil ));_fdg [_bcb ]=append (_fdg [_bcb ],_bcgf );};};for _ ,_bce :=range _fdg {if len (_bce )< 2{continue ;
};_eaddb :=_bce [0];for _gee :=1;_gee < len (_bce );_gee ++{_gfge :=_bce [_gee ];_cef [_gfge ]=_eaddb ;_agf [_gfge ]=struct{}{};};};_ebff =make ([]_bbc .PdfObject ,0,len (objects )-len (_agf ));for _ ,_bggc :=range objects {if _ ,_ebed :=_agf [_bggc ];
_ebed {continue ;};_ebff =append (_ebff ,_bggc );};_bba (_ebff ,_cef );return _ebff ,nil ;};

// CombineDuplicateStreams combines duplicated streams by its data hash.
// It implements interface model.Optimizer.
type CombineDuplicateStreams struct{};func _fc (_ggf *_bbc .PdfObjectStream )error {_fa ,_bdc :=_bbc .DecodeStream (_ggf );if _bdc !=nil {return _bdc ;};_ac :=_g .NewContentStreamParser (string (_fa ));_gca ,_bdc :=_ac .Parse ();if _bdc !=nil {return _bdc ;
};_gca =_ce (_gca );_ba :=_gca .Bytes ();if len (_ba )>=len (_fa ){return nil ;};_abad ,_bdc :=_bbc .MakeStream (_gca .Bytes (),_bbc .NewFlateEncoder ());if _bdc !=nil {return _bdc ;};_ggf .Stream =_abad .Stream ;_ggf .Merge (_abad .PdfObjectDictionary );
return nil ;};func _bgef (_bdced []_bbc .PdfObject )objectStructure {_bdaf :=objectStructure {};_ccfa :=false ;for _ ,_ggce :=range _bdced {switch _ffac :=_ggce .(type ){case *_bbc .PdfIndirectObject :_abgcc ,_fge :=_bbc .GetDict (_ffac );if !_fge {continue ;
};_bbdb ,_fge :=_bbc .GetName (_abgcc .Get ("\u0054\u0079\u0070\u0065"));if !_fge {continue ;};switch _bbdb .String (){case "\u0043a\u0074\u0061\u006c\u006f\u0067":_bdaf ._eddc =_abgcc ;_ccfa =true ;};};if _ccfa {break ;};};if !_ccfa {return _bdaf ;};_aea ,_efa :=_bbc .GetDict (_bdaf ._eddc .Get ("\u0050\u0061\u0067e\u0073"));
if !_efa {return _bdaf ;};_bdaf ._edgc =_aea ;_cbb ,_efa :=_bbc .GetArray (_aea .Get ("\u004b\u0069\u0064\u0073"));if !_efa {return _bdaf ;};for _ ,_bgga :=range _cbb .Elements (){_bfg ,_gadd :=_bbc .GetIndirect (_bgga );if !_gadd {break ;};_bdaf ._gddf =append (_bdaf ._gddf ,_bfg );
};return _bdaf ;};

// Append appends optimizers to the chain.
func (_ea *Chain )Append (optimizers ..._da .Optimizer ){_ea ._f =append (_ea ._f ,optimizers ...)};func _gaca (_ebc *_bbc .PdfObjectStream ,_dcb []rune ,_bea []_cb .GlyphIndex )error {_ebc ,_edb :=_bbc .GetStream (_ebc );if !_edb {_e .Log .Debug ("\u0045\u006d\u0062\u0065\u0064\u0064\u0065\u0064\u0020\u0066\u006f\u006e\u0074\u0020\u006f\u0062\u006a\u0065c\u0074\u0020\u006e\u006f\u0074\u0020\u0066o\u0075\u006e\u0064\u0020\u002d\u002d\u0020\u0041\u0042\u004f\u0052T\u0020\u0073\u0075\u0062\u0073\u0065\u0074\u0074\u0069\u006e\u0067");
return _dd .New ("\u0066\u006f\u006e\u0074fi\u006c\u0065\u0032\u0020\u006e\u006f\u0074\u0020\u0066\u006f\u0075\u006e\u0064");};_cfb ,_cfd :=_bbc .DecodeStream (_ebc );if _cfd !=nil {_e .Log .Debug ("\u0044\u0065c\u006f\u0064\u0065 \u0065\u0072\u0072\u006f\u0072\u003a\u0020\u0025\u0076",_cfd );
return _cfd ;};_ece ,_cfd :=_cb .Parse (_ab .NewReader (_cfb ));if _cfd !=nil {_e .Log .Debug ("\u0045\u0072\u0072\u006f\u0072\u0020\u0070\u0061\u0072\u0073\u0069n\u0067\u0020\u0025\u0064\u0020\u0062\u0079\u0074\u0065\u0020f\u006f\u006e\u0074",len (_ebc .Stream ));
return _cfd ;};_cgc :=_bea ;if len (_dcb )> 0{_fed :=_ece .LookupRunes (_dcb );_cgc =append (_cgc ,_fed ...);};_ece ,_cfd =_ece .SubsetKeepIndices (_cgc );if _cfd !=nil {_e .Log .Debug ("\u0045R\u0052\u004f\u0052\u0020s\u0075\u0062\u0073\u0065\u0074t\u0069n\u0067 \u0066\u006f\u006e\u0074\u003a\u0020\u0025v",_cfd );
return _cfd ;};var _bgda _ab .Buffer ;_cfd =_ece .Write (&_bgda );if _cfd !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004fR \u0057\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076",_cfd );return _cfd ;};if _bgda .Len ()> len (_cfb ){_e .Log .Debug ("\u0052\u0065-\u0077\u0072\u0069\u0074\u0074\u0065\u006e\u0020\u0066\u006f\u006e\u0074\u0020\u0069\u0073\u0020\u006c\u0061\u0072\u0067\u0065\u0072\u0020\u0074\u0068\u0061\u006e\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u002d\u0020\u0073\u006b\u0069\u0070");
return nil ;};_aed ,_cfd :=_bbc .MakeStream (_bgda .Bytes (),_bbc .NewFlateEncoder ());if _cfd !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004fR \u0057\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076",_cfd );return _cfd ;
};*_ebc =*_aed ;_ebc .Set ("\u004ce\u006e\u0067\u0074\u0068\u0031",_bbc .MakeInteger (int64 (_bgda .Len ())));return nil ;};

// CompressStreams compresses uncompressed streams.
// It implements interface model.Optimizer.
type CompressStreams struct{};func _daeg (_bge *_bbc .PdfObjectDictionary )[]string {_eadd :=[]string {};for _ ,_eaea :=range _bge .Keys (){_eadd =append (_eadd ,_eaea .String ());};return _eadd ;};

// Linearize toggles linearized ("Fast Web View") output on the given writer.
// It is a convenience wrapper over model.PdfWriter.SetLinearized — exposed
// in the optimize package so callers reaching for size/structure tweaks can
// find linearization in the same namespace.
//
// Linearization is not a true Optimizer (the Optimizer interface transforms
// an object list, while linearization is a write-strategy decision), so
// this function does not implement that interface.
func Linearize (w *_da .PdfWriter ){w .SetLinearized (true )};

// Optimize optimizes PDF objects to decrease PDF size.
func (_caff *Image )Optimize (objects []_bbc .PdfObject )(_cbf []_bbc .PdfObject ,_ebb error ){if _caff .ImageQuality <=0{return objects ,nil ;};_dfc :=_cfba (objects );if len (_dfc )==0{return objects ,nil ;};_gddg :=make (map[_bbc .PdfObject ]_bbc .PdfObject );
_dcf :=make (map[_bbc .PdfObject ]struct{});for _ ,_aedc :=range _dfc {_ged :=_aedc .Stream .Get ("\u0053\u004d\u0061s\u006b");_dcf [_ged ]=struct{}{};};for _egba ,_egeb :=range _dfc {_fggeg :=_egeb .Stream ;if _ ,_ffa :=_dcf [_fggeg ];_ffa {continue ;
};_gddd ,_dfbf :=_da .NewXObjectImageFromStream (_fggeg );if _dfbf !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_dfbf );continue ;};switch _gddd .Filter .(type ){case *_bbc .JBIG2Encoder :continue ;case *_bbc .CCITTFaxEncoder :continue ;
};_aecc ,_dfbf :=_gddd .ToImage ();if _dfbf !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_dfbf );continue ;};_cfe :=_bbc .NewDCTEncoder ();_cfe .ColorComponents =_aecc .ColorComponents ;_cfe .Quality =_caff .ImageQuality ;
_cfe .BitsPerComponent =_egeb .BitsPerComponent ;_cfe .Width =_egeb .Width ;_cfe .Height =_egeb .Height ;_edc ,_dfbf :=_cfe .EncodeBytes (_aecc .Data );if _dfbf !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_dfbf );
continue ;};var _gabe _bbc .StreamEncoder ;_gabe =_cfe ;{_bcgdc :=_bbc .NewFlateEncoder ();_ada :=_bbc .NewMultiEncoder ();_ada .AddEncoder (_bcgdc );_ada .AddEncoder (_cfe );_egda ,_ageg :=_ada .EncodeBytes (_aecc .Data );if _ageg !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_ageg );
continue ;};if len (_egda )< len (_edc ){if _e .Log .IsLogLevel (_e .LogLevelTrace ){_e .Log .Trace ("\u004d\u0075\u006c\u0074\u0069\u0020\u0065\u006e\u0063\u0020\u0069\u006d\u0070\u0072\u006f\u0076\u0065\u0073\u003a\u0020\u0025\u0064\u0020\u0074o\u0020\u0025\u0064\u0020\u0028o\u0072\u0069g\u0020\u0025\u0064\u0029",len (_edc ),len (_egda ),len (_fggeg .Stream ));
};_edc =_egda ;_gabe =_ada ;};};_caa :=len (_fggeg .Stream );if _caa < len (_edc ){continue ;};_gacb :=&_bbc .PdfObjectStream {Stream :_edc };_gacb .PdfObjectReference =_fggeg .PdfObjectReference ;_gacb .PdfObjectDictionary =_bbc .MakeDict ();_gacb .Merge (_fggeg .PdfObjectDictionary );
_gacb .Merge (_gabe .MakeStreamDict ());_gacb .Set ("\u004c\u0065\u006e\u0067\u0074\u0068",_bbc .MakeInteger (int64 (len (_edc ))));_gddg [_fggeg ]=_gacb ;_dfc [_egba ].Stream =_gacb ;};_cbf =make ([]_bbc .PdfObject ,len (objects ));copy (_cbf ,objects );
_bba (_cbf ,_gddg );return _cbf ,nil ;};func _bbb (_dfa _bbc .PdfObject )[]content {if _dfa ==nil {return nil ;};_fgc ,_abgc :=_bbc .GetArray (_dfa );if !_abgc {_e .Log .Debug ("\u0041\u006e\u006e\u006fts\u0020\u006e\u006f\u0074\u0020\u0061\u006e\u0020\u0061\u0072\u0072\u0061\u0079");
return nil ;};var _abb []content ;for _ ,_fce :=range _fgc .Elements (){_fbed ,_fgb :=_bbc .GetDict (_fce );if !_fgb {_e .Log .Debug ("I\u0067\u006e\u006f\u0072\u0069\u006eg\u0020\u006e\u006f\u006e\u002d\u0064i\u0063\u0074\u0020\u0065\u006c\u0065\u006de\u006e\u0074\u0020\u0069\u006e\u0020\u0041\u006e\u006e\u006ft\u0073");
continue ;};_gccf ,_fgb :=_bbc .GetDict (_fbed .Get ("\u0041\u0050"));if !_fgb {_e .Log .Debug ("\u004e\u006f\u0020\u0041P \u0065\u006e\u0074\u0072\u0079\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067");continue ;};_cfdf :=_bbc .TraceToDirectObject (_gccf .Get ("\u004e"));
if _cfdf ==nil {_e .Log .Debug ("N\u006f\u0020\u004e\u0020en\u0074r\u0079\u0020\u002d\u0020\u0073k\u0069\u0070\u0070\u0069\u006e\u0067");continue ;};var _gba *_bbc .PdfObjectStream ;switch _def :=_cfdf .(type ){case *_bbc .PdfObjectDictionary :_aae ,_dgf :=_bbc .GetName (_fbed .Get ("\u0041\u0053"));
if !_dgf {_e .Log .Debug ("\u004e\u006f\u0020\u0041S \u0065\u006e\u0074\u0072\u0079\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067");continue ;};_gba ,_dgf =_bbc .GetStream (_def .Get (*_aae ));if !_dgf {_e .Log .Debug ("\u0046o\u0072\u006d\u0020\u006eo\u0074\u0020\u0066\u006f\u0075n\u0064 \u002d \u0073\u006b\u0069\u0070\u0070\u0069\u006eg");
continue ;};case *_bbc .PdfObjectStream :_gba =_def ;};if _gba ==nil {_e .Log .Debug ("\u0046\u006f\u0072m\u0020\u006e\u006f\u0074 \u0066\u006f\u0075\u006e\u0064\u0020\u0028n\u0069\u006c\u0029\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069\u006e\u0067");
continue ;};_acg ,_aec :=_da .NewXObjectFormFromStream (_gba );if _aec !=nil {_e .Log .Debug ("\u0045\u0072\u0072\u006f\u0072\u0020l\u006f\u0061\u0064\u0069\u006e\u0067\u0020\u0066\u006f\u0072\u006d\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_aec );
continue ;};_gfg ,_aec :=_acg .GetContentStream ();if _aec !=nil {_e .Log .Debug ("E\u0072\u0072\u006f\u0072\u0020\u0064e\u0063\u006f\u0064\u0069\u006e\u0067\u0020\u0063\u006fn\u0074\u0065\u006et\u0073:\u0020\u0025\u0076",_aec );continue ;};_abb =append (_abb ,content {_aebg :string (_gfg ),_daad :_acg .Resources });
};return _abb ;};func _cegc (_edgb []_bbc .PdfObject ){for _ddef ,_eged :=range _edgb {switch _dafb :=_eged .(type ){case *_bbc .PdfIndirectObject :_dafb .ObjectNumber =int64 (_ddef +1);_dafb .GenerationNumber =0;case *_bbc .PdfObjectStream :_dafb .ObjectNumber =int64 (_ddef +1);
_dafb .GenerationNumber =0;case *_bbc .PdfObjectStreams :_dafb .ObjectNumber =int64 (_ddef +1);_dafb .GenerationNumber =0;};};};func _bcg (_cbc []_bbc .PdfObject )(_aeg map[*_bbc .PdfObjectStream ]struct{},_ef error ){_aeg =map[*_bbc .PdfObjectStream ]struct{}{};
_age :=map[*_da .PdfFont ]struct{}{};_bdcd :=_bgef (_cbc );for _ ,_deb :=range _bdcd ._gddf {_gd ,_gcc :=_bbc .GetDict (_deb .PdfObject );if !_gcc {continue ;};_bfe ,_gcc :=_bbc .GetDict (_gd .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));if !_gcc {continue ;
};_bbcb ,_ :=_fcfd (_gd .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));_bff ,_cd :=_da .NewPdfPageResourcesFromDict (_bfe );if _cd !=nil {return nil ,_cd ;};_ace :=[]content {{_aebg :_bbcb ,_daad :_bff }};_degf :=_bbb (_gd .Get ("\u0041\u006e\u006e\u006f\u0074\u0073"));
if _degf !=nil {_ace =append (_ace ,_degf ...);};for _ ,_gcb :=range _ace {_fbg ,_egf :=_eef .NewFromContents (_gcb ._aebg ,_gcb ._daad );if _egf !=nil {return nil ,_egf ;};_fba ,_ ,_ ,_egf :=_fbg .ExtractPageText ();if _egf !=nil {return nil ,_egf ;};
for _ ,_fe :=range _fba .Marks ().Elements (){if _fe .Font ==nil {continue ;};if _ ,_daa :=_age [_fe .Font ];!_daa {_age [_fe .Font ]=struct{}{};};};};};_dcc :=map[*_bbc .PdfObjectStream ][]*_da .PdfFont {};for _aaa :=range _age {_edg :=_aaa .FontDescriptor ();
if _edg ==nil ||_edg .FontFile2 ==nil {continue ;};_abd ,_abde :=_bbc .GetStream (_edg .FontFile2 );if !_abde {continue ;};_dcc [_abd ]=append (_dcc [_abd ],_aaa );};for _fec :=range _dcc {var _ffb []rune ;var _geb []_cb .GlyphIndex ;for _ ,_acb :=range _dcc [_fec ]{switch _eca :=_acb .Encoder ().(type ){case _d .GIDRegistry :for _ ,_fea :=range _eca .RegisteredGIDs (){_geb =append (_geb ,_cb .GlyphIndex (_fea ));
};case _d .RuneRegistry :_ffb =append (_ffb ,_eca .RegisteredRunes ()...);case _d .SimpleEncoder :_dbf :=_eca .Charcodes ();for _ ,_cge :=range _dbf {_dbe ,_cgg :=_eca .CharcodeToRune (_cge );if !_cgg {_e .Log .Debug ("\u0043\u0068a\u0072\u0063\u006f\u0064\u0065\u003c\u002d\u003e\u0072\u0075\u006e\u0065\u0020\u006e\u006f\u0074\u0020\u0066\u006f\u0075\u006e\u0064: \u0025\u0064",_cge );
continue ;};_ffb =append (_ffb ,_dbe );};};};if len (_ffb )==0&&len (_geb )==0{_e .Log .Debug ("\u004e\u006f\u0020\u0072\u0065\u0067\u0069\u0073t\u0065\u0072\u0065d \u0072\u0075\u006e\u0065\u0073\u0020o\u0072\u0020\u0069\u006e\u0064\u0069\u0063\u0065\u0073\u0020\u002d\u0020\u0073\u006b\u0069p\u0020\u0073\u0075\u0062\u0073\u0065\u0074\u0074i\u006e\u0067");
continue ;};_ef =_gaca (_fec ,_ffb ,_geb );if _ef !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020\u0073\u0075\u0062\u0073\u0065\u0074\u0074\u0069\u006eg\u0020f\u006f\u006e\u0074\u0020\u0073\u0074\u0072\u0065\u0061\u006d\u003a\u0020\u0025\u0076",_ef );
return nil ,_ef ;};_aeg [_fec ]=struct{}{};};return _aeg ,nil ;};

// CombineIdenticalIndirectObjects combines identical indirect objects.
// It implements interface model.Optimizer.
type CombineIdenticalIndirectObjects struct{};

// Optimize optimizes PDF objects to decrease PDF size.
func (_bffe *CombineDuplicateStreams )Optimize (objects []_bbc .PdfObject )(_ggc []_bbc .PdfObject ,_gff error ){_egb :=make (map[_bbc .PdfObject ]_bbc .PdfObject );_ceg :=make (map[_bbc .PdfObject ]struct{});_bbbg :=make (map[string ][]*_bbc .PdfObjectStream );
for _ ,_faf :=range objects {_acae ,_baf :=_faf .(*_bbc .PdfObjectStream );if !_baf {continue ;};if _acae .Lazy {continue ;};_dgc :=_ee .New ();_dgc .Write (_acae .Stream );_dgc .Write (_acae .PdfObjectDictionary .Write ());_cdeg :=string (_dgc .Sum (nil ));
_bbbg [_cdeg ]=append (_bbbg [_cdeg ],_acae );};for _ ,_bec :=range _bbbg {if len (_bec )< 2{continue ;};_cbac :=_bec [0];for _aab :=1;_aab < len (_bec );_aab ++{_cgad :=_bec [_aab ];_egb [_cgad ]=_cbac ;_ceg [_cgad ]=struct{}{};};};_ggc =make ([]_bbc .PdfObject ,0,len (objects )-len (_ceg ));
for _ ,_eccc :=range objects {if _ ,_cggb :=_ceg [_eccc ];_cggb {continue ;};_ggc =append (_ggc ,_eccc );};_bba (_ggc ,_egb );return _ggc ,nil ;};

// Optimize implements Optimizer interface.
func (_fad *CleanUnusedResources )Optimize (objects []_bbc .PdfObject )(_gfga []_bbc .PdfObject ,_cdbd error ){_fbb ,_cdbd :=_bab (objects );if _cdbd !=nil {return nil ,_cdbd ;};_aedd :=[]_bbc .PdfObject {};for _ ,_feg :=range objects {_ ,_dbed :=_fbb [_feg ];
if _dbed {continue ;};_aedd =append (_aedd ,_feg );};return _aedd ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_bece *CompressStreams )Optimize (objects []_bbc .PdfObject )(_bfc []_bbc .PdfObject ,_eaga error ){_bfc =make ([]_bbc .PdfObject ,len (objects ));copy (_bfc ,objects );for _ ,_cbag :=range objects {_adfg ,_becb :=_bbc .GetStream (_cbag );if !_becb {continue ;
};if _geba :=_adfg .Get ("\u0046\u0069\u006c\u0074\u0065\u0072");_geba !=nil {if _ ,_fbfe :=_bbc .GetName (_geba );_fbfe {continue ;};if _dfad ,_fadc :=_bbc .GetArray (_geba );_fadc &&_dfad .Len ()> 0{continue ;};};_dcegf :=_bbc .NewFlateEncoder ();var _gebe []byte ;
_gebe ,_eaga =_dcegf .EncodeBytes (_adfg .Stream );if _eaga !=nil {return _bfc ,_eaga ;};_gcf :=_dcegf .MakeStreamDict ();if len (_gebe )+len (_gcf .Write ())< len (_adfg .Stream ){_adfg .Stream =_gebe ;_adfg .PdfObjectDictionary .Merge (_gcf );_adfg .PdfObjectDictionary .Set ("\u004c\u0065\u006e\u0067\u0074\u0068",_bbc .MakeInteger (int64 (len (_adfg .Stream ))));
};};return _bfc ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_bedf *ObjectStreams )Optimize (objects []_bbc .PdfObject )(_edcc []_bbc .PdfObject ,_cfdc error ){_bfeb :=&_bbc .PdfObjectStreams {};_aee :=make ([]_bbc .PdfObject ,0,len (objects ));for _ ,_ggg :=range objects {if _abada ,_fcfe :=_ggg .(*_bbc .PdfIndirectObject );
_fcfe &&_abada .GenerationNumber ==0{_bfeb .Append (_ggg );}else {_aee =append (_aee ,_ggg );};};if _bfeb .Len ()==0{return _aee ,nil ;};_edcc =make ([]_bbc .PdfObject ,0,len (_aee )+_bfeb .Len ()+1);if _bfeb .Len ()> 1{_edcc =append (_edcc ,_bfeb );};
_edcc =append (_edcc ,_bfeb .Elements ()...);_edcc =append (_edcc ,_aee ...);return _edcc ,nil ;};type content struct{_aebg string ;_daad *_da .PdfPageResources ;};

// CleanContentstream cleans up redundant operands in content streams, including Page and XObject Form
// contents. This process includes:
// 1. Marked content operators are removed.
// 2. Some operands are simplified (shorter form).
// TODO: Add more reduction methods and improving the methods for identifying unnecessary operands.
type CleanContentstream struct{};func _eeff (_gede *_da .Image ,_gbfa float64 )(*_da .Image ,error ){_ddfc ,_dda :=_gede .ToGoImage ();if _dda !=nil {return nil ,_dda ;};var _cae _bb .Image ;_caba ,_bfcf :=_ddfc .(*_bb .Monochrome );if _bfcf {if _dda =_caba .ResolveDecode ();
_dda !=nil {return nil ,_dda ;};_cae ,_dda =_caba .Scale (_gbfa );if _dda !=nil {return nil ,_dda ;};}else {_dcba :=int (_b .RoundToEven (float64 (_gede .Width )*_gbfa ));_aaab :=int (_b .RoundToEven (float64 (_gede .Height )*_gbfa ));_cae ,_dda =_bb .NewImage (_dcba ,_aaab ,int (_gede .BitsPerComponent ),_gede .ColorComponents ,nil ,nil ,nil );
if _dda !=nil {return nil ,_dda ;};_ed .CatmullRom .Scale (_cae ,_cae .Bounds (),_ddfc ,_ddfc .Bounds (),_ed .Over ,&_ed .Options {});};_dba :=_cae .Base ();_gddc :=&_da .Image {Width :int64 (_dba .Width ),Height :int64 (_dba .Height ),BitsPerComponent :int64 (_dba .BitsPerComponent ),ColorComponents :_dba .ColorComponents ,Data :_dba .Data };
_gddc .SetDecode (_dba .Decode );_gddc .SetAlpha (_dba .Alpha );return _gddc ,nil ;};func _bab (_gbfe []_bbc .PdfObject )(map[_bbc .PdfObject ]struct{},error ){_ced :=_bgef (_gbfe );_cgec :=_ced ._gddf ;_aag :=make (map[_bbc .PdfObject ]struct{});_efce :=_dbd (_cgec );
for _ ,_aga :=range _cgec {_ecef ,_fbgc :=_bbc .GetDict (_aga .PdfObject );if !_fbgc {continue ;};_bgf ,_fbgc :=_bbc .GetDict (_ecef .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));if !_fbgc {continue ;};_cbd :=_efce ["\u0058O\u0062\u006a\u0065\u0063\u0074"];
_ebe ,_fbgc :=_bbc .GetDict (_bgf .Get ("\u0058O\u0062\u006a\u0065\u0063\u0074"));if _fbgc {_afd :=_daeg (_ebe );for _ ,_fde :=range _afd {if _eaeb (_fde ,_cbd ){continue ;};_ddb :=*_bbc .MakeName (_fde );_ebf :=_ebe .Get (_ddb );_aag [_ebf ]=struct{}{};
_ebe .Remove (_ddb );_ddf :=_dbc (_ebf ,_aag );if _ddf !=nil {_e .Log .Debug ("\u0066\u0061\u0069\u006ce\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065r\u0073e\u0020\u006f\u0062\u006a\u0065\u0063\u0074 \u0025\u0076",_ebf );};};};_ccd ,_fbgc :=_bbc .GetDict (_bgf .Get ("\u0046\u006f\u006e\u0074"));
_bdce :=_efce ["\u0046\u006f\u006e\u0074"];if _fbgc {_debd :=_daeg (_ccd );for _ ,_ggb :=range _debd {if _eaeb (_ggb ,_bdce ){continue ;};_ggfg :=*_bbc .MakeName (_ggb );_ecf :=_ccd .Get (_ggfg );_aag [_ecf ]=struct{}{};_ccd .Remove (_ggfg );_cdg :=_dbc (_ecf ,_aag );
if _cdg !=nil {_e .Log .Debug ("\u0046\u0061i\u006c\u0065\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065\u0072\u0073\u0065\u0020\u006f\u0062\u006a\u0065\u0063\u0074 %\u0076\u000a",_ecf );};};};_fdd ,_fbgc :=_bbc .GetDict (_bgf .Get ("\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"));
if _fbgc {_cdeb :=_daeg (_fdd );_cca :=_efce ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"];for _ ,_fedd :=range _cdeb {if _eaeb (_fedd ,_cca ){continue ;};_fgg :=*_bbc .MakeName (_fedd );_fcb :=_fdd .Get (_fgg );_aag [_fcb ]=struct{}{};_fdd .Remove (_fgg );
_fdc :=_dbc (_fcb ,_aag );if _fdc !=nil {_e .Log .Debug ("\u0066\u0061i\u006c\u0065\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065\u0072\u0073\u0065\u0020\u006f\u0062\u006a\u0065\u0063\u0074 %\u0076\u000a",_fcb );};};};};return _aag ,nil ;
};

// Optimize optimizes PDF objects to decrease PDF size.
func (_bbd *Chain )Optimize (objects []_bbc .PdfObject )(_aba []_bbc .PdfObject ,_gb error ){_gc :=objects ;for _ ,_abae :=range _bbd ._f {_ca ,_eb :=_abae .Optimize (_gc );if _eb !=nil {_e .Log .Debug ("\u0045\u0052\u0052OR\u0020\u004f\u0070\u0074\u0069\u006d\u0069\u007a\u0061\u0074\u0069\u006f\u006e\u003a\u0020\u0025\u002b\u0076",_eb );
continue ;};_gc =_ca ;};return _gc ,nil ;};

// Image optimizes images by rewrite images into JPEG format with quality equals to ImageQuality.
// TODO(a5i): Add support for inline images.
// It implements interface model.Optimizer.
type Image struct{ImageQuality int ;};func _abcf (_edda *_da .XObjectImage ,_abab imageModifications )error {_eeb ,_fbgf :=_edda .ToImage ();if _fbgf !=nil {return _fbgf ;};if _abab .Scale !=0{_eeb ,_fbgf =_eeff (_eeb ,_abab .Scale );if _fbgf !=nil {return _fbgf ;
};};if _abab .Encoding !=nil {_edda .Filter =_abab .Encoding ;};_edda .Decode =nil ;switch _gdbf :=_edda .Filter .(type ){case *_bbc .FlateEncoder :if _gdbf .Predictor !=1&&_gdbf .Predictor !=11{_gdbf .Predictor =1;};};if _fbgf =_edda .SetImage (_eeb ,nil );
_fbgf !=nil {_e .Log .Debug ("\u0045\u0072\u0072or\u0020\u0073\u0065\u0074\u0074\u0069\u006e\u0067\u0020\u0069\u006d\u0061\u0067\u0065\u003a\u0020\u0025\u0076",_fbgf );return _fbgf ;};_edda .ToPdfObject ();return nil ;};type objectStructure struct{_eddc *_bbc .PdfObjectDictionary ;
_edgc *_bbc .PdfObjectDictionary ;_gddf []*_bbc .PdfIndirectObject ;};

// LinearizeWithOptions is the same as Linearize but additionally configures
// the linearization options. Callers wanting object-stream packaging
// (LinearizationOptions.UseObjectStreams) use this entry point.
func LinearizeWithOptions (w *_da .PdfWriter ,opts _da .LinearizationOptions ){w .SetLinearized (true );w .SetLinearizationOptions (opts );};

// Optimize optimizes PDF objects to decrease PDF size.
func (_abaec *ImagePPI )Optimize (objects []_bbc .PdfObject )(_fbc []_bbc .PdfObject ,_ded error ){if _abaec .ImageUpperPPI <=0{return objects ,nil ;};_afe :=_cfba (objects );if len (_afe )==0{return objects ,nil ;};_efcb :=make (map[_bbc .PdfObject ]struct{});
for _ ,_eaa :=range _afe {_dfdg :=_eaa .Stream .PdfObjectDictionary .Get ("\u0053\u004d\u0061s\u006b");_efcb [_dfdg ]=struct{}{};};_fadg :=make (map[*_bbc .PdfObjectStream ]*imageInfo );for _ ,_fdda :=range _afe {_fadg [_fdda .Stream ]=_fdda ;};var _cee *_bbc .PdfObjectDictionary ;
for _ ,_egbd :=range objects {if _fddc ,_bga :=_bbc .GetDict (_egbd );_cee ==nil &&_bga {if _cfec ,_eec :=_bbc .GetName (_fddc .Get ("\u0054\u0079\u0070\u0065"));_eec &&*_cfec =="\u0043a\u0074\u0061\u006c\u006f\u0067"{_cee =_fddc ;};};};if _cee ==nil {return objects ,nil ;
};_cag ,_fgbda :=_bbc .GetDict (_cee .Get ("\u0050\u0061\u0067e\u0073"));if !_fgbda {return objects ,nil ;};_gef ,_dea :=_bbc .GetArray (_cag .Get ("\u004b\u0069\u0064\u0073"));if !_dea {return objects ,nil ;};for _ ,_ebfd :=range _gef .Elements (){_gecf :=make (map[string ]*imageInfo );
_ffe ,_eee :=_bbc .GetDict (_ebfd );if !_eee {continue ;};_afeb ,_ :=_fcfd (_ffe .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));if len (_afeb )==0{continue ;};_cdegc ,_bgec :=_bbc .GetDict (_ffe .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));
if !_bgec {continue ;};_ddg ,_fac :=_da .NewPdfPageResourcesFromDict (_cdegc );if _fac !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0072\u0065\u0073\u006f\u0075\u0072\u0063\u0065\u0073\u0020-\u0020\u0069\u0067\u006e\u006fr\u0069\u006eg\u003a\u0020\u0025\u0076",_fac );
continue ;};_gbd ,_defb :=_bbc .GetDict (_cdegc .Get ("\u0058O\u0062\u006a\u0065\u0063\u0074"));if !_defb {continue ;};_bagb :=_gbd .Keys ();for _ ,_baba :=range _bagb {if _degd ,_baga :=_bbc .GetStream (_gbd .Get (_baba ));_baga {if _ecefe ,_gda :=_fadg [_degd ];
_gda {_gecf [string (_baba )]=_ecefe ;};};};_dde :=_g .NewContentStreamParser (_afeb );_cdgb ,_fac :=_dde .Parse ();if _fac !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_fac );continue ;};_bgc :=_g .NewContentStreamProcessor (*_cdgb );
_bgc .AddHandler (_g .HandlerConditionEnumAllOperands ,"",func (_aecf *_g .ContentStreamOperation ,_gbfb _g .GraphicsState ,_ebddf *_da .PdfPageResources )error {switch _aecf .Operand {case "\u0044\u006f":if len (_aecf .Params )!=1{_e .Log .Debug ("E\u0052\u0052\u004f\u0052\u003a\u0020\u0049\u0067\u006e\u006f\u0072\u0069\u006e\u0067\u0020\u0044\u006f\u0020w\u0069\u0074\u0068\u0020\u006c\u0065\u006e\u0028\u0070\u0061ra\u006d\u0073\u0029 \u0021=\u0020\u0031");
return nil ;};_bda ,_ddag :=_bbc .GetName (_aecf .Params [0]);if !_ddag {_e .Log .Debug ("\u0045\u0052\u0052O\u0052\u003a\u0020\u0049\u0067\u006e\u006f\u0072\u0069\u006e\u0067\u0020\u0044\u006f\u0020\u0077\u0069\u0074\u0068\u0020\u006e\u006f\u006e\u0020\u004e\u0061\u006d\u0065\u0020p\u0061\u0072\u0061\u006d\u0065\u0074\u0065\u0072");
return nil ;};if _adfb ,_deca :=_gecf [string (*_bda )];_deca {_feef :=_gbfb .CTM .ScalingFactorX ();_geeg :=_gbfb .CTM .ScalingFactorY ();_fbdba ,_egbf :=_feef /72.0,_geeg /72.0;_ebfa ,_bef :=float64 (_adfb .Width )/_fbdba ,float64 (_adfb .Height )/_egbf ;
if _fbdba ==0||_egbf ==0{_ebfa =72.0;_bef =72.0;};_adfb .PPI =_b .Max (_adfb .PPI ,_ebfa );_adfb .PPI =_b .Max (_adfb .PPI ,_bef );};};return nil ;});_fac =_bgc .Process (_ddg );if _fac !=nil {_e .Log .Debug ("E\u0052\u0052\u004f\u0052 p\u0072o\u0063\u0065\u0073\u0073\u0069n\u0067\u003a\u0020\u0025\u002b\u0076",_fac );
continue ;};};for _ ,_gfeae :=range _afe {if _ ,_abdc :=_efcb [_gfeae .Stream ];_abdc {continue ;};if _gfeae .PPI <=_abaec .ImageUpperPPI {continue ;};_bee ,_ceeb :=_da .NewXObjectImageFromStream (_gfeae .Stream );if _ceeb !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_ceeb );
continue ;};var _dafd imageModifications ;_dafd .Scale =_abaec .ImageUpperPPI /_gfeae .PPI ;if _gfeae .BitsPerComponent ==1&&_gfeae .ColorComponents ==1{_geaa :=_b .Round (_gfeae .PPI /_abaec .ImageUpperPPI );_bddb :=_bb .NextPowerOf2 (uint (_geaa ));if _bb .InDelta (float64 (_bddb ),1/_dafd .Scale ,0.3){_dafd .Scale =float64 (1)/float64 (_bddb );
};if _ ,_cgf :=_bee .Filter .(*_bbc .JBIG2Encoder );!_cgf {_dafd .Encoding =_bbc .NewJBIG2Encoder ();};};if _ceeb =_abcf (_bee ,_dafd );_ceeb !=nil {_e .Log .Debug ("\u0045\u0072\u0072\u006f\u0072 \u0073\u0063\u0061\u006c\u0065\u0020\u0069\u006d\u0061\u0067\u0065\u0020\u006be\u0065\u0070\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u0069\u006d\u0061\u0067\u0065\u003a\u0020\u0025\u0073",_ceeb );
continue ;};_dafd .Encoding =nil ;if _bfb ,_ebce :=_bbc .GetStream (_gfeae .Stream .PdfObjectDictionary .Get ("\u0053\u004d\u0061s\u006b"));_ebce {_agefg ,_gdg :=_da .NewXObjectImageFromStream (_bfb );if _gdg !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_gdg );
continue ;};if _gdg =_abcf (_agefg ,_dafd );_gdg !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_gdg );continue ;};};};return objects ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_efcc *CombineDuplicateDirectObjects )Optimize (objects []_bbc .PdfObject )(_dfe []_bbc .PdfObject ,_gbaa error ){_cegc (objects );_aaed :=make (map[string ][]*_bbc .PdfObjectDictionary );var _ggd func (_fgge *_bbc .PdfObjectDictionary );_ggd =func (_aced *_bbc .PdfObjectDictionary ){for _ ,_gbc :=range _aced .Keys (){_fee :=_aced .Get (_gbc );
if _dac ,_fcba :=_fee .(*_bbc .PdfObjectDictionary );_fcba {if _baec :=_dac .Keys ();len (_baec )==0{continue ;};_bgg :=_eda .New ();_bgg .Write (_dac .Write ());_dfg :=string (_bgg .Sum (nil ));_aaed [_dfg ]=append (_aaed [_dfg ],_dac );_ggd (_dac );};
};};for _ ,_gbg :=range objects {_egd ,_gab :=_gbg .(*_bbc .PdfIndirectObject );if !_gab {continue ;};if _gfd ,_aaee :=_egd .PdfObject .(*_bbc .PdfObjectDictionary );_aaee {_ggd (_gfd );};};_gdd :=make ([]_bbc .PdfObject ,0,len (_aaed ));_bdg :=make (map[_bbc .PdfObject ]_bbc .PdfObject );
for _ ,_bdd :=range _aaed {if len (_bdd )< 2{continue ;};_ebd :=_bbc .MakeDict ();_ebd .Merge (_bdd [0]);_dagc :=_bbc .MakeIndirectObject (_ebd );_gdd =append (_gdd ,_dagc );for _ebdf :=0;_ebdf < len (_bdd );_ebdf ++{_ddbd :=_bdd [_ebdf ];_bdg [_ddbd ]=_dagc ;
};};_dfe =make ([]_bbc .PdfObject ,len (objects ));copy (_dfe ,objects );_dfe =append (_gdd ,_dfe ...);_bba (_dfe ,_bdg );return _dfe ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_cbg *CleanContentstream )Optimize (objects []_bbc .PdfObject )(_ae []_bbc .PdfObject ,_bad error ){_gac :=map[*_bbc .PdfObjectStream ]struct{}{};var _gf []*_bbc .PdfObjectStream ;_gaa :=func (_badf *_bbc .PdfObjectStream ){if _ ,_dgg :=_gac [_badf ];
!_dgg {_gac [_badf ]=struct{}{};_gf =append (_gf ,_badf );};};_ge :=map[_bbc .PdfObject ]bool {};_abg :=map[_bbc .PdfObject ]bool {};for _ ,_cc :=range objects {switch _db :=_cc .(type ){case *_bbc .PdfIndirectObject :switch _cf :=_db .PdfObject .(type ){case *_bbc .PdfObjectDictionary :if _dbb ,_ffg :=_bbc .GetName (_cf .Get ("\u0054\u0079\u0070\u0065"));
!_ffg ||_dbb .String ()!="\u0050\u0061\u0067\u0065"{continue ;};if _aca ,_eag :=_bbc .GetStream (_cf .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));_eag {_gaa (_aca );}else if _ecd ,_cg :=_bbc .GetArray (_cf .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));
_cg {var _ag []*_bbc .PdfObjectStream ;for _ ,_eg :=range _ecd .Elements (){if _bc ,_gaf :=_bbc .GetStream (_eg );_gaf {_ag =append (_ag ,_bc );};};if len (_ag )> 0{var _gafa _ab .Buffer ;for _ ,_cfa :=range _ag {if _dee ,_bbg :=_bbc .DecodeStream (_cfa );
_bbg ==nil {_gafa .Write (_dee );};_ge [_cfa ]=true ;};_be ,_bcc :=_bbc .MakeStream (_gafa .Bytes (),_bbc .NewFlateEncoder ());if _bcc !=nil {return nil ,_bcc ;};_abg [_be ]=true ;_cf .Set ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073",_be );_gaa (_be );
};};};case *_bbc .PdfObjectStream :if _egc ,_acc :=_bbc .GetName (_db .Get ("\u0054\u0079\u0070\u0065"));!_acc ||_egc .String ()!="\u0058O\u0062\u006a\u0065\u0063\u0074"{continue ;};if _ead ,_bgd :=_bbc .GetName (_db .Get ("\u0053u\u0062\u0074\u0079\u0070\u0065"));
!_bgd ||_ead .String ()!="\u0046\u006f\u0072\u006d"{continue ;};_gaa (_db );};};for _ ,_dc :=range _gf {_bad =_fc (_dc );if _bad !=nil {return nil ,_bad ;};};_ae =nil ;for _ ,_fb :=range objects {if _ge [_fb ]{continue ;};_ae =append (_ae ,_fb );};for _dag :=range _abg {_ae =append (_ae ,_dag );
};return _ae ,nil ;};func _acd (_fcd _bbc .PdfObject )(string ,error ){_dcd :=_bbc .TraceToDirectObject (_fcd );switch _dca :=_dcd .(type ){case *_bbc .PdfObjectString :return _dca .Str (),nil ;case *_bbc .PdfObjectStream :_dec ,_dgfd :=_bbc .DecodeStream (_dca );
if _dgfd !=nil {return "",_dgfd ;};return string (_dec ),nil ;};return "",_bd .Errorf ("\u0069\u006e\u0076\u0061\u006ci\u0064\u0020\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u0020\u0073\u0074\u0072e\u0061\u006d\u0020\u006f\u0062\u006a\u0065\u0063\u0074\u0020\u0068\u006f\u006c\u0064\u0065\u0072\u0020\u0028\u0025\u0054\u0029",_dcd );
};func _ce (_ff *_g .ContentStreamOperations )*_g .ContentStreamOperations {if _ff ==nil {return nil ;};_ga :=_g .ContentStreamOperations {};for _ ,_gg :=range *_ff {switch _gg .Operand {case "\u0042\u0044\u0043","\u0042\u004d\u0043","\u0045\u004d\u0043":continue ;
case "\u0054\u006d":if len (_gg .Params )==6{if _abf ,_bg :=_bbc .GetNumbersAsFloat (_gg .Params );_bg ==nil {if _abf [0]==1&&_abf [1]==0&&_abf [2]==0&&_abf [3]==1{_gg =&_g .ContentStreamOperation {Params :[]_bbc .PdfObject {_gg .Params [4],_gg .Params [5]},Operand :"\u0054\u0064"};
};};};};_ga =append (_ga ,_gg );};return &_ga ;};

// GetOptimizers gets the list of optimizers in chain `c`.
func (_aa *Chain )GetOptimizers ()[]_da .Optimizer {return _aa ._f };

// New creates a optimizers chain from options.
func New (options Options )*Chain {_cabc :=new (Chain );if options .CleanFonts ||options .SubsetFonts {_cabc .Append (&CleanFonts {Subset :options .SubsetFonts });};if options .CleanContentstream {_cabc .Append (new (CleanContentstream ));};if options .ImageUpperPPI > 0{_ddec :=new (ImagePPI );
_ddec .ImageUpperPPI =options .ImageUpperPPI ;_cabc .Append (_ddec );};if options .ImageQuality > 0{_fead :=new (Image );_fead .ImageQuality =options .ImageQuality ;_cabc .Append (_fead );};if options .CombineDuplicateDirectObjects {_cabc .Append (new (CombineDuplicateDirectObjects ));
};if options .CombineDuplicateStreams {_cabc .Append (new (CombineDuplicateStreams ));};if options .CombineIdenticalIndirectObjects {_cabc .Append (new (CombineIdenticalIndirectObjects ));};if options .UseObjectStreams {_cabc .Append (new (ObjectStreams ));
};if options .CompressStreams {_cabc .Append (new (CompressStreams ));};if options .CleanUnusedResources {_cabc .Append (new (CleanUnusedResources ));};return _cabc ;};type imageModifications struct{Scale float64 ;Encoding _bbc .StreamEncoder ;};func _bba (_dgcd []_bbc .PdfObject ,_ceec map[_bbc .PdfObject ]_bbc .PdfObject ){if len (_ceec )==0{return ;
};for _afc ,_feag :=range _dgcd {if _dead ,_fcc :=_ceec [_feag ];_fcc {_dgcd [_afc ]=_dead ;continue ;};_ceec [_feag ]=_feag ;switch _bacb :=_feag .(type ){case *_bbc .PdfObjectArray :_fceb :=make ([]_bbc .PdfObject ,_bacb .Len ());copy (_fceb ,_bacb .Elements ());
_bba (_fceb ,_ceec );for _fdgd ,_gabea :=range _fceb {_bacb .Set (_fdgd ,_gabea );};case *_bbc .PdfObjectStreams :_bba (_bacb .Elements (),_ceec );case *_bbc .PdfObjectStream :_dbfd :=[]_bbc .PdfObject {_bacb .PdfObjectDictionary };_bba (_dbfd ,_ceec );
_bacb .PdfObjectDictionary =_dbfd [0].(*_bbc .PdfObjectDictionary );case *_bbc .PdfObjectDictionary :_gad :=_bacb .Keys ();_cdfe :=make ([]_bbc .PdfObject ,len (_gad ));for _bbcbe ,_adfa :=range _gad {_cdfe [_bbcbe ]=_bacb .Get (_adfa );};_bba (_cdfe ,_ceec );
for _ebfb ,_afa :=range _gad {_bacb .Set (_afa ,_cdfe [_ebfb ]);};case *_bbc .PdfIndirectObject :_abe :=[]_bbc .PdfObject {_bacb .PdfObject };_bba (_abe ,_ceec );_bacb .PdfObject =_abe [0];};};};

// Chain allows to use sequence of optimizers.
// It implements interface model.Optimizer.
type Chain struct{_f []_da .Optimizer };func _dbd (_ega []*_bbc .PdfIndirectObject )map[string ][]string {_gdbb :=map[string ][]string {};for _ ,_efd :=range _ega {_cec ,_eagc :=_bbc .GetDict (_efd .PdfObject );if !_eagc {continue ;};_dce :=_cec .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073");
_dae :=_bbc .TraceToDirectObject (_dce );_ad :="";if _gcafa ,_bbbb :=_dae .(*_bbc .PdfObjectArray );_bbbb {var _dbba []string ;for _ ,_acf :=range _gcafa .Elements (){_ecc ,_efe :=_acd (_acf );if _efe !=nil {continue ;};_dbba =append (_dbba ,_ecc );};_ad =_c .Join (_dbba ,"\u0020");
};if _fbeb ,_ccf :=_dae .(*_bbc .PdfObjectStream );_ccf {_cfbf ,_abgb :=_bbc .DecodeStream (_fbeb );if _abgb !=nil {continue ;};_ad =string (_cfbf );};_fddf :=_g .NewContentStreamParser (_ad );_eae ,_babb :=_fddf .Parse ();if _babb !=nil {continue ;};for _ ,_cfc :=range *_eae {_fbaf :=_cfc .Operand ;
_bbe :=_cfc .Params ;switch _fbaf {case "\u0044\u006f":_ebg :=_bbe [0].String ();if _ ,_fdb :=_gdbb ["\u0058O\u0062\u006a\u0065\u0063\u0074"];!_fdb {_gdbb ["\u0058O\u0062\u006a\u0065\u0063\u0074"]=[]string {_ebg };}else {_gdbb ["\u0058O\u0062\u006a\u0065\u0063\u0074"]=append (_gdbb ["\u0058O\u0062\u006a\u0065\u0063\u0074"],_ebg );
};case "\u0054\u0066":_eff :=_bbe [0].String ();if _ ,_geg :=_gdbb ["\u0046\u006f\u006e\u0074"];!_geg {_gdbb ["\u0046\u006f\u006e\u0074"]=[]string {_eff };}else {_gdbb ["\u0046\u006f\u006e\u0074"]=append (_gdbb ["\u0046\u006f\u006e\u0074"],_eff );};case "\u0067\u0073":_bdcb :=_bbe [0].String ();
if _ ,_adf :=_gdbb ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"];!_adf {_gdbb ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"]=[]string {_bdcb };}else {_gdbb ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"]=append (_gdbb ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"],_bdcb );
};};};};return _gdbb ;};

// CleanUnusedResources represents an optimizer used to clean unused resources.
type CleanUnusedResources struct{};func _fcfd (_deba _bbc .PdfObject )(_bcd string ,_cdd []_bbc .PdfObject ){var _bgb _ab .Buffer ;switch _dff :=_deba .(type ){case *_bbc .PdfIndirectObject :_cdd =append (_cdd ,_dff );_deba =_dff .PdfObject ;};switch _eaae :=_deba .(type ){case *_bbc .PdfObjectStream :if _fdfc ,_baab :=_bbc .DecodeStream (_eaae );
_baab ==nil {_bgb .Write (_fdfc );_cdd =append (_cdd ,_eaae );};case *_bbc .PdfObjectArray :for _ ,_dfee :=range _eaae .Elements (){switch _ffba :=_dfee .(type ){case *_bbc .PdfObjectStream :if _faa ,_ccac :=_bbc .DecodeStream (_ffba );_ccac ==nil {_bgb .Write (_faa );
_cdd =append (_cdd ,_ffba );};};};};return _bgb .String (),_cdd ;};

// ObjectStreams groups PDF objects to object streams.
// It implements interface model.Optimizer.
type ObjectStreams struct{};func _eaeb (_dbcg string ,_bbda []string )bool {for _ ,_beaf :=range _bbda {if _dbcg ==_beaf {return true ;};};return false ;};func _cfba (_dggf []_bbc .PdfObject )[]*imageInfo {_fbeg :=_bbc .PdfObjectName ("\u0053u\u0062\u0074\u0079\u0070\u0065");
_ecea :=make (map[*_bbc .PdfObjectStream ]struct{});var _fcf []*imageInfo ;for _ ,_gga :=range _dggf {_bcbf ,_agef :=_bbc .GetStream (_gga );if !_agef {continue ;};if _ ,_ebdd :=_ecea [_bcbf ];_ebdd {continue ;};_ecea [_bcbf ]=struct{}{};_bddd :=_bcbf .PdfObjectDictionary .Get (_fbeg );
_bbee ,_agef :=_bbc .GetName (_bddd );if !_agef ||string (*_bbee )!="\u0049\u006d\u0061g\u0065"{continue ;};_acdf :=&imageInfo {Stream :_bcbf ,BitsPerComponent :8};if _gbcc ,_ecae :=_bbc .GetIntVal (_bcbf .Get ("\u0042\u0069t\u0073\u0050\u0065r\u0043\u006f\u006d\u0070\u006f\u006e\u0065\u006e\u0074"));
_ecae {_acdf .BitsPerComponent =_gbcc ;};if _gfa ,_bcad :=_bbc .GetIntVal (_bcbf .Get ("\u0057\u0069\u0064t\u0068"));_bcad {_acdf .Width =_gfa ;};if _eada ,_ggfaa :=_bbc .GetIntVal (_bcbf .Get ("\u0048\u0065\u0069\u0067\u0068\u0074"));_ggfaa {_acdf .Height =_eada ;
};_becbf ,_daf :=_da .NewPdfColorspaceFromPdfObject (_bcbf .Get ("\u0043\u006f\u006c\u006f\u0072\u0053\u0070\u0061\u0063\u0065"));if _daf !=nil {_e .Log .Debug ("\u0045R\u0052\u004f\u0052\u003a\u0020\u0025v",_daf );continue ;};if _becbf ==nil {_feec ,_aabc :=_bbc .GetName (_bcbf .Get ("\u0046\u0069\u006c\u0074\u0065\u0072"));
if _aabc {switch _feec .String (){case "\u0043\u0043\u0049\u0054\u0054\u0046\u0061\u0078\u0044e\u0063\u006f\u0064\u0065","J\u0042\u0049\u0047\u0032\u0044\u0065\u0063\u006f\u0064\u0065":_becbf =_da .NewPdfColorspaceDeviceGray ();_acdf .BitsPerComponent =1;
};};};switch _gdf :=_becbf .(type ){case *_da .PdfColorspaceDeviceRGB :_acdf .ColorComponents =3;case *_da .PdfColorspaceDeviceGray :_acdf .ColorComponents =1;default:_e .Log .Debug ("\u004f\u0070\u0074\u0069\u006d\u0069\u007aa\u0074\u0069\u006fn\u0020\u0069\u0073 \u006e\u006ft\u0020\u0073\u0075\u0070\u0070\u006fr\u0074ed\u0020\u0066\u006f\u0072\u0020\u0063\u006f\u006c\u006f\u0072\u0020\u0073\u0070\u0061\u0063\u0065\u0020\u0025\u0054\u0020\u002d\u0020\u0073\u006b\u0069\u0070",_gdf );
continue ;};_fcf =append (_fcf ,_acdf );};return _fcf ;};

// Options describes PDF optimization parameters.
type Options struct{CombineDuplicateStreams bool ;CombineDuplicateDirectObjects bool ;ImageUpperPPI float64 ;ImageQuality int ;UseObjectStreams bool ;CombineIdenticalIndirectObjects bool ;CompressStreams bool ;CleanFonts bool ;SubsetFonts bool ;CleanContentstream bool ;
CleanUnusedResources bool ;};