//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package optimize ;import (_da "bytes";_ga "crypto/md5";_d "crypto/sha256";_ea "errors";_a "fmt";_e "github.com/unidoc/unipdf/v4/common";_ba "github.com/unidoc/unipdf/v4/contentstream";_bb "github.com/unidoc/unipdf/v4/core";_ab "github.com/unidoc/unipdf/v4/extractor";
_gf "github.com/unidoc/unipdf/v4/internal/imageutil";_bc "github.com/unidoc/unipdf/v4/internal/textencoding";_abe "github.com/unidoc/unipdf/v4/model";_gaf "github.com/unidoc/unitype";_g "golang.org/x/image/draw";_b "math";_fd "strings";);type imageModifications struct{Scale float64 ;
Encoding _bb .StreamEncoder ;};

// Chain allows to use sequence of optimizers.
// It implements interface model.Optimizer.
type Chain struct{_bd []_abe .Optimizer };

// GetOptimizers gets the list of optimizers in chain `c`.
func (_gc *Chain )GetOptimizers ()[]_abe .Optimizer {return _gc ._bd };type objectStructure struct{_bfec *_bb .PdfObjectDictionary ;_gac *_bb .PdfObjectDictionary ;_dfcf []*_bb .PdfIndirectObject ;};func _bag (_ggd _bb .PdfObject )[]content {if _ggd ==nil {return nil ;
};_cfea ,_egcf :=_bb .GetArray (_ggd );if !_egcf {_e .Log .Debug ("\u0041\u006e\u006e\u006fts\u0020\u006e\u006f\u0074\u0020\u0061\u006e\u0020\u0061\u0072\u0072\u0061\u0079");return nil ;};var _dgf []content ;for _ ,_eag :=range _cfea .Elements (){_caf ,_efc :=_bb .GetDict (_eag );
if !_efc {_e .Log .Debug ("I\u0067\u006e\u006f\u0072\u0069\u006eg\u0020\u006e\u006f\u006e\u002d\u0064i\u0063\u0074\u0020\u0065\u006c\u0065\u006de\u006e\u0074\u0020\u0069\u006e\u0020\u0041\u006e\u006e\u006ft\u0073");continue ;};_age ,_efc :=_bb .GetDict (_caf .Get ("\u0041\u0050"));
if !_efc {_e .Log .Debug ("\u004e\u006f\u0020\u0041P \u0065\u006e\u0074\u0072\u0079\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067");continue ;};_fae :=_bb .TraceToDirectObject (_age .Get ("\u004e"));if _fae ==nil {_e .Log .Debug ("N\u006f\u0020\u004e\u0020en\u0074r\u0079\u0020\u002d\u0020\u0073k\u0069\u0070\u0070\u0069\u006e\u0067");
continue ;};var _egf *_bb .PdfObjectStream ;switch _ffff :=_fae .(type ){case *_bb .PdfObjectDictionary :_ddd ,_dgc :=_bb .GetName (_caf .Get ("\u0041\u0053"));if !_dgc {_e .Log .Debug ("\u004e\u006f\u0020\u0041S \u0065\u006e\u0074\u0072\u0079\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067");
continue ;};_egf ,_dgc =_bb .GetStream (_ffff .Get (*_ddd ));if !_dgc {_e .Log .Debug ("\u0046o\u0072\u006d\u0020\u006eo\u0074\u0020\u0066\u006f\u0075n\u0064 \u002d \u0073\u006b\u0069\u0070\u0070\u0069\u006eg");continue ;};case *_bb .PdfObjectStream :_egf =_ffff ;
};if _egf ==nil {_e .Log .Debug ("\u0046\u006f\u0072m\u0020\u006e\u006f\u0074 \u0066\u006f\u0075\u006e\u0064\u0020\u0028n\u0069\u006c\u0029\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069\u006e\u0067");continue ;};_agb ,_dc :=_abe .NewXObjectFormFromStream (_egf );
if _dc !=nil {_e .Log .Debug ("\u0045\u0072\u0072\u006f\u0072\u0020l\u006f\u0061\u0064\u0069\u006e\u0067\u0020\u0066\u006f\u0072\u006d\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_dc );continue ;};_afe ,_dc :=_agb .GetContentStream ();
if _dc !=nil {_e .Log .Debug ("E\u0072\u0072\u006f\u0072\u0020\u0064e\u0063\u006f\u0064\u0069\u006e\u0067\u0020\u0063\u006fn\u0074\u0065\u006et\u0073:\u0020\u0025\u0076",_dc );continue ;};_dgf =append (_dgf ,content {_cfe :string (_afe ),_bede :_agb .Resources });
};return _dgf ;};func _cggc (_ffdb []_bb .PdfObject ,_eeeb map[_bb .PdfObject ]_bb .PdfObject ){if len (_eeeb )==0{return ;};for _gegd ,_bbg :=range _ffdb {if _daad ,_fafg :=_eeeb [_bbg ];_fafg {_ffdb [_gegd ]=_daad ;continue ;};_eeeb [_bbg ]=_bbg ;switch _dabf :=_bbg .(type ){case *_bb .PdfObjectArray :_babg :=make ([]_bb .PdfObject ,_dabf .Len ());
copy (_babg ,_dabf .Elements ());_cggc (_babg ,_eeeb );for _dfag ,_gcaa :=range _babg {_dabf .Set (_dfag ,_gcaa );};case *_bb .PdfObjectStreams :_cggc (_dabf .Elements (),_eeeb );case *_bb .PdfObjectStream :_ccca :=[]_bb .PdfObject {_dabf .PdfObjectDictionary };
_cggc (_ccca ,_eeeb );_dabf .PdfObjectDictionary =_ccca [0].(*_bb .PdfObjectDictionary );case *_bb .PdfObjectDictionary :_abcf :=_dabf .Keys ();_gfd :=make ([]_bb .PdfObject ,len (_abcf ));for _bdbb ,_cbfc :=range _abcf {_gfd [_bdbb ]=_dabf .Get (_cbfc );
};_cggc (_gfd ,_eeeb );for _gaae ,_aagg :=range _abcf {_dabf .Set (_aagg ,_gfd [_gaae ]);};case *_bb .PdfIndirectObject :_bec :=[]_bb .PdfObject {_dabf .PdfObject };_cggc (_bec ,_eeeb );_dabf .PdfObject =_bec [0];};};};func _ae (_bcf *_ba .ContentStreamOperations )*_ba .ContentStreamOperations {if _bcf ==nil {return nil ;
};_ebb :=_ba .ContentStreamOperations {};for _ ,_df :=range *_bcf {switch _df .Operand {case "\u0042\u0044\u0043","\u0042\u004d\u0043","\u0045\u004d\u0043":continue ;case "\u0054\u006d":if len (_df .Params )==6{if _baa ,_fc :=_bb .GetNumbersAsFloat (_df .Params );
_fc ==nil {if _baa [0]==1&&_baa [1]==0&&_baa [2]==0&&_baa [3]==1{_df =&_ba .ContentStreamOperation {Params :[]_bb .PdfObject {_df .Params [4],_df .Params [5]},Operand :"\u0054\u0064"};};};};};_ebb =append (_ebb ,_df );};return &_ebb ;};

// CleanContentstream cleans up redundant operands in content streams, including Page and XObject Form
// contents. This process includes:
// 1. Marked content operators are removed.
// 2. Some operands are simplified (shorter form).
// TODO: Add more reduction methods and improving the methods for identifying unnecessary operands.
type CleanContentstream struct{};type imageInfo struct{BitsPerComponent int ;ColorComponents int ;Width int ;Height int ;Stream *_bb .PdfObjectStream ;PPI float64 ;};

// Image optimizes images by rewrite images into JPEG format with quality equals to ImageQuality.
// TODO(a5i): Add support for inline images.
// It implements interface model.Optimizer.
type Image struct{ImageQuality int ;};

// CleanUnusedResources represents an optimizer used to clean unused resources.
type CleanUnusedResources struct{};func _dgff (_cgdd _bb .PdfObject ,_agea map[_bb .PdfObject ]struct{})error {if _deg ,_eca :=_cgdd .(*_bb .PdfIndirectObject );_eca {_agea [_cgdd ]=struct{}{};_cda :=_dgff (_deg .PdfObject ,_agea );if _cda !=nil {return _cda ;
};return nil ;};if _abg ,_aecg :=_cgdd .(*_bb .PdfObjectStream );_aecg {_agea [_abg ]=struct{}{};_cbd :=_dgff (_abg .PdfObjectDictionary ,_agea );if _cbd !=nil {return _cbd ;};return nil ;};if _gaab ,_bbbf :=_cgdd .(*_bb .PdfObjectDictionary );_bbbf {for _ ,_fbd :=range _gaab .Keys (){_cbg :=_gaab .Get (_fbd );
_ =_cbg ;if _agc ,_cagg :=_cbg .(*_bb .PdfObjectReference );_cagg {_cbg =_agc .Resolve ();_gaab .Set (_fbd ,_cbg );};if _fbd !="\u0050\u0061\u0072\u0065\u006e\u0074"{if _cff :=_dgff (_cbg ,_agea );_cff !=nil {return _cff ;};};};return nil ;};if _ada ,_dcc :=_cgdd .(*_bb .PdfObjectArray );
_dcc {if _ada ==nil {return _ea .New ("\u0061\u0072\u0072a\u0079\u0020\u0069\u0073\u0020\u006e\u0069\u006c");};for _bgd ,_gcbb :=range _ada .Elements (){if _fadb ,_aggg :=_gcbb .(*_bb .PdfObjectReference );_aggg {_gcbb =_fadb .Resolve ();_ada .Set (_bgd ,_gcbb );
};if _gabf :=_dgff (_gcbb ,_agea );_gabf !=nil {return _gabf ;};};return nil ;};return nil ;};

// CombineIdenticalIndirectObjects combines identical indirect objects.
// It implements interface model.Optimizer.
type CombineIdenticalIndirectObjects struct{};

// CompressStreams compresses uncompressed streams.
// It implements interface model.Optimizer.
type CompressStreams struct{};func _cfd (_eagb []_bb .PdfObject )(map[_bb .PdfObject ]struct{},error ){_abd :=_aedd (_eagb );_cgg :=_abd ._dfcf ;_egdef :=make (map[_bb .PdfObject ]struct{});_ggf :=_cbec (_cgg );for _ ,_cde :=range _cgg {_bda ,_bef :=_bb .GetDict (_cde .PdfObject );
if !_bef {continue ;};_gaaa ,_bef :=_bb .GetDict (_bda .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));if !_bef {continue ;};_efg :=_ggf ["\u0058O\u0062\u006a\u0065\u0063\u0074"];_abba ,_bef :=_bb .GetDict (_gaaa .Get ("\u0058O\u0062\u006a\u0065\u0063\u0074"));
if _bef {_edfg :=_efag (_abba );for _ ,_ddge :=range _edfg {if _bfg (_ddge ,_efg ){continue ;};_ggg :=*_bb .MakeName (_ddge );_ege :=_abba .Get (_ggg );_egdef [_ege ]=struct{}{};_abba .Remove (_ggg );_fcaf :=_dgff (_ege ,_egdef );if _fcaf !=nil {_e .Log .Debug ("\u0066\u0061\u0069\u006ce\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065r\u0073e\u0020\u006f\u0062\u006a\u0065\u0063\u0074 \u0025\u0076",_ege );
};};};_gggd ,_bef :=_bb .GetDict (_gaaa .Get ("\u0046\u006f\u006e\u0074"));_gbf :=_ggf ["\u0046\u006f\u006e\u0074"];if _bef {_dee :=_efag (_gggd );for _ ,_cbe :=range _dee {if _bfg (_cbe ,_gbf ){continue ;};_ebab :=*_bb .MakeName (_cbe );_eab :=_gggd .Get (_ebab );
_egdef [_eab ]=struct{}{};_gggd .Remove (_ebab );_bbag :=_dgff (_eab ,_egdef );if _bbag !=nil {_e .Log .Debug ("\u0046\u0061i\u006c\u0065\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065\u0072\u0073\u0065\u0020\u006f\u0062\u006a\u0065\u0063\u0074 %\u0076\u000a",_eab );
};};};_agg ,_bef :=_bb .GetDict (_gaaa .Get ("\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"));if _bef {_bac :=_efag (_agg );_dad :=_ggf ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"];for _ ,_cabc :=range _bac {if _bfg (_cabc ,_dad ){continue ;};_bff :=*_bb .MakeName (_cabc );
_dfca :=_agg .Get (_bff );_egdef [_dfca ]=struct{}{};_agg .Remove (_bff );_eagba :=_dgff (_dfca ,_egdef );if _eagba !=nil {_e .Log .Debug ("\u0066\u0061i\u006c\u0065\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065\u0072\u0073\u0065\u0020\u006f\u0062\u006a\u0065\u0063\u0074 %\u0076\u000a",_dfca );
};};};};return _egdef ,nil ;};func _cdeb (_eebd []_bb .PdfObject )[]*imageInfo {_eee :=_bb .PdfObjectName ("\u0053u\u0062\u0074\u0079\u0070\u0065");_eafg :=make (map[*_bb .PdfObjectStream ]struct{});var _fecb []*imageInfo ;for _ ,_cfgd :=range _eebd {_adcf ,_gegg :=_bb .GetStream (_cfgd );
if !_gegg {continue ;};if _ ,_agggd :=_eafg [_adcf ];_agggd {continue ;};_eafg [_adcf ]=struct{}{};_def :=_adcf .PdfObjectDictionary .Get (_eee );_fag ,_gegg :=_bb .GetName (_def );if !_gegg ||string (*_fag )!="\u0049\u006d\u0061g\u0065"{continue ;};_aagf :=&imageInfo {Stream :_adcf ,BitsPerComponent :8};
if _bagg ,_bae :=_bb .GetIntVal (_adcf .Get ("\u0042\u0069t\u0073\u0050\u0065r\u0043\u006f\u006d\u0070\u006f\u006e\u0065\u006e\u0074"));_bae {_aagf .BitsPerComponent =_bagg ;};if _gbd ,_bcag :=_bb .GetIntVal (_adcf .Get ("\u0057\u0069\u0064t\u0068"));_bcag {_aagf .Width =_gbd ;
};if _gef ,_bagdd :=_bb .GetIntVal (_adcf .Get ("\u0048\u0065\u0069\u0067\u0068\u0074"));_bagdd {_aagf .Height =_gef ;};_bdad ,_cafge :=_abe .NewPdfColorspaceFromPdfObject (_adcf .Get ("\u0043\u006f\u006c\u006f\u0072\u0053\u0070\u0061\u0063\u0065"));if _cafge !=nil {_e .Log .Debug ("\u0045R\u0052\u004f\u0052\u003a\u0020\u0025v",_cafge );
continue ;};if _bdad ==nil {_cfae ,_gbcc :=_bb .GetName (_adcf .Get ("\u0046\u0069\u006c\u0074\u0065\u0072"));if _gbcc {switch _cfae .String (){case "\u0043\u0043\u0049\u0054\u0054\u0046\u0061\u0078\u0044e\u0063\u006f\u0064\u0065","J\u0042\u0049\u0047\u0032\u0044\u0065\u0063\u006f\u0064\u0065":_bdad =_abe .NewPdfColorspaceDeviceGray ();
_aagf .BitsPerComponent =1;};};};switch _caee :=_bdad .(type ){case *_abe .PdfColorspaceDeviceRGB :_aagf .ColorComponents =3;case *_abe .PdfColorspaceDeviceGray :_aagf .ColorComponents =1;default:_e .Log .Debug ("\u004f\u0070\u0074\u0069\u006d\u0069\u007aa\u0074\u0069\u006fn\u0020\u0069\u0073 \u006e\u006ft\u0020\u0073\u0075\u0070\u0070\u006fr\u0074ed\u0020\u0066\u006f\u0072\u0020\u0063\u006f\u006c\u006f\u0072\u0020\u0073\u0070\u0061\u0063\u0065\u0020\u0025\u0054\u0020\u002d\u0020\u0073\u006b\u0069\u0070",_caee );
continue ;};_fecb =append (_fecb ,_aagf );};return _fecb ;};func _cbec (_ge []*_bb .PdfIndirectObject )map[string ][]string {_ddf :=map[string ][]string {};for _ ,_efb :=range _ge {_gde ,_dbe :=_bb .GetDict (_efb .PdfObject );if !_dbe {continue ;};_ecf :=_gde .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073");
_bcg :=_bb .TraceToDirectObject (_ecf );_cga :="";if _ecc ,_gcc :=_bcg .(*_bb .PdfObjectArray );_gcc {var _cfdg []string ;for _ ,_eagg :=range _ecc .Elements (){_bdb ,_cgd :=_dccg (_eagg );if _cgd !=nil {continue ;};_cfdg =append (_cfdg ,_bdb );};_cga =_fd .Join (_cfdg ,"\u0020");
};if _eda ,_bgf :=_bcg .(*_bb .PdfObjectStream );_bgf {_dag ,_ecb :=_bb .DecodeStream (_eda );if _ecb !=nil {continue ;};_cga =string (_dag );};_edac :=_ba .NewContentStreamParser (_cga );_dff ,_dae :=_edac .Parse ();if _dae !=nil {continue ;};for _ ,_gce :=range *_dff {_afaf :=_gce .Operand ;
_dbea :=_gce .Params ;switch _afaf {case "\u0044\u006f":_dgfc :=_dbea [0].String ();if _ ,_fbfc :=_ddf ["\u0058O\u0062\u006a\u0065\u0063\u0074"];!_fbfc {_ddf ["\u0058O\u0062\u006a\u0065\u0063\u0074"]=[]string {_dgfc };}else {_ddf ["\u0058O\u0062\u006a\u0065\u0063\u0074"]=append (_ddf ["\u0058O\u0062\u006a\u0065\u0063\u0074"],_dgfc );
};case "\u0054\u0066":_aae :=_dbea [0].String ();if _ ,_cgb :=_ddf ["\u0046\u006f\u006e\u0074"];!_cgb {_ddf ["\u0046\u006f\u006e\u0074"]=[]string {_aae };}else {_ddf ["\u0046\u006f\u006e\u0074"]=append (_ddf ["\u0046\u006f\u006e\u0074"],_aae );};case "\u0067\u0073":_cgde :=_dbea [0].String ();
if _ ,_bgb :=_ddf ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"];!_bgb {_ddf ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"]=[]string {_cgde };}else {_ddf ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"]=append (_ddf ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"],_cgde );
};};};};return _ddf ;};func _bdf (_dca *_abe .Image ,_ccbd float64 )(*_abe .Image ,error ){_abecb ,_aage :=_dca .ToGoImage ();if _aage !=nil {return nil ,_aage ;};var _edeb _gf .Image ;_dgb ,_defc :=_abecb .(*_gf .Monochrome );if _defc {if _aage =_dgb .ResolveDecode ();
_aage !=nil {return nil ,_aage ;};_edeb ,_aage =_dgb .Scale (_ccbd );if _aage !=nil {return nil ,_aage ;};}else {_aeg :=int (_b .RoundToEven (float64 (_dca .Width )*_ccbd ));_aga :=int (_b .RoundToEven (float64 (_dca .Height )*_ccbd ));_edeb ,_aage =_gf .NewImage (_aeg ,_aga ,int (_dca .BitsPerComponent ),_dca .ColorComponents ,nil ,nil ,nil );
if _aage !=nil {return nil ,_aage ;};_g .CatmullRom .Scale (_edeb ,_edeb .Bounds (),_abecb ,_abecb .Bounds (),_g .Over ,&_g .Options {});};_bbac :=_edeb .Base ();_cfca :=&_abe .Image {Width :int64 (_bbac .Width ),Height :int64 (_bbac .Height ),BitsPerComponent :int64 (_bbac .BitsPerComponent ),ColorComponents :_bbac .ColorComponents ,Data :_bbac .Data };
_cfca .SetDecode (_bbac .Decode );_cfca .SetAlpha (_bbac .Alpha );return _cfca ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_ggfc *CompressStreams )Optimize (objects []_bb .PdfObject )(_cfg []_bb .PdfObject ,_aaee error ){_cfg =make ([]_bb .PdfObject ,len (objects ));copy (_cfg ,objects );for _ ,_caa :=range objects {_bedf ,_ccaf :=_bb .GetStream (_caa );if !_ccaf {continue ;
};if _fdg :=_bedf .Get ("\u0046\u0069\u006c\u0074\u0065\u0072");_fdg !=nil {if _ ,_cgge :=_bb .GetName (_fdg );_cgge {continue ;};if _bfd ,_gdd :=_bb .GetArray (_fdg );_gdd &&_bfd .Len ()> 0{continue ;};};_fbdg :=_bb .NewFlateEncoder ();var _gggf []byte ;
_gggf ,_aaee =_fbdg .EncodeBytes (_bedf .Stream );if _aaee !=nil {return _cfg ,_aaee ;};_gdcg :=_fbdg .MakeStreamDict ();if len (_gggf )+len (_gdcg .Write ())< len (_bedf .Stream ){_bedf .Stream =_gggf ;_bedf .PdfObjectDictionary .Merge (_gdcg );_bedf .PdfObjectDictionary .Set ("\u004c\u0065\u006e\u0067\u0074\u0068",_bb .MakeInteger (int64 (len (_bedf .Stream ))));
};};return _cfg ,nil ;};func _bfg (_bffg string ,_fce []string )bool {for _ ,_cbdff :=range _fce {if _bffg ==_cbdff {return true ;};};return false ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_cc *Chain )Optimize (objects []_bb .PdfObject )(_ed []_bb .PdfObject ,_gfg error ){_ca :=objects ;for _ ,_ff :=range _cc ._bd {_cd ,_eb :=_ff .Optimize (_ca );if _eb !=nil {_e .Log .Debug ("\u0045\u0052\u0052OR\u0020\u004f\u0070\u0074\u0069\u006d\u0069\u007a\u0061\u0074\u0069\u006f\u006e\u003a\u0020\u0025\u002b\u0076",_eb );
continue ;};_ca =_cd ;};return _ca ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_gfa *CombineDuplicateStreams )Optimize (objects []_bb .PdfObject )(_fbc []_bb .PdfObject ,_ddb error ){_bffc :=make (map[_bb .PdfObject ]_bb .PdfObject );_eaf :=make (map[_bb .PdfObject ]struct{});_ffde :=make (map[string ][]*_bb .PdfObjectStream );
for _ ,_agd :=range objects {_bbab ,_gee :=_agd .(*_bb .PdfObjectStream );if !_gee {continue ;};if _bbab .Lazy {continue ;};_cgee :=_d .New ();_cgee .Write (_bbab .Stream );_cgee .Write (_bbab .PdfObjectDictionary .Write ());_edae :=string (_cgee .Sum (nil ));
_ffde [_edae ]=append (_ffde [_edae ],_bbab );};for _ ,_ccae :=range _ffde {if len (_ccae )< 2{continue ;};_agfa :=_ccae [0];for _gadef :=1;_gadef < len (_ccae );_gadef ++{_ffea :=_ccae [_gadef ];_bffc [_ffea ]=_agfa ;_eaf [_ffea ]=struct{}{};};};_fbc =make ([]_bb .PdfObject ,0,len (objects )-len (_eaf ));
for _ ,_geg :=range objects {if _ ,_ggdd :=_eaf [_geg ];_ggdd {continue ;};_fbc =append (_fbc ,_geg );};_cggc (_fbc ,_bffc );return _fbc ,nil ;};func _gddg (_bfc []_bb .PdfObject ){for _bgbd ,_edeg :=range _bfc {switch _eae :=_edeg .(type ){case *_bb .PdfIndirectObject :_eae .ObjectNumber =int64 (_bgbd +1);
_eae .GenerationNumber =0;case *_bb .PdfObjectStream :_eae .ObjectNumber =int64 (_bgbd +1);_eae .GenerationNumber =0;case *_bb .PdfObjectStreams :_eae .ObjectNumber =int64 (_bgbd +1);_eae .GenerationNumber =0;};};};

// ObjectStreams groups PDF objects to object streams.
// It implements interface model.Optimizer.
type ObjectStreams struct{};

// Optimize optimizes PDF objects to decrease PDF size.
func (_dcd *CombineDuplicateDirectObjects )Optimize (objects []_bb .PdfObject )(_agf []_bb .PdfObject ,_adb error ){_gddg (objects );_ffdd :=make (map[string ][]*_bb .PdfObjectDictionary );var _dafe func (_fgca *_bb .PdfObjectDictionary );_dafe =func (_dda *_bb .PdfObjectDictionary ){for _ ,_efbc :=range _dda .Keys (){_egdg :=_dda .Get (_efbc );
if _cdac ,_dga :=_egdg .(*_bb .PdfObjectDictionary );_dga {if _add :=_cdac .Keys ();len (_add )==0{continue ;};_abec :=_ga .New ();_abec .Write (_cdac .Write ());_bcd :=string (_abec .Sum (nil ));_ffdd [_bcd ]=append (_ffdd [_bcd ],_cdac );_dafe (_cdac );
};};};for _ ,_bagd :=range objects {_abgd ,_gae :=_bagd .(*_bb .PdfIndirectObject );if !_gae {continue ;};if _cbf ,_bfe :=_abgd .PdfObject .(*_bb .PdfObjectDictionary );_bfe {_dafe (_cbf );};};_degb :=make ([]_bb .PdfObject ,0,len (_ffdd ));_cca :=make (map[_bb .PdfObject ]_bb .PdfObject );
for _ ,_aebe :=range _ffdd {if len (_aebe )< 2{continue ;};_cfc :=_bb .MakeDict ();_cfc .Merge (_aebe [0]);_cba :=_bb .MakeIndirectObject (_cfc );_degb =append (_degb ,_cba );for _ffc :=0;_ffc < len (_aebe );_ffc ++{_bee :=_aebe [_ffc ];_cca [_bee ]=_cba ;
};};_agf =make ([]_bb .PdfObject ,len (objects ));copy (_agf ,objects );_agf =append (_degb ,_agf ...);_cggc (_agf ,_cca );return _agf ,nil ;};

// Options describes PDF optimization parameters.
type Options struct{CombineDuplicateStreams bool ;CombineDuplicateDirectObjects bool ;ImageUpperPPI float64 ;ImageQuality int ;UseObjectStreams bool ;CombineIdenticalIndirectObjects bool ;CompressStreams bool ;CleanFonts bool ;SubsetFonts bool ;CleanContentstream bool ;
CleanUnusedResources bool ;};

// Optimize implements Optimizer interface.
func (_cefd *CleanUnusedResources )Optimize (objects []_bb .PdfObject )(_eecc []_bb .PdfObject ,_aec error ){_bca ,_aec :=_cfd (objects );if _aec !=nil {return nil ,_aec ;};_bba :=[]_bb .PdfObject {};for _ ,_ec :=range objects {_ ,_fcde :=_bca [_ec ];if _fcde {continue ;
};_bba =append (_bba ,_ec );};return _bba ,nil ;};func _aedd (_ccde []_bb .PdfObject )objectStructure {_eaa :=objectStructure {};_eccc :=false ;for _ ,_ece :=range _ccde {switch _bbde :=_ece .(type ){case *_bb .PdfIndirectObject :_gbcd ,_aagc :=_bb .GetDict (_bbde );
if !_aagc {continue ;};_cfag ,_aagc :=_bb .GetName (_gbcd .Get ("\u0054\u0079\u0070\u0065"));if !_aagc {continue ;};switch _cfag .String (){case "\u0043a\u0074\u0061\u006c\u006f\u0067":_eaa ._bfec =_gbcd ;_eccc =true ;};};if _eccc {break ;};};if !_eccc {return _eaa ;
};_babea ,_fgfb :=_bb .GetDict (_eaa ._bfec .Get ("\u0050\u0061\u0067e\u0073"));if !_fgfb {return _eaa ;};_eaa ._gac =_babea ;_badf ,_fgfb :=_bb .GetArray (_babea .Get ("\u004b\u0069\u0064\u0073"));if !_fgfb {return _eaa ;};for _ ,_fba :=range _badf .Elements (){_baf ,_bgc :=_bb .GetIndirect (_fba );
if !_bgc {break ;};_eaa ._dfcf =append (_eaa ._dfcf ,_baf );};return _eaa ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_abfe *Image )Optimize (objects []_bb .PdfObject )(_cdacb []_bb .PdfObject ,_ffdf error ){if _abfe .ImageQuality <=0{return objects ,nil ;};_cbac :=_cdeb (objects );if len (_cbac )==0{return objects ,nil ;};_adcb :=make (map[_bb .PdfObject ]_bb .PdfObject );
_eagbc :=make (map[_bb .PdfObject ]struct{});for _ ,_ddfc :=range _cbac {_dadf :=_ddfc .Stream .Get ("\u0053\u004d\u0061s\u006b");_eagbc [_dadf ]=struct{}{};};for _eacd ,_fbdb :=range _cbac {_ggea :=_fbdb .Stream ;if _ ,_deb :=_eagbc [_ggea ];_deb {continue ;
};_gbca ,_ggee :=_abe .NewXObjectImageFromStream (_ggea );if _ggee !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_ggee );continue ;};switch _gbca .Filter .(type ){case *_bb .JBIG2Encoder :continue ;case *_bb .CCITTFaxEncoder :continue ;
};_eea ,_ggee :=_gbca .ToImage ();if _ggee !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_ggee );continue ;};_bcac :=_bb .NewDCTEncoder ();_bcac .ColorComponents =_eea .ColorComponents ;_bcac .Quality =_abfe .ImageQuality ;
_bcac .BitsPerComponent =_fbdb .BitsPerComponent ;_bcac .Width =_fbdb .Width ;_bcac .Height =_fbdb .Height ;_fbec ,_ggee :=_bcac .EncodeBytes (_eea .Data );if _ggee !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_ggee );
continue ;};var _dcb _bb .StreamEncoder ;_dcb =_bcac ;{_ede :=_bb .NewFlateEncoder ();_efe :=_bb .NewMultiEncoder ();_efe .AddEncoder (_ede );_efe .AddEncoder (_bcac );_ffgb ,_bfdb :=_efe .EncodeBytes (_eea .Data );if _bfdb !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_bfdb );
continue ;};if len (_ffgb )< len (_fbec ){if _e .Log .IsLogLevel (_e .LogLevelTrace ){_e .Log .Trace ("\u004d\u0075\u006c\u0074\u0069\u0020\u0065\u006e\u0063\u0020\u0069\u006d\u0070\u0072\u006f\u0076\u0065\u0073\u003a\u0020\u0025\u0064\u0020\u0074o\u0020\u0025\u0064\u0020\u0028o\u0072\u0069g\u0020\u0025\u0064\u0029",len (_fbec ),len (_ffgb ),len (_ggea .Stream ));
};_fbec =_ffgb ;_dcb =_efe ;};};_ade :=len (_ggea .Stream );if _ade < len (_fbec ){continue ;};_bga :=&_bb .PdfObjectStream {Stream :_fbec };_bga .PdfObjectReference =_ggea .PdfObjectReference ;_bga .PdfObjectDictionary =_bb .MakeDict ();_bga .Merge (_ggea .PdfObjectDictionary );
_bga .Merge (_dcb .MakeStreamDict ());_bga .Set ("\u004c\u0065\u006e\u0067\u0074\u0068",_bb .MakeInteger (int64 (len (_fbec ))));_adcb [_ggea ]=_bga ;_cbac [_eacd ].Stream =_bga ;};_cdacb =make ([]_bb .PdfObject ,len (objects ));copy (_cdacb ,objects );
_cggc (_cdacb ,_adcb );return _cdacb ,nil ;};func _efcc (_dded *_abe .XObjectImage ,_edbf imageModifications )error {_agfe ,_gba :=_dded .ToImage ();if _gba !=nil {return _gba ;};if _edbf .Scale !=0{_agfe ,_gba =_bdf (_agfe ,_edbf .Scale );if _gba !=nil {return _gba ;
};};if _edbf .Encoding !=nil {_dded .Filter =_edbf .Encoding ;};_dded .Decode =nil ;switch _fcc :=_dded .Filter .(type ){case *_bb .FlateEncoder :if _fcc .Predictor !=1&&_fcc .Predictor !=11{_fcc .Predictor =1;};};if _gba =_dded .SetImage (_agfe ,nil );
_gba !=nil {_e .Log .Debug ("\u0045\u0072\u0072or\u0020\u0073\u0065\u0074\u0074\u0069\u006e\u0067\u0020\u0069\u006d\u0061\u0067\u0065\u003a\u0020\u0025\u0076",_gba );return _gba ;};_dded .ToPdfObject ();return nil ;};func _efag (_dddb *_bb .PdfObjectDictionary )[]string {_daa :=[]string {};
for _ ,_gaabb :=range _dddb .Keys (){_daa =append (_daa ,_gaabb .String ());};return _daa ;};func _cacc (_eede _bb .PdfObject )(_adad string ,_gdef []_bb .PdfObject ){var _cacb _da .Buffer ;switch _dfae :=_eede .(type ){case *_bb .PdfIndirectObject :_gdef =append (_gdef ,_dfae );
_eede =_dfae .PdfObject ;};switch _fbdd :=_eede .(type ){case *_bb .PdfObjectStream :if _ecfa ,_abcad :=_bb .DecodeStream (_fbdd );_abcad ==nil {_cacb .Write (_ecfa );_gdef =append (_gdef ,_fbdd );};case *_bb .PdfObjectArray :for _ ,_geb :=range _fbdd .Elements (){switch _badc :=_geb .(type ){case *_bb .PdfObjectStream :if _bdbd ,_daff :=_bb .DecodeStream (_badc );
_daff ==nil {_cacb .Write (_bdbd );_gdef =append (_gdef ,_badc );};};};};return _cacb .String (),_gdef ;};

// CleanFonts cleans up embedded fonts, reducing font sizes.
type CleanFonts struct{

// Subset embedded fonts if encountered (if true).
// Otherwise attempts to reduce the font program.
Subset bool ;};

// CombineDuplicateDirectObjects combines duplicated direct objects by its data hash.
// It implements interface model.Optimizer.
type CombineDuplicateDirectObjects struct{};type content struct{_cfe string ;_bede *_abe .PdfPageResources ;};func _aba (_cf *_bb .PdfObjectStream ,_aca []rune ,_bad []_gaf .GlyphIndex )error {_cf ,_aag :=_bb .GetStream (_cf );if !_aag {_e .Log .Debug ("\u0045\u006d\u0062\u0065\u0064\u0064\u0065\u0064\u0020\u0066\u006f\u006e\u0074\u0020\u006f\u0062\u006a\u0065c\u0074\u0020\u006e\u006f\u0074\u0020\u0066o\u0075\u006e\u0064\u0020\u002d\u002d\u0020\u0041\u0042\u004f\u0052T\u0020\u0073\u0075\u0062\u0073\u0065\u0074\u0074\u0069\u006e\u0067");
return _ea .New ("\u0066\u006f\u006e\u0074fi\u006c\u0065\u0032\u0020\u006e\u006f\u0074\u0020\u0066\u006f\u0075\u006e\u0064");};_dfa ,_ffaa :=_bb .DecodeStream (_cf );if _ffaa !=nil {_e .Log .Debug ("\u0044\u0065c\u006f\u0064\u0065 \u0065\u0072\u0072\u006f\u0072\u003a\u0020\u0025\u0076",_ffaa );
return _ffaa ;};_ebf ,_ffaa :=_gaf .Parse (_da .NewReader (_dfa ));if _ffaa !=nil {_e .Log .Debug ("\u0045\u0072\u0072\u006f\u0072\u0020\u0070\u0061\u0072\u0073\u0069n\u0067\u0020\u0025\u0064\u0020\u0062\u0079\u0074\u0065\u0020f\u006f\u006e\u0074",len (_cf .Stream ));
return _ffaa ;};_afdd :=_bad ;if len (_aca )> 0{_fbfb :=_ebf .LookupRunes (_aca );_afdd =append (_afdd ,_fbfb ...);};_ebf ,_ffaa =_ebf .SubsetKeepIndices (_afdd );if _ffaa !=nil {_e .Log .Debug ("\u0045R\u0052\u004f\u0052\u0020s\u0075\u0062\u0073\u0065\u0074t\u0069n\u0067 \u0066\u006f\u006e\u0074\u003a\u0020\u0025v",_ffaa );
return _ffaa ;};var _egde _da .Buffer ;_ffaa =_ebf .Write (&_egde );if _ffaa !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004fR \u0057\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076",_ffaa );return _ffaa ;};if _egde .Len ()> len (_dfa ){_e .Log .Debug ("\u0052\u0065-\u0077\u0072\u0069\u0074\u0074\u0065\u006e\u0020\u0066\u006f\u006e\u0074\u0020\u0069\u0073\u0020\u006c\u0061\u0072\u0067\u0065\u0072\u0020\u0074\u0068\u0061\u006e\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u002d\u0020\u0073\u006b\u0069\u0070");
return nil ;};_fcab ,_ffaa :=_bb .MakeStream (_egde .Bytes (),_bb .NewFlateEncoder ());if _ffaa !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004fR \u0057\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076",_ffaa );return _ffaa ;
};*_cf =*_fcab ;_cf .Set ("\u004ce\u006e\u0067\u0074\u0068\u0031",_bb .MakeInteger (int64 (_egde .Len ())));return nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_fcae *ObjectStreams )Optimize (objects []_bb .PdfObject )(_ccg []_bb .PdfObject ,_effa error ){_addc :=&_bb .PdfObjectStreams {};_ebcf :=make ([]_bb .PdfObject ,0,len (objects ));for _ ,_gbcg :=range objects {if _dbd ,_bgfb :=_gbcg .(*_bb .PdfIndirectObject );
_bgfb &&_dbd .GenerationNumber ==0{_addc .Append (_gbcg );}else {_ebcf =append (_ebcf ,_gbcg );};};if _addc .Len ()==0{return _ebcf ,nil ;};_ccg =make ([]_bb .PdfObject ,0,len (_ebcf )+_addc .Len ()+1);if _addc .Len ()> 1{_ccg =append (_ccg ,_addc );};
_ccg =append (_ccg ,_addc .Elements ()...);_ccg =append (_ccg ,_ebcf ...);return _ccg ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_gaa *CleanFonts )Optimize (objects []_bb .PdfObject )(_fgf []_bb .PdfObject ,_cfb error ){var _faf map[*_bb .PdfObjectStream ]struct{};if _gaa .Subset {var _edb error ;_faf ,_edb =_fa (objects );if _edb !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004fR\u003a\u0020\u0046\u0061\u0069\u006c\u0065\u0064\u0020\u0073u\u0062s\u0065\u0074\u0074\u0069\u006e\u0067\u003a \u0025\u0076",_edb );
return nil ,_edb ;};};for _ ,_feb :=range objects {_aebb ,_fgg :=_bb .GetStream (_feb );if !_fgg {continue ;};if _ ,_eacc :=_faf [_aebb ];_eacc {continue ;};_edbc ,_ebfd :=_bb .NewEncoderFromStream (_aebb );if _ebfd !=nil {_e .Log .Debug ("\u0045\u0052RO\u0052\u0020\u0067e\u0074\u0074\u0069\u006eg e\u006eco\u0064\u0065\u0072\u003a\u0020\u0025\u0076 -\u0020\u0069\u0067\u006e\u006f\u0072\u0069n\u0067",_ebfd );
continue ;};_ebaa ,_ebfd :=_edbc .DecodeStream (_aebb );if _ebfd !=nil {_e .Log .Debug ("\u0044\u0065\u0063\u006f\u0064\u0069\u006e\u0067\u0020\u0065r\u0072\u006f\u0072\u0020\u003a\u0020\u0025v\u0020\u002d\u0020\u0069\u0067\u006e\u006f\u0072\u0069\u006e\u0067",_ebfd );
continue ;};if len (_ebaa )< 4{continue ;};_ccd :=string (_ebaa [:4]);if _ccd =="\u004f\u0054\u0054\u004f"{continue ;};if _ccd !="\u0000\u0001\u0000\u0000"&&_ccd !="\u0074\u0072\u0075\u0065"{continue ;};_egc ,_ebfd :=_gaf .Parse (_da .NewReader (_ebaa ));
if _ebfd !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020P\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_ebfd );continue ;};_ebfd =_egc .Optimize ();
if _ebfd !=nil {_e .Log .Debug ("\u0045\u0052RO\u0052\u0020\u004fp\u0074\u0069\u006d\u0069zin\u0067 f\u006f\u006e\u0074\u003a\u0020\u0025\u0076 -\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067",_ebfd );continue ;};var _cdd _da .Buffer ;_ebfd =_egc .Write (&_cdd );
if _ebfd !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020W\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_ebfd );continue ;};if _cdd .Len ()> len (_ebaa ){_e .Log .Debug ("\u0052\u0065-\u0077\u0072\u0069\u0074\u0074\u0065\u006e\u0020\u0066\u006f\u006e\u0074\u0020\u0069\u0073\u0020\u006c\u0061\u0072\u0067\u0065\u0072\u0020\u0074\u0068\u0061\u006e\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u002d\u0020\u0073\u006b\u0069\u0070");
continue ;};_dfab ,_ebfd :=_bb .MakeStream (_cdd .Bytes (),_bb .NewFlateEncoder ());if _ebfd !=nil {continue ;};*_aebb =*_dfab ;_aebb .Set ("\u004ce\u006e\u0067\u0074\u0068\u0031",_bb .MakeInteger (int64 (_cdd .Len ())));};return objects ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_bg *CleanContentstream )Optimize (objects []_bb .PdfObject )(_aa []_bb .PdfObject ,_ce error ){_af :=map[*_bb .PdfObjectStream ]struct{}{};var _abc []*_bb .PdfObjectStream ;_bf :=func (_be *_bb .PdfObjectStream ){if _ ,_abb :=_af [_be ];!_abb {_af [_be ]=struct{}{};
_abc =append (_abc ,_be );};};_fcd :=map[_bb .PdfObject ]bool {};_ad :=map[_bb .PdfObject ]bool {};for _ ,_fff :=range objects {switch _gfe :=_fff .(type ){case *_bb .PdfIndirectObject :switch _fe :=_gfe .PdfObject .(type ){case *_bb .PdfObjectDictionary :if _de ,_fb :=_bb .GetName (_fe .Get ("\u0054\u0079\u0070\u0065"));
!_fb ||_de .String ()!="\u0050\u0061\u0067\u0065"{continue ;};if _ffd ,_gd :=_bb .GetStream (_fe .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));_gd {_bf (_ffd );}else if _dbc ,_bge :=_bb .GetArray (_fe .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));
_bge {var _ac []*_bb .PdfObjectStream ;for _ ,_aac :=range _dbc .Elements (){if _abf ,_gcb :=_bb .GetStream (_aac );_gcb {_ac =append (_ac ,_abf );};};if len (_ac )> 0{var _adg _da .Buffer ;for _ ,_aaa :=range _ac {if _ffe ,_abed :=_bb .DecodeStream (_aaa );
_abed ==nil {_adg .Write (_ffe );};_fcd [_aaa ]=true ;};_bbb ,_ee :=_bb .MakeStream (_adg .Bytes (),_bb .NewFlateEncoder ());if _ee !=nil {return nil ,_ee ;};_ad [_bbb ]=true ;_fe .Set ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073",_bbb );_bf (_bbb );
};};};case *_bb .PdfObjectStream :if _gff ,_gfcc :=_bb .GetName (_gfe .Get ("\u0054\u0079\u0070\u0065"));!_gfcc ||_gff .String ()!="\u0058O\u0062\u006a\u0065\u0063\u0074"{continue ;};if _bea ,_aab :=_bb .GetName (_gfe .Get ("\u0053u\u0062\u0074\u0079\u0070\u0065"));
!_aab ||_bea .String ()!="\u0046\u006f\u0072\u006d"{continue ;};_bf (_gfe );};};for _ ,_fec :=range _abc {_ce =_ccb (_fec );if _ce !=nil {return nil ,_ce ;};};_aa =nil ;for _ ,_gad :=range objects {if _fcd [_gad ]{continue ;};_aa =append (_aa ,_gad );};
for _ggc :=range _ad {_aa =append (_aa ,_ggc );};return _aa ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_bdd *CombineIdenticalIndirectObjects )Optimize (objects []_bb .PdfObject )(_gda []_bb .PdfObject ,_aabd error ){_gddg (objects );_fde :=make (map[_bb .PdfObject ]_bb .PdfObject );_efad :=make (map[_bb .PdfObject ]struct{});_gdc :=make (map[string ][]*_bb .PdfIndirectObject );
for _ ,_cbfg :=range objects {_dagd ,_dge :=_cbfg .(*_bb .PdfIndirectObject );if !_dge {continue ;};if _eeg ,_dbb :=_dagd .PdfObject .(*_bb .PdfObjectDictionary );_dbb {if _geeg ,_cdacc :=_eeg .Get ("\u0054\u0079\u0070\u0065").(*_bb .PdfObjectName );_cdacc &&*_geeg =="\u0050\u0061\u0067\u0065"{continue ;
};if _cbaa :=_eeg .Keys ();len (_cbaa )==0{continue ;};_bbd :=_ga .New ();_bbd .Write (_eeg .Write ());_dgca :=string (_bbd .Sum (nil ));_gdc [_dgca ]=append (_gdc [_dgca ],_dagd );};};for _ ,_gagb :=range _gdc {if len (_gagb )< 2{continue ;};_ffg :=_gagb [0];
for _eed :=1;_eed < len (_gagb );_eed ++{_cfa :=_gagb [_eed ];_fde [_cfa ]=_ffg ;_efad [_cfa ]=struct{}{};};};_gda =make ([]_bb .PdfObject ,0,len (objects )-len (_efad ));for _ ,_fbe :=range objects {if _ ,_babe :=_efad [_fbe ];_babe {continue ;};_gda =append (_gda ,_fbe );
};_cggc (_gda ,_fde );return _gda ,nil ;};

// CombineDuplicateStreams combines duplicated streams by its data hash.
// It implements interface model.Optimizer.
type CombineDuplicateStreams struct{};func _ccb (_aeb *_bb .PdfObjectStream )error {_gfc ,_eac :=_bb .DecodeStream (_aeb );if _eac !=nil {return _eac ;};_ef :=_ba .NewContentStreamParser (string (_gfc ));_eg ,_eac :=_ef .Parse ();if _eac !=nil {return _eac ;
};_eg =_ae (_eg );_db :=_eg .Bytes ();if len (_db )>=len (_gfc ){return nil ;};_gab ,_eac :=_bb .MakeStream (_eg .Bytes (),_bb .NewFlateEncoder ());if _eac !=nil {return _eac ;};_aeb .Stream =_gab .Stream ;_aeb .Merge (_gab .PdfObjectDictionary );return nil ;
};

// Optimize optimizes PDF objects to decrease PDF size.
func (_afba *ImagePPI )Optimize (objects []_bb .PdfObject )(_bffb []_bb .PdfObject ,_eff error ){if _afba .ImageUpperPPI <=0{return objects ,nil ;};_fga :=_cdeb (objects );if len (_fga )==0{return objects ,nil ;};_agaf :=make (map[_bb .PdfObject ]struct{});
for _ ,_bbbfd :=range _fga {_eef :=_bbbfd .Stream .PdfObjectDictionary .Get ("\u0053\u004d\u0061s\u006b");_agaf [_eef ]=struct{}{};};_bgee :=make (map[*_bb .PdfObjectStream ]*imageInfo );for _ ,_fggc :=range _fga {_bgee [_fggc .Stream ]=_fggc ;};var _fefc *_bb .PdfObjectDictionary ;
for _ ,_cccg :=range objects {if _ggca ,_ddc :=_bb .GetDict (_cccg );_fefc ==nil &&_ddc {if _fadf ,_bfdd :=_bb .GetName (_ggca .Get ("\u0054\u0079\u0070\u0065"));_bfdd &&*_fadf =="\u0043a\u0074\u0061\u006c\u006f\u0067"{_fefc =_ggca ;};};};if _fefc ==nil {return objects ,nil ;
};_bgac ,_dddd :=_bb .GetDict (_fefc .Get ("\u0050\u0061\u0067e\u0073"));if !_dddd {return objects ,nil ;};_dab ,_fcdf :=_bb .GetArray (_bgac .Get ("\u004b\u0069\u0064\u0073"));if !_fcdf {return objects ,nil ;};for _ ,_bcdd :=range _dab .Elements (){_efd :=make (map[string ]*imageInfo );
_gdae ,_dged :=_bb .GetDict (_bcdd );if !_dged {continue ;};_gbde ,_ :=_cacc (_gdae .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));if len (_gbde )==0{continue ;};_afac ,_edebc :=_bb .GetDict (_gdae .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));
if !_edebc {continue ;};_fegd ,_cebb :=_abe .NewPdfPageResourcesFromDict (_afac );if _cebb !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0072\u0065\u0073\u006f\u0075\u0072\u0063\u0065\u0073\u0020-\u0020\u0069\u0067\u006e\u006fr\u0069\u006eg\u003a\u0020\u0025\u0076",_cebb );
continue ;};_bfdc ,_deeb :=_bb .GetDict (_afac .Get ("\u0058O\u0062\u006a\u0065\u0063\u0074"));if !_deeb {continue ;};_cbb :=_bfdc .Keys ();for _ ,_edef :=range _cbb {if _edd ,_aaae :=_bb .GetStream (_bfdc .Get (_edef ));_aaae {if _cad ,_bcfd :=_bgee [_edd ];
_bcfd {_efd [string (_edef )]=_cad ;};};};_gfgf :=_ba .NewContentStreamParser (_gbde );_cbba ,_cebb :=_gfgf .Parse ();if _cebb !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_cebb );continue ;};_acgg :=_ba .NewContentStreamProcessor (*_cbba );
_acgg .AddHandler (_ba .HandlerConditionEnumAllOperands ,"",func (_cbca *_ba .ContentStreamOperation ,_gdf _ba .GraphicsState ,_cgda *_abe .PdfPageResources )error {switch _cbca .Operand {case "\u0044\u006f":if len (_cbca .Params )!=1{_e .Log .Debug ("E\u0052\u0052\u004f\u0052\u003a\u0020\u0049\u0067\u006e\u006f\u0072\u0069\u006e\u0067\u0020\u0044\u006f\u0020w\u0069\u0074\u0068\u0020\u006c\u0065\u006e\u0028\u0070\u0061ra\u006d\u0073\u0029 \u0021=\u0020\u0031");
return nil ;};_fbeb ,_bdg :=_bb .GetName (_cbca .Params [0]);if !_bdg {_e .Log .Debug ("\u0045\u0052\u0052O\u0052\u003a\u0020\u0049\u0067\u006e\u006f\u0072\u0069\u006e\u0067\u0020\u0044\u006f\u0020\u0077\u0069\u0074\u0068\u0020\u006e\u006f\u006e\u0020\u004e\u0061\u006d\u0065\u0020p\u0061\u0072\u0061\u006d\u0065\u0074\u0065\u0072");
return nil ;};if _ddbg ,_bbbg :=_efd [string (*_fbeb )];_bbbg {_baaea :=_gdf .CTM .ScalingFactorX ();_dea :=_gdf .CTM .ScalingFactorY ();_fdgf ,_gegb :=_baaea /72.0,_dea /72.0;_gcf ,_gca :=float64 (_ddbg .Width )/_fdgf ,float64 (_ddbg .Height )/_gegb ;
if _fdgf ==0||_gegb ==0{_gcf =72.0;_gca =72.0;};_ddbg .PPI =_b .Max (_ddbg .PPI ,_gcf );_ddbg .PPI =_b .Max (_ddbg .PPI ,_gca );};};return nil ;});_cebb =_acgg .Process (_fegd );if _cebb !=nil {_e .Log .Debug ("E\u0052\u0052\u004f\u0052 p\u0072o\u0063\u0065\u0073\u0073\u0069n\u0067\u003a\u0020\u0025\u002b\u0076",_cebb );
continue ;};};for _ ,_agdg :=range _fga {if _ ,_gfac :=_agaf [_agdg .Stream ];_gfac {continue ;};if _agdg .PPI <=_afba .ImageUpperPPI {continue ;};_ecbb ,_aaba :=_abe .NewXObjectImageFromStream (_agdg .Stream );if _aaba !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_aaba );
continue ;};var _daef imageModifications ;_daef .Scale =_afba .ImageUpperPPI /_agdg .PPI ;if _agdg .BitsPerComponent ==1&&_agdg .ColorComponents ==1{_deac :=_b .Round (_agdg .PPI /_afba .ImageUpperPPI );_gdg :=_gf .NextPowerOf2 (uint (_deac ));if _gf .InDelta (float64 (_gdg ),1/_daef .Scale ,0.3){_daef .Scale =float64 (1)/float64 (_gdg );
};if _ ,_fagc :=_ecbb .Filter .(*_bb .JBIG2Encoder );!_fagc {_daef .Encoding =_bb .NewJBIG2Encoder ();};};if _aaba =_efcc (_ecbb ,_daef );_aaba !=nil {_e .Log .Debug ("\u0045\u0072\u0072\u006f\u0072 \u0073\u0063\u0061\u006c\u0065\u0020\u0069\u006d\u0061\u0067\u0065\u0020\u006be\u0065\u0070\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u0069\u006d\u0061\u0067\u0065\u003a\u0020\u0025\u0073",_aaba );
continue ;};_daef .Encoding =nil ;if _fbfa ,_faff :=_bb .GetStream (_agdg .Stream .PdfObjectDictionary .Get ("\u0053\u004d\u0061s\u006b"));_faff {_cdae ,_acc :=_abe .NewXObjectImageFromStream (_fbfa );if _acc !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_acc );
continue ;};if _acc =_efcc (_cdae ,_daef );_acc !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_acc );continue ;};};};return objects ,nil ;};

// Append appends optimizers to the chain.
func (_c *Chain )Append (optimizers ..._abe .Optimizer ){_c ._bd =append (_c ._bd ,optimizers ...)};

// New creates a optimizers chain from options.
func New (options Options )*Chain {_cdef :=new (Chain );if options .CleanFonts ||options .SubsetFonts {_cdef .Append (&CleanFonts {Subset :options .SubsetFonts });};if options .CleanContentstream {_cdef .Append (new (CleanContentstream ));};if options .ImageUpperPPI > 0{_dbge :=new (ImagePPI );
_dbge .ImageUpperPPI =options .ImageUpperPPI ;_cdef .Append (_dbge );};if options .ImageQuality > 0{_bcgb :=new (Image );_bcgb .ImageQuality =options .ImageQuality ;_cdef .Append (_bcgb );};if options .CombineDuplicateDirectObjects {_cdef .Append (new (CombineDuplicateDirectObjects ));
};if options .CombineDuplicateStreams {_cdef .Append (new (CombineDuplicateStreams ));};if options .CombineIdenticalIndirectObjects {_cdef .Append (new (CombineIdenticalIndirectObjects ));};if options .UseObjectStreams {_cdef .Append (new (ObjectStreams ));
};if options .CompressStreams {_cdef .Append (new (CompressStreams ));};if options .CleanUnusedResources {_cdef .Append (new (CleanUnusedResources ));};return _cdef ;};func _fa (_cea []_bb .PdfObject )(_edf map[*_bb .PdfObjectStream ]struct{},_gabb error ){_edf =map[*_bb .PdfObjectStream ]struct{}{};
_fg :=map[*_abe .PdfFont ]struct{}{};_fbf :=_aedd (_cea );for _ ,_fge :=range _fbf ._dfcf {_edc ,_edg :=_bb .GetDict (_fge .PdfObject );if !_edg {continue ;};_gade ,_edg :=_bb .GetDict (_edc .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));if !_edg {continue ;
};_dbg ,_ :=_cacc (_edc .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));_ceb ,_ebc :=_abe .NewPdfPageResourcesFromDict (_gade );if _ebc !=nil {return nil ,_ebc ;};_fab :=[]content {{_cfe :_dbg ,_bede :_ceb }};_aaf :=_bag (_edc .Get ("\u0041\u006e\u006e\u006f\u0074\u0073"));
if _aaf !=nil {_fab =append (_fab ,_aaf ...);};for _ ,_cab :=range _fab {_cbc ,_fea :=_ab .NewFromContents (_cab ._cfe ,_cab ._bede );if _fea !=nil {return nil ,_fea ;};_fed ,_ ,_ ,_fea :=_cbc .ExtractPageText ();if _fea !=nil {return nil ,_fea ;};for _ ,_eeb :=range _fed .Marks ().Elements (){if _eeb .Font ==nil {continue ;
};if _ ,_gdb :=_fg [_eeb .Font ];!_gdb {_fg [_eeb .Font ]=struct{}{};};};};};_afd :=map[*_bb .PdfObjectStream ][]*_abe .PdfFont {};for _gfcb :=range _fg {_dd :=_gfcb .FontDescriptor ();if _dd ==nil ||_dd .FontFile2 ==nil {continue ;};_ddg ,_ag :=_bb .GetStream (_dd .FontFile2 );
if !_ag {continue ;};_afd [_ddg ]=append (_afd [_ddg ],_gfcb );};for _fef :=range _afd {var _abca []rune ;var _abbg []_gaf .GlyphIndex ;for _ ,_fad :=range _afd [_fef ]{switch _cae :=_fad .Encoder ().(type ){case *_bc .IdentityEncoder :_fda :=_cae .RegisteredRunes ();
_ccc :=make ([]_gaf .GlyphIndex ,len (_fda ));for _eec ,_ffa :=range _fda {_ccc [_eec ]=_gaf .GlyphIndex (_ffa );};_abbg =append (_abbg ,_ccc ...);case *_bc .TrueTypeFontEncoder :_dde :=_cae .RegisteredRunes ();_abca =append (_abca ,_dde ...);case _bc .SimpleEncoder :_bab :=_cae .Charcodes ();
for _ ,_ead :=range _bab {_egd ,_bed :=_cae .CharcodeToRune (_ead );if !_bed {_e .Log .Debug ("\u0043\u0068a\u0072\u0063\u006f\u0064\u0065\u003c\u002d\u003e\u0072\u0075\u006e\u0065\u0020\u006e\u006f\u0074\u0020\u0066\u006f\u0075\u006e\u0064: \u0025\u0064",_ead );
continue ;};_abca =append (_abca ,_egd );};};};_gabb =_aba (_fef ,_abca ,_abbg );if _gabb !=nil {_e .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020\u0073\u0075\u0062\u0073\u0065\u0074\u0074\u0069\u006eg\u0020f\u006f\u006e\u0074\u0020\u0073\u0074\u0072\u0065\u0061\u006d\u003a\u0020\u0025\u0076",_gabb );
return nil ,_gabb ;};_edf [_fef ]=struct{}{};};return _edf ,nil ;};

// ImagePPI optimizes images by scaling images such that the PPI (pixels per inch) is never higher than ImageUpperPPI.
// TODO(a5i): Add support for inline images.
// It implements interface model.Optimizer.
type ImagePPI struct{ImageUpperPPI float64 ;};func _dccg (_cbdf _bb .PdfObject )(string ,error ){_bedd :=_bb .TraceToDirectObject (_cbdf );switch _cafe :=_bedd .(type ){case *_bb .PdfObjectString :return _cafe .Str (),nil ;case *_bb .PdfObjectStream :_gbe ,_bcad :=_bb .DecodeStream (_cafe );
if _bcad !=nil {return "",_bcad ;};return string (_gbe ),nil ;};return "",_a .Errorf ("\u0069\u006e\u0076\u0061\u006ci\u0064\u0020\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u0020\u0073\u0074\u0072e\u0061\u006d\u0020\u006f\u0062\u006a\u0065\u0063\u0074\u0020\u0068\u006f\u006c\u0064\u0065\u0072\u0020\u0028\u0025\u0054\u0029",_bedd );
};