//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

// Package fjson provides support for loading PDF form field data from JSON data/files.
package fjson ;import (_f "encoding/json";_fd "github.com/unidoc/unipdf/v4/common";_c "github.com/unidoc/unipdf/v4/core";_df "github.com/unidoc/unipdf/v4/model";_d "io";_ga "os";);

// LoadFromPDFFile loads form field data from a PDF file.
func LoadFromPDFFile (filePath string )(*FieldData ,error ){_gb ,_daf :=_ga .Open (filePath );if _daf !=nil {return nil ,_daf ;};defer _gb .Close ();return LoadFromPDF (_gb );};type fieldValue struct{Name string `json:"name"`;Value string `json:"value"`;
ImageValue *_df .Image `json:"-"`;

// Options lists allowed values if present.
Options []string `json:"options,omitempty"`;};

// FieldData represents form field data loaded from JSON file.
type FieldData struct{_gg []fieldValue };

// LoadFromJSONFile loads form field data from a JSON file.
func LoadFromJSONFile (filePath string )(*FieldData ,error ){_ac ,_e :=_ga .Open (filePath );if _e !=nil {return nil ,_e ;};defer _ac .Close ();return LoadFromJSON (_ac );};

// SetImage assign model.Image to a specific field identified by fieldName.
func (_gfe *FieldData )SetImage (fieldName string ,img *_df .Image ,opt []string )error {_bega :=fieldValue {Name :fieldName ,ImageValue :img ,Options :opt };_gfe ._gg =append (_gfe ._gg ,_bega );return nil ;};

// LoadFromJSON loads JSON form data from `r`.
func LoadFromJSON (r _d .Reader )(*FieldData ,error ){var _a FieldData ;_b :=_f .NewDecoder (r ).Decode (&_a ._gg );if _b !=nil {return nil ,_b ;};return &_a ,nil ;};

// FieldImageValues implements model.FieldImageProvider interface.
func (_feb *FieldData )FieldImageValues ()(map[string ]*_df .Image ,error ){_gab :=make (map[string ]*_df .Image );for _ ,_cfe :=range _feb ._gg {if _cfe .ImageValue !=nil {_gab [_cfe .Name ]=_cfe .ImageValue ;};};return _gab ,nil ;};

// JSON returns the field data as a string in JSON format.
func (_db FieldData )JSON ()(string ,error ){_ffe ,_gc :=_f .MarshalIndent (_db ._gg ,"","\u0020\u0020\u0020\u0020");return string (_ffe ),_gc ;};

// FieldValues implements model.FieldValueProvider interface.
func (_aac *FieldData )FieldValues ()(map[string ]_c .PdfObject ,error ){_beg :=make (map[string ]_c .PdfObject );for _ ,_cfa :=range _aac ._gg {if len (_cfa .Value )> 0{_beg [_cfa .Name ]=_c .MakeString (_cfa .Value );};};return _beg ,nil ;};

// LoadFromPDF loads form field data from a PDF.
func LoadFromPDF (rs _d .ReadSeeker )(*FieldData ,error ){_ec ,_fe :=_df .NewPdfReader (rs );if _fe !=nil {return nil ,_fe ;};if _ec .AcroForm ==nil {return nil ,nil ;};var _da []fieldValue ;_bc :=_ec .AcroForm .AllFields ();for _ ,_acf :=range _bc {var _fde []string ;
_af :=make (map[string ]struct{});_ed ,_bd :=_acf .FullName ();if _bd !=nil {return nil ,_bd ;};if _de ,_ea :=_acf .V .(*_c .PdfObjectString );_ea {_da =append (_da ,fieldValue {Name :_ed ,Value :_de .Decoded ()});continue ;};var _ead string ;for _ ,_dg :=range _acf .Annotations {_aa ,_bb :=_c .GetName (_dg .AS );
if _bb {_ead =_aa .String ();};_gf ,_cc :=_c .GetDict (_dg .AP );if !_cc {continue ;};_dc ,_ :=_c .GetDict (_gf .Get ("\u004e"));for _ ,_dd :=range _dc .Keys (){_bbd :=_dd .String ();if _ ,_gaf :=_af [_bbd ];!_gaf {_fde =append (_fde ,_bbd );_af [_bbd ]=struct{}{};
};};_afc ,_ :=_c .GetDict (_gf .Get ("\u0044"));for _ ,_aaf :=range _afc .Keys (){_ff :=_aaf .String ();if _ ,_fce :=_af [_ff ];!_fce {_fde =append (_fde ,_ff );_af [_ff ]=struct{}{};};};};_ag :=fieldValue {Name :_ed ,Value :_ead ,Options :_fde };_da =append (_da ,_ag );
};_ccd :=FieldData {_gg :_da };return &_ccd ,nil ;};

// SetImageFromFile assign image file to a specific field identified by fieldName.
func (_cfc *FieldData )SetImageFromFile (fieldName string ,imagePath string ,opt []string )error {_dda ,_fdf :=_ga .Open (imagePath );if _fdf !=nil {return _fdf ;};defer _dda .Close ();_eda ,_fdf :=_df .ImageHandling .Read (_dda );if _fdf !=nil {_fd .Log .Error ("\u0045\u0072\u0072or\u0020\u006c\u006f\u0061\u0064\u0069\u006e\u0067\u0020\u0069\u006d\u0061\u0067\u0065\u003a\u0020\u0025\u0073",_fdf );
return _fdf ;};return _cfc .SetImage (fieldName ,_eda ,opt );};