//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package transform ;import (_f "fmt";_ef "github.com/unidoc/unipdf/v4/common";_e "math";);func IdentityMatrix ()Matrix {return NewMatrix (1,0,0,1,0,0)};func (_cgfa Point )Displace (delta Point )Point {return Point {_cgfa .X +delta .X ,_cgfa .Y +delta .Y }};
func (_aec Matrix )Unrealistic ()bool {_ed ,_dac ,_ffa ,_dea :=_e .Abs (_aec [0]),_e .Abs (_aec [1]),_e .Abs (_aec [3]),_e .Abs (_aec [4]);_ag :=_ed > _bbd &&_dea > _bbd ;_fee :=_dac > _bbd &&_ffa > _bbd ;return !(_ag ||_fee );};func NewMatrix (a ,b ,c ,d ,tx ,ty float64 )Matrix {_a :=Matrix {a ,b ,0,c ,d ,0,tx ,ty ,1};
_a .clampRange ();return _a ;};func NewMatrixFromTransforms (xScale ,yScale ,theta ,tx ,ty float64 )Matrix {return IdentityMatrix ().Scale (xScale ,yScale ).Rotate (theta ).Translate (tx ,ty );};func (_ddg *Point )Transform (a ,b ,c ,d ,tx ,ty float64 ){_fga :=NewMatrix (a ,b ,c ,d ,tx ,ty );
_ddg .transformByMatrix (_fga );};func (_be Matrix )Rotate (theta float64 )Matrix {return _be .Mult (RotationMatrix (theta ))};const _egd =1.0e-6;func ShearMatrix (x ,y float64 )Matrix {return NewMatrix (1,y ,x ,1,0,0)};func (_da Matrix )Angle ()float64 {_gd :=_e .Atan2 (-_da [1],_da [0]);
if _gd < 0.0{_gd +=2*_e .Pi ;};return _gd /_e .Pi *180.0;};func (_de *Matrix )Shear (x ,y float64 ){_de .Concat (ShearMatrix (x ,y ))};func (_bg Point )Distance (b Point )float64 {return _e .Hypot (_bg .X -b .X ,_bg .Y -b .Y )};func (_fc Matrix )Identity ()bool {return _fc [0]==1&&_fc [1]==0&&_fc [2]==0&&_fc [3]==0&&_fc [4]==1&&_fc [5]==0&&_fc [6]==0&&_fc [7]==0&&_fc [8]==1;
};func (_ea *Matrix )Concat (b Matrix ){*_ea =Matrix {b [0]*_ea [0]+b [1]*_ea [3],b [0]*_ea [1]+b [1]*_ea [4],0,b [3]*_ea [0]+b [4]*_ea [3],b [3]*_ea [1]+b [4]*_ea [4],0,b [6]*_ea [0]+b [7]*_ea [3]+_ea [6],b [6]*_ea [1]+b [7]*_ea [4]+_ea [7],1};_ea .clampRange ();
};func (_edb Point )Rotate (theta float64 )Point {_acc :=_e .Hypot (_edb .X ,_edb .Y );_fdb :=_e .Atan2 (_edb .Y ,_edb .X );_gg ,_ege :=_e .Sincos (_fdb +theta /180.0*_e .Pi );return Point {_acc *_ege ,_acc *_gg };};func (_fbf Matrix )Translation ()(float64 ,float64 ){return _fbf [6],_fbf [7]};
type Point struct{X float64 ;Y float64 ;};func (_fb Matrix )Scale (xScale ,yScale float64 )Matrix {return _fb .Mult (ScaleMatrix (xScale ,yScale ))};const _bbd =1e-6;func (_fd Matrix )Translate (tx ,ty float64 )Matrix {return _fd .Mult (TranslationMatrix (tx ,ty ))};
const _fe =1e-10;func (_bf Matrix )ScalingFactorX ()float64 {return _e .Hypot (_bf [0],_bf [1])};func (_aff *Matrix )clampRange (){for _afb ,_afbf :=range _aff {if _afbf > _gf {_ef .Log .Debug ("\u0043L\u0041M\u0050\u003a\u0020\u0025\u0067\u0020\u002d\u003e\u0020\u0025\u0067",_afbf ,_gf );
_aff [_afb ]=_gf ;}else if _afbf < -_gf {_ef .Log .Debug ("\u0043L\u0041M\u0050\u003a\u0020\u0025\u0067\u0020\u002d\u003e\u0020\u0025\u0067",_afbf ,-_gf );_aff [_afb ]=-_gf ;};};};func ScaleMatrix (x ,y float64 )Matrix {return NewMatrix (x ,0,0,y ,0,0)};
func (_eab Point )String ()string {return _f .Sprintf ("(\u0025\u002e\u0032\u0066\u002c\u0025\u002e\u0032\u0066\u0029",_eab .X ,_eab .Y );};func (_df Matrix )Mult (b Matrix )Matrix {_df .Concat (b );return _df };func NewPoint (x ,y float64 )Point {return Point {X :x ,Y :y }};
func (_def *Point )Set (x ,y float64 ){_def .X ,_def .Y =x ,y };func (_dd *Matrix )Set (a ,b ,c ,d ,tx ,ty float64 ){_dd [0],_dd [1]=a ,b ;_dd [3],_dd [4]=c ,d ;_dd [6],_dd [7]=tx ,ty ;_dd .clampRange ();};func (_fg Matrix )Singular ()bool {return _e .Abs (_fg [0]*_fg [4]-_fg [1]*_fg [3])< _fe };
func (_cgfd Point )Interpolate (b Point ,t float64 )Point {return Point {X :(1-t )*_cgfd .X +t *b .X ,Y :(1-t )*_cgfd .Y +t *b .Y };};func RotationMatrix (angle float64 )Matrix {_cg :=_e .Cos (angle );_b :=_e .Sin (angle );return NewMatrix (_cg ,_b ,-_b ,_cg ,0,0);
};func (_dfg *Matrix )Clone ()Matrix {return NewMatrix (_dfg [0],_dfg [1],_dfg [3],_dfg [4],_dfg [6],_dfg [7]);};func (_cf Matrix )Round (precision float64 )Matrix {for _eg :=range _cf {_cf [_eg ]=_e .Round (_cf [_eg ]/precision )*precision ;};return _cf ;
};func (_cfg Matrix )String ()string {_ac ,_ae ,_bd ,_d ,_fcb ,_ca :=_cfg [0],_cfg [1],_cfg [3],_cfg [4],_cfg [6],_cfg [7];return _f .Sprintf ("\u005b\u00257\u002e\u0034\u0066\u002c%\u0037\u002e4\u0066\u002c\u0025\u0037\u002e\u0034\u0066\u002c%\u0037\u002e\u0034\u0066\u003a\u0025\u0037\u002e\u0034\u0066\u002c\u00257\u002e\u0034\u0066\u005d",_ac ,_ae ,_bd ,_d ,_fcb ,_ca );
};const _gf =1e9;func (_g Matrix )Transform (x ,y float64 )(float64 ,float64 ){_cgf :=x *_g [0]+y *_g [3]+_g [6];_ga :=x *_g [1]+y *_g [4]+_g [7];return _cgf ,_ga ;};func TranslationMatrix (tx ,ty float64 )Matrix {return NewMatrix (1,0,0,1,tx ,ty )};func (_bb Matrix )ScalingFactorY ()float64 {return _e .Hypot (_bb [3],_bb [4])};
type Matrix [9]float64 ;func (_dae *Point )transformByMatrix (_ddd Matrix ){_dae .X ,_dae .Y =_ddd .Transform (_dae .X ,_dae .Y )};func (_aef Matrix )Inverse ()(Matrix ,bool ){_ead ,_cae :=_aef [0],_aef [1];_cff ,_ee :=_aef [3],_aef [4];_af ,_aca :=_aef [6],_aef [7];
_ba :=_ead *_ee -_cae *_cff ;if _e .Abs (_ba )< _egd {return Matrix {},false ;};_gde ,_cb :=_ee /_ba ,-_cae /_ba ;_feg ,_baf :=-_cff /_ba ,_ead /_ba ;_ff :=-(_gde *_af +_feg *_aca );_eea :=-(_cb *_af +_baf *_aca );return NewMatrix (_gde ,_cb ,_feg ,_baf ,_ff ,_eea ),true ;
};