//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package sanitize ;import (_c "github.com/unidoc/unipdf/v4/common";_cb "github.com/unidoc/unipdf/v4/core";);

// GetSuspiciousObjects returns a count of each detected suspicious object.
func (_gcc *Sanitizer )GetSuspiciousObjects ()map[string ]int {return _gcc ._ce };

// New returns a new sanitizer object.
func New (opts SanitizationOpts )*Sanitizer {return &Sanitizer {_b :opts }};func (_cbf *Sanitizer )processObjects (_a []_cb .PdfObject )([]_cb .PdfObject ,error ){_aa :=[]_cb .PdfObject {};_fd :=_cbf ._b ;for _ ,_d :=range _a {switch _bd :=_d .(type ){case *_cb .PdfIndirectObject :_ad ,_ff :=_cb .GetDict (_bd );
if _ff {if _bb ,_ffa :=_cb .GetName (_ad .Get ("\u0054\u0079\u0070\u0065"));_ffa &&*_bb =="\u0043a\u0074\u0061\u006c\u006f\u0067"{if _ ,_fa :=_cb .GetIndirect (_ad .Get ("\u004f\u0070\u0065\u006e\u0041\u0063\u0074\u0069\u006f\u006e"));_fa &&_fd .OpenAction {_ad .Remove ("\u004f\u0070\u0065\u006e\u0041\u0063\u0074\u0069\u006f\u006e");
};}else if _beg ,_de :=_cb .GetName (_ad .Get ("\u0053"));_de {switch *_beg {case "\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074":if _fd .JavaScript {if _dg ,_ab :=_cb .GetStream (_ad .Get ("\u004a\u0053"));_ab {_fc :=[]byte {};_cd ,_ceg :=_cb .MakeStream (_fc ,nil );
if _ceg ==nil {*_dg =*_cd ;};};_c .Log .Debug ("\u004a\u0061\u0076\u0061\u0073\u0063\u0072\u0069\u0070\u0074\u0020a\u0063\u0074\u0069\u006f\u006e\u0020\u0073\u006b\u0069\u0070p\u0065\u0064\u002e");continue ;};case "\u0055\u0052\u0049":if _fd .URI {_c .Log .Debug ("\u0055\u0052\u0049\u0020ac\u0074\u0069\u006f\u006e\u0020\u0073\u006b\u0069\u0070\u0070\u0065\u0064\u002e");
continue ;};case "\u0047\u006f\u0054\u006f":if _fd .GoTo {_c .Log .Debug ("G\u004fT\u004f\u0020\u0061\u0063\u0074\u0069\u006f\u006e \u0073\u006b\u0069\u0070pe\u0064\u002e");continue ;};case "\u0047\u006f\u0054o\u0052":if _fd .GoToR {_c .Log .Debug ("R\u0065\u006d\u006f\u0074\u0065\u0020G\u006f\u0054\u004f\u0020\u0061\u0063\u0074\u0069\u006fn\u0020\u0073\u006bi\u0070p\u0065\u0064\u002e");
continue ;};case "\u004c\u0061\u0075\u006e\u0063\u0068":if _fd .Launch {_c .Log .Debug ("\u004a\u0061\u0076\u0061\u0073\u0063\u0072\u0069\u0070\u0074\u0020a\u0063\u0074\u0069\u006f\u006e\u0020\u0073\u006b\u0069\u0070p\u0065\u0064\u002e");continue ;};case "\u0052e\u006e\u0064\u0069\u0074\u0069\u006fn":if _af ,_abd :=_cb .GetStream (_ad .Get ("\u004a\u0053"));
_abd {_ca :=[]byte {};_fdb ,_fe :=_cb .MakeStream (_ca ,nil );if _fe ==nil {*_af =*_fdb ;};};};}else if _fcc :=_ad .Get ("\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074");_fcc !=nil &&_fd .JavaScript {continue ;}else if _fee ,_ba :=_cb .GetName (_ad .Get ("\u0054\u0079\u0070\u0065"));
_ba &&*_fee =="\u0041\u006e\u006eo\u0074"&&_fd .JavaScript {if _fad ,_g :=_cb .GetIndirect (_ad .Get ("\u0050\u0061\u0072\u0065\u006e\u0074"));_g {if _ga ,_cc :=_cb .GetDict (_fad .PdfObject );_cc {if _gf ,_eg :=_cb .GetDict (_ga .Get ("\u0041\u0041"));
_eg {_bf ,_fef :=_cb .GetIndirect (_gf .Get ("\u004b"));if _fef {if _ae ,_dc :=_cb .GetDict (_bf .PdfObject );_dc {if _gg ,_fdg :=_cb .GetName (_ae .Get ("\u0053"));_fdg &&*_gg =="\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"{_ae .Clear ();
}else if _cbb :=_gf .Get ("\u0046");_cbb !=nil {if _ec ,_bee :=_cb .GetIndirect (_cbb );_bee {if _gc ,_dcc :=_cb .GetDict (_ec .PdfObject );_dcc {if _cef ,_bdc :=_cb .GetName (_gc .Get ("\u0053"));_bdc &&*_cef =="\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"{_gc .Clear ();
};};};};};};};};};};};case *_cb .PdfObjectStream :_c .Log .Debug ("\u0070d\u0066\u0020\u006f\u0062j\u0065\u0063\u0074\u0020\u0073t\u0072e\u0061m\u0020\u0074\u0079\u0070\u0065\u0020\u0025T",_bd );case *_cb .PdfObjectStreams :_c .Log .Debug ("\u0070\u0064\u0066\u0020\u006f\u0062\u006a\u0065\u0063\u0074\u0020s\u0074\u0072\u0065\u0061\u006d\u0073\u0020\u0074\u0079\u0070e\u0020\u0025\u0054",_bd );
default:_c .Log .Debug ("u\u006e\u006b\u006e\u006fwn\u0020p\u0064\u0066\u0020\u006f\u0062j\u0065\u0063\u0074\u0020\u0025\u0054",_bd );};_aa =append (_aa ,_d );};_cbf .analyze (_aa );return _aa ,nil ;};

// Sanitizer represents a sanitizer object.
// It implements the Optimizer interface to access the objects field from the writer.
type Sanitizer struct{_b SanitizationOpts ;_ce map[string ]int ;};

// Optimize optimizes `objects` and returns updated list of objects.
func (_be *Sanitizer )Optimize (objects []_cb .PdfObject )([]_cb .PdfObject ,error ){return _be .processObjects (objects );};

// SanitizationOpts specifies the objects to be removed during sanitization.
type SanitizationOpts struct{

// JavaScript specifies wether JavaScript action should be removed. JavaScript Actions, section 12.6.4.16 of PDF32000_2008
JavaScript bool ;

// URI specifies if URI actions should be removed. 12.6.4.7 URI Actions, PDF32000_2008.
URI bool ;

// GoToR removes remote GoTo actions. 12.6.4.3 Remote Go-To Actions, PDF32000_2008.
GoToR bool ;

// GoTo specifies wether GoTo actions should be removed. 12.6.4.2 Go-To Actions, PDF32000_2008.
GoTo bool ;

// RenditionJS enables removing of `JS` entry from a Rendition Action.
// The `JS` entry has a value of text string or stream containing a JavaScript script that shall be executed when the action is triggered.
// 12.6.4.13 Rendition Actions Table 214, PDF32000_2008.
RenditionJS bool ;

// OpenAction removes OpenAction entry from the document catalog.
OpenAction bool ;

// Launch specifies wether Launch Action should be removed.
// A launch action launches an application or opens or prints a document.
// 12.6.4.5 Launch Actions, PDF32000_2008.
Launch bool ;};func (_dgb *Sanitizer )analyze (_bbf []_cb .PdfObject ){_fag :=map[string ]int {};for _ ,_gad :=range _bbf {switch _cg :=_gad .(type ){case *_cb .PdfIndirectObject :_dcb ,_cf :=_cb .GetDict (_cg .PdfObject );if _cf {if _dd ,_cab :=_cb .GetName (_dcb .Get ("\u0054\u0079\u0070\u0065"));
_cab &&*_dd =="\u0043a\u0074\u0061\u006c\u006f\u0067"{if _ ,_bc :=_cb .GetIndirect (_dcb .Get ("\u004f\u0070\u0065\u006e\u0041\u0063\u0074\u0069\u006f\u006e"));_bc {_fag ["\u004f\u0070\u0065\u006e\u0041\u0063\u0074\u0069\u006f\u006e"]++;};}else if _eb ,_ecf :=_cb .GetName (_dcb .Get ("\u0053"));
_ecf {_db :=_eb .String ();if _db =="\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"||_db =="\u0055\u0052\u0049"||_db =="\u0047\u006f\u0054\u006f"||_db =="\u0047\u006f\u0054o\u0052"||_db =="\u004c\u0061\u0075\u006e\u0063\u0068"{_fag [_db ]++;
}else if _db =="\u0052e\u006e\u0064\u0069\u0074\u0069\u006fn"{if _ ,_ac :=_cb .GetStream (_dcb .Get ("\u004a\u0053"));_ac {_fag [_db ]++;};};}else if _dec :=_dcb .Get ("\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074");_dec !=nil {_fag ["\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"]++;
}else if _ded ,_dccf :=_cb .GetIndirect (_dcb .Get ("\u0050\u0061\u0072\u0065\u006e\u0074"));_dccf {if _baa ,_bg :=_cb .GetDict (_ded .PdfObject );_bg {if _fadf ,_fcg :=_cb .GetDict (_baa .Get ("\u0041\u0041"));_fcg {_gaa :=_fadf .Get ("\u004b");_gac ,_gb :=_cb .GetIndirect (_gaa );
if _gb {if _bfb ,_aed :=_cb .GetDict (_gac .PdfObject );_aed {if _fefb ,_ecfd :=_cb .GetName (_bfb .Get ("\u0053"));_ecfd &&*_fefb =="\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"{_fag ["\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"]++;
}else if _ ,_cgf :=_cb .GetString (_bfb .Get ("\u004a\u0053"));_cgf {_fag ["\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"]++;}else {_cbfe :=_fadf .Get ("\u0046");if _cbfe !=nil {_fdd ,_adf :=_cb .GetIndirect (_cbfe );if _adf {if _ggc ,_ge :=_cb .GetDict (_fdd .PdfObject );
_ge {if _afb ,_gd :=_cb .GetName (_ggc .Get ("\u0053"));_gd {_df :=_afb .String ();_fag [_df ]++;};};};};};};};};};};};};};_dgb ._ce =_fag ;};