//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package jbig2 ;import (_cb "github.com/unidoc/unipdf/v5/internal/bitwise";_f "github.com/unidoc/unipdf/v5/internal/jbig2/decoder";_a "github.com/unidoc/unipdf/v5/internal/jbig2/document";_ce "github.com/unidoc/unipdf/v5/internal/jbig2/document/segments";
_bc "github.com/unidoc/unipdf/v5/internal/jbig2/errors";_b "sort";);type Globals map[int ]*_ce .Header ;func (_ge Globals )ToDocumentGlobals ()*_a .Globals {if _ge ==nil {return nil ;};_af :=[]*_ce .Header {};for _ ,_de :=range _ge {_af =append (_af ,_de );
};_b .Slice (_af ,func (_be ,_baf int )bool {return _af [_be ].SegmentNumber < _af [_baf ].SegmentNumber });return &_a .Globals {Segments :_af };};func DecodeBytes (encoded []byte ,parameters _f .Parameters ,globals ...Globals )([]byte ,error ){var _e Globals ;
if len (globals )> 0{_e =globals [0];};_g ,_d :=_f .Decode (encoded ,parameters ,_e .ToDocumentGlobals ());if _d !=nil {return nil ,_d ;};return _g .DecodeNextPage ();};func DecodeGlobals (encoded []byte )(Globals ,error ){const _ba ="\u0044\u0065\u0063\u006f\u0064\u0065\u0047\u006c\u006f\u0062\u0061\u006c\u0073";
_df :=_cb .NewReader (encoded );_ef ,_ga :=_a .DecodeDocument (_df ,nil );if _ga !=nil {return nil ,_bc .Wrap (_ga ,_ba ,"");};if _ef .GlobalSegments ==nil ||(_ef .GlobalSegments .Segments ==nil ){return nil ,_bc .Error (_ba ,"\u006eo\u0020\u0067\u006c\u006f\u0062\u0061\u006c\u0020\u0073\u0065\u0067m\u0065\u006e\u0074\u0073\u0020\u0066\u006f\u0075\u006e\u0064");
};_cbb :=Globals {};for _ ,_dc :=range _ef .GlobalSegments .Segments {_cbb [int (_dc .SegmentNumber )]=_dc ;};return _cbb ,nil ;};