//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package timeutils ;import (_a "errors";_adg "fmt";_b "regexp";_ad "strconv";_e "time";);var _dc =_b .MustCompile ("\u005cs\u002a\u0044\u005cs\u002a\u003a\u005cs\u002a(\\\u0064\u007b\u0034\u007d\u0029\u0028\u005cd\u007b\u0032\u007d\u0029\u0028\u005c\u0064\u007b\u0032\u007d\u0029\u0028\u005c\u0064\u007b\u0032\u007d\u0029\u0028\u005c\u0064\u007b\u0032\u007d\u0029\u0028\u005c\u0064{2\u007d)\u003f\u0028\u005b\u002b\u002d\u005a]\u0029\u003f\u0028\u005c\u0064{\u0032\u007d\u0029\u003f\u0027\u003f\u0028\u005c\u0064\u007b\u0032}\u0029\u003f");
func FormatPdfTime (in _e .Time )string {_bd :=in .Format ("\u002d\u0030\u0037\u003a\u0030\u0030");_eb ,_ :=_ad .ParseInt (_bd [1:3],10,32);_f ,_ :=_ad .ParseInt (_bd [4:6],10,32);_ed :=int64 (in .Year ());_ab :=int64 (in .Month ());_gb :=int64 (in .Day ());
_ae :=int64 (in .Hour ());_gd :=int64 (in .Minute ());_fc :=int64 (in .Second ());_ag :=_bd [0];return _adg .Sprintf ("\u0044\u003a\u0025\u002e\u0034\u0064\u0025\u002e\u0032\u0064\u0025\u002e\u0032\u0064\u0025\u002e\u0032\u0064\u0025\u002e\u0032\u0064\u0025\u002e2\u0064\u0025\u0063\u0025\u002e2\u0064\u0027%\u002e\u0032\u0064\u0027",_ed ,_ab ,_gb ,_ae ,_gd ,_fc ,_ag ,_eb ,_f );
};func ParsePdfTime (pdfTime string )(_e .Time ,error ){_adb :=_dc .FindAllStringSubmatch (pdfTime ,1);if len (_adb )< 1{if len (pdfTime )> 0&&pdfTime [0]!='D'{pdfTime =_adg .Sprintf ("\u0044\u003a\u0025\u0073",pdfTime );return ParsePdfTime (pdfTime );
};return _e .Time {},_adg .Errorf ("\u0069n\u0076\u0061\u006c\u0069\u0064\u0020\u0064\u0061\u0074\u0065\u0020s\u0074\u0072\u0069\u006e\u0067\u0020\u0028\u0025\u0073\u0029",pdfTime );};if len (_adb [0])!=10{return _e .Time {},_a .New ("\u0069\u006e\u0076\u0061\u006c\u0069\u0064\u0020\u0072\u0065\u0067\u0065\u0078p\u0020\u0067\u0072\u006f\u0075\u0070 \u006d\u0061\u0074\u0063\u0068\u0020\u006c\u0065\u006e\u0067\u0074\u0068\u0020!\u003d\u0020\u0031\u0030");
};_fg ,_ :=_ad .ParseInt (_adb [0][1],10,32);_be ,_ :=_ad .ParseInt (_adb [0][2],10,32);_ge ,_ :=_ad .ParseInt (_adb [0][3],10,32);_edf ,_ :=_ad .ParseInt (_adb [0][4],10,32);_aa ,_ :=_ad .ParseInt (_adb [0][5],10,32);_dd ,_ :=_ad .ParseInt (_adb [0][6],10,32);
var (_af byte ;_cc int64 ;_df int64 ;);_af ='+';if len (_adb [0][7])> 0{switch _adb [0][7]{case "\u002d":_af ='-';case "\u005a":_af ='Z';};};if len (_adb [0][8])> 0{_cc ,_ =_ad .ParseInt (_adb [0][8],10,32);}else {_cc =0;};if len (_adb [0][9])> 0{_df ,_ =_ad .ParseInt (_adb [0][9],10,32);
}else {_df =0;};_ga :=int (_cc *60*60+_df *60);switch _af {case '-':_ga =-_ga ;case 'Z':_ga =0;};_gfd :=_adg .Sprintf ("\u0055\u0054\u0043\u0025\u0063\u0025\u002e\u0032\u0064\u0025\u002e\u0032\u0064",_af ,_cc ,_df );_eg :=_e .FixedZone (_gfd ,_ga );return _e .Date (int (_fg ),_e .Month (_be ),int (_ge ),int (_edf ),int (_aa ),int (_dd ),0,_eg ),nil ;
};