//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package sampling ;import (_e "github.com/unidoc/unipdf/v4/internal/bitwise";_c "github.com/unidoc/unipdf/v4/internal/imageutil";_ab "io";);func (_cf *Writer )WriteSamples (samples []uint32 )error {for _ea :=0;_ea < len (samples );_ea ++{if _aed :=_cf .WriteSample (samples [_ea ]);
_aed !=nil {return _aed ;};};return nil ;};func (_gc *Writer )WriteSample (sample uint32 )error {if _ ,_bbe :=_gc ._gg .WriteBits (uint64 (sample ),_gc ._dc .BitsPerComponent );_bbe !=nil {return _bbe ;};_gc ._gb --;if _gc ._gb ==0{_gc ._gb =_gc ._dc .ColorComponents ;
_gc ._cbc ++;};if _gc ._cbc ==_gc ._dc .Width {if _gc ._cdb {_gc ._gg .FinishByte ();};_gc ._cbc =0;};return nil ;};func NewReader (img _c .ImageBase )*Reader {return &Reader {_eg :_e .NewReader (img .Data ),_ca :img ,_ba :img .ColorComponents ,_fg :img .BytesPerLine *8!=img .ColorComponents *img .BitsPerComponent *img .Width };
};type Writer struct{_dc _c .ImageBase ;_gg *_e .Writer ;_cbc ,_gb int ;_cdb bool ;};type Reader struct{_ca _c .ImageBase ;_eg *_e .Reader ;_b ,_cb ,_ba int ;_fg bool ;};type SampleReader interface{ReadSample ()(uint32 ,error );ReadSamples (_f []uint32 )error ;
};func NewWriter (img _c .ImageBase )*Writer {return &Writer {_gg :_e .NewWriterMSB (img .Data ),_dc :img ,_gb :img .ColorComponents ,_cdb :img .BytesPerLine *8!=img .ColorComponents *img .BitsPerComponent *img .Width };};func ResampleUint32 (data []uint32 ,bitsPerInputSample int ,bitsPerOutputSample int )[]uint32 {var _cg []uint32 ;
_eb :=bitsPerOutputSample ;var _fdc uint32 ;var _bb uint32 ;_ee :=0;_cd :=0;_cbg :=0;for _cbg < len (data ){if _ee > 0{_bf :=_ee ;if _eb < _bf {_bf =_eb ;};_fdc =(_fdc <<uint (_bf ))|(_bb >>uint (bitsPerInputSample -_bf ));_ee -=_bf ;if _ee > 0{_bb =_bb <<uint (_bf );
}else {_bb =0;};_eb -=_bf ;if _eb ==0{_cg =append (_cg ,_fdc );_eb =bitsPerOutputSample ;_fdc =0;_cd ++;};}else {_eee :=data [_cbg ];_cbg ++;_ae :=bitsPerInputSample ;if _eb < _ae {_ae =_eb ;};_ee =bitsPerInputSample -_ae ;_fdc =(_fdc <<uint (_ae ))|(_eee >>uint (_ee ));
if _ae < bitsPerInputSample {_bb =_eee <<uint (_ae );};_eb -=_ae ;if _eb ==0{_cg =append (_cg ,_fdc );_eb =bitsPerOutputSample ;_fdc =0;_cd ++;};};};for _ee >=bitsPerOutputSample {_dd :=_ee ;if _eb < _dd {_dd =_eb ;};_fdc =(_fdc <<uint (_dd ))|(_bb >>uint (bitsPerInputSample -_dd ));
_ee -=_dd ;if _ee > 0{_bb =_bb <<uint (_dd );}else {_bb =0;};_eb -=_dd ;if _eb ==0{_cg =append (_cg ,_fdc );_eb =bitsPerOutputSample ;_fdc =0;_cd ++;};};if _eb > 0&&_eb < bitsPerOutputSample {_fdc <<=uint (_eb );_cg =append (_cg ,_fdc );};return _cg ;};
type SampleWriter interface{WriteSample (_de uint32 )error ;WriteSamples (_dg []uint32 )error ;};func ResampleBytes (data []byte ,bitsPerSample int )[]uint32 {var _fd []uint32 ;_ef :=bitsPerSample ;var _gf uint32 ;var _cac byte ;_fe :=0;_bae :=0;_ga :=0;
for _ga < len (data ){if _fe > 0{_da :=_fe ;if _ef < _da {_da =_ef ;};_gf =(_gf <<uint (_da ))|uint32 (_cac >>uint (8-_da ));_fe -=_da ;if _fe > 0{_cac =_cac <<uint (_da );}else {_cac =0;};_ef -=_da ;if _ef ==0{_fd =append (_fd ,_gf );_ef =bitsPerSample ;
_gf =0;_bae ++;};}else {_ac :=data [_ga ];_ga ++;_gfc :=8;if _ef < _gfc {_gfc =_ef ;};_fe =8-_gfc ;_gf =(_gf <<uint (_gfc ))|uint32 (_ac >>uint (_fe ));if _gfc < 8{_cac =_ac <<uint (_gfc );};_ef -=_gfc ;if _ef ==0{_fd =append (_fd ,_gf );_ef =bitsPerSample ;
_gf =0;_bae ++;};};};for _fe >=bitsPerSample {_aa :=_fe ;if _ef < _aa {_aa =_ef ;};_gf =(_gf <<uint (_aa ))|uint32 (_cac >>uint (8-_aa ));_fe -=_aa ;if _fe > 0{_cac =_cac <<uint (_aa );}else {_cac =0;};_ef -=_aa ;if _ef ==0{_fd =append (_fd ,_gf );_ef =bitsPerSample ;
_gf =0;_bae ++;};};return _fd ;};func (_ce *Reader )ReadSample ()(uint32 ,error ){if _ce ._cb ==_ce ._ca .Height {return 0,_ab .EOF ;};_af ,_ed :=_ce ._eg .ReadBits (byte (_ce ._ca .BitsPerComponent ));if _ed !=nil {return 0,_ed ;};_ce ._ba --;if _ce ._ba ==0{_ce ._ba =_ce ._ca .ColorComponents ;
_ce ._b ++;};if _ce ._b ==_ce ._ca .Width {if _ce ._fg {_ce ._eg .ConsumeRemainingBits ();};_ce ._b =0;_ce ._cb ++;};return uint32 (_af ),nil ;};func (_d *Reader )ReadSamples (samples []uint32 )(_cc error ){for _g :=0;_g < len (samples );_g ++{samples [_g ],_cc =_d .ReadSample ();
if _cc !=nil {return _cc ;};};return nil ;};