//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

// Package ps implements various functionalities needed for handling Postscript for PDF uses, in particular
// for PDF function type 4.
//
// Package ps implements various functionalities needed for handling Postscript for PDF uses, in particular
// for PDF function type 4.
package ps ;import (_c "bufio";_gg "bytes";_g "errors";_e "fmt";_gge "github.com/unidoc/unipdf/v4/common";_gc "github.com/unidoc/unipdf/v4/core";_a "io";_f "math";);func (_df *PSOperand )div (_fbf *PSStack )error {_ffd ,_gbe :=_fbf .Pop ();if _gbe !=nil {return _gbe ;
};_cde ,_gbe :=_fbf .Pop ();if _gbe !=nil {return _gbe ;};_bff ,_gfb :=_ffd .(*PSReal );_aee ,_dccd :=_ffd .(*PSInteger );if !_gfb &&!_dccd {return ErrTypeCheck ;};if _gfb &&_bff .Val ==0{return ErrUndefinedResult ;};if _dccd &&_aee .Val ==0{return ErrUndefinedResult ;
};_cfa ,_ffdc :=_cde .(*PSReal );_gfbg ,_bae :=_cde .(*PSInteger );if !_ffdc &&!_bae {return ErrTypeCheck ;};var _dee float64 ;if _ffdc {_dee =_cfa .Val ;}else {_dee =float64 (_gfbg .Val );};if _gfb {_dee /=_bff .Val ;}else {_dee /=float64 (_aee .Val );
};_gbe =_fbf .Push (MakeReal (_dee ));return _gbe ;};

// Append appends an object to the PSProgram.
func (_geg *PSProgram )Append (obj PSObject ){*_geg =append (*_geg ,obj )};func (_gbde *PSOperand )sub (_cge *PSStack )error {_gdbe ,_efde :=_cge .Pop ();if _efde !=nil {return _efde ;};_bgdg ,_efde :=_cge .Pop ();if _efde !=nil {return _efde ;};_dag ,_afg :=_gdbe .(*PSReal );
_fbc ,_agff :=_gdbe .(*PSInteger );if !_afg &&!_agff {return ErrTypeCheck ;};_geaab ,_efea :=_bgdg .(*PSReal );_gbba ,_aebd :=_bgdg .(*PSInteger );if !_efea &&!_aebd {return ErrTypeCheck ;};if _agff &&_aebd {_ede :=_gbba .Val -_fbc .Val ;_gegc :=_cge .Push (MakeInteger (_ede ));
return _gegc ;};var _gaae float64 =0;if _efea {_gaae =_geaab .Val ;}else {_gaae =float64 (_gbba .Val );};if _afg {_gaae -=_dag .Val ;}else {_gaae -=float64 (_fbc .Val );};_efde =_cge .Push (MakeReal (_gaae ));return _efde ;};func (_bba *PSOperand )ln (_gdea *PSStack )error {_bcd ,_ddgb :=_gdea .PopNumberAsFloat64 ();
if _ddgb !=nil {return _ddgb ;};_eeb :=_f .Log (_bcd );_ddgb =_gdea .Push (MakeReal (_eeb ));return _ddgb ;};func (_geaa *PSReal )DebugString ()string {return _e .Sprintf ("\u0072e\u0061\u006c\u003a\u0025\u002e\u0035f",_geaa .Val );};

// PSObject represents a postscript object.
type PSObject interface{

// Duplicate makes a fresh copy of the PSObject.
Duplicate ()PSObject ;

// DebugString returns a descriptive representation of the PSObject with more information than String()
// for debugging purposes.
DebugString ()string ;

// String returns a string representation of the PSObject.
String ()string ;};func (_gce *PSOperand )String ()string {return string (*_gce )};func (_bb *PSBoolean )String ()string {return _e .Sprintf ("\u0025\u0076",_bb .Val )};func (_gfe *PSOperand )cvi (_bcgd *PSStack )error {_bbd ,_gda :=_bcgd .Pop ();if _gda !=nil {return _gda ;
};if _dab ,_dbd :=_bbd .(*PSReal );_dbd {_ccb :=int (_dab .Val );_gda =_bcgd .Push (MakeInteger (_ccb ));}else if _aed ,_cag :=_bbd .(*PSInteger );_cag {_dcea :=_aed .Val ;_gda =_bcgd .Push (MakeInteger (_dcea ));}else {return ErrTypeCheck ;};return _gda ;
};func (_egb *PSInteger )DebugString ()string {return _e .Sprintf ("\u0069\u006e\u0074\u003a\u0025\u0064",_egb .Val );};

// PSParser is a basic Postscript parser.
type PSParser struct{_caeda *_c .Reader };

// MakeInteger returns a new PSInteger object initialized with `val`.
func MakeInteger (val int )*PSInteger {_dbda :=PSInteger {};_dbda .Val =val ;return &_dbda };func (_gbb *PSOperand )round (_aeed *PSStack )error {_egeb ,_gcb :=_aeed .Pop ();if _gcb !=nil {return _gcb ;};if _ffca ,_gegb :=_egeb .(*PSReal );_gegb {_gcb =_aeed .Push (MakeReal (_f .Floor (_ffca .Val +0.5)));
}else if _dgb ,_cfab :=_egeb .(*PSInteger );_cfab {_gcb =_aeed .Push (MakeInteger (_dgb .Val ));}else {return ErrTypeCheck ;};return _gcb ;};func (_cbea *PSOperand )sin (_deef *PSStack )error {_dgbb ,_eag :=_deef .PopNumberAsFloat64 ();if _eag !=nil {return _eag ;
};_dgff :=_f .Sin (_dgbb *_f .Pi /180.0);_eag =_deef .Push (MakeReal (_dgff ));return _eag ;};var ErrStackUnderflow =_g .New ("\u0073t\u0061c\u006b\u0020\u0075\u006e\u0064\u0065\u0072\u0066\u006c\u006f\u0077");

// PopNumberAsFloat64 pops and return the numeric value of the top of the stack as a float64.
// Real or integer only.
func (_edea *PSStack )PopNumberAsFloat64 ()(float64 ,error ){_ddcc ,_bca :=_edea .Pop ();if _bca !=nil {return 0,_bca ;};if _gffd ,_ega :=_ddcc .(*PSReal );_ega {return _gffd .Val ,nil ;}else if _aefd ,_bgggc :=_ddcc .(*PSInteger );_bgggc {return float64 (_aefd .Val ),nil ;
}else {return 0,ErrTypeCheck ;};};func (_dc *PSReal )Duplicate ()PSObject {_dbe :=PSReal {};_dbe .Val =_dc .Val ;return &_dbe };func (_ecc *PSOperand )index (_adfd *PSStack )error {_aad ,_bcca :=_adfd .Pop ();if _bcca !=nil {return _bcca ;};_ggeb ,_bafe :=_aad .(*PSInteger );
if !_bafe {return ErrTypeCheck ;};if _ggeb .Val < 0{return ErrRangeCheck ;};if _ggeb .Val > len (*_adfd )-1{return ErrStackUnderflow ;};_bdf :=(*_adfd )[len (*_adfd )-1-_ggeb .Val ];_bcca =_adfd .Push (_bdf .Duplicate ());return _bcca ;};func (_dbg *PSBoolean )DebugString ()string {return _e .Sprintf ("\u0062o\u006f\u006c\u003a\u0025\u0076",_dbg .Val );
};func (_gdb *PSProgram )String ()string {_dd :="\u007b\u0020";for _ ,_ab :=range *_gdb {_dd +=_ab .String ();_dd +="\u0020";};_dd +="\u007d";return _dd ;};

// NewPSParser returns a new instance of the PDF Postscript parser from input data.
func NewPSParser (content []byte )*PSParser {_gbeg :=PSParser {};_gagf :=_gg .NewBuffer (content );_gbeg ._caeda =_c .NewReader (_gagf );return &_gbeg ;};

// PSReal represents a real number.
type PSReal struct{Val float64 ;};func (_abb *PSOperand )mul (_fbd *PSStack )error {_gdec ,_afe :=_fbd .Pop ();if _afe !=nil {return _afe ;};_abae ,_afe :=_fbd .Pop ();if _afe !=nil {return _afe ;};_gggc ,_bda :=_gdec .(*PSReal );_aaab ,_ege :=_gdec .(*PSInteger );
if !_bda &&!_ege {return ErrTypeCheck ;};_fgca ,_gba :=_abae .(*PSReal );_fbbe ,_cgf :=_abae .(*PSInteger );if !_gba &&!_cgf {return ErrTypeCheck ;};if _ege &&_cgf {_cgfe :=_aaab .Val *_fbbe .Val ;_eedf :=_fbd .Push (MakeInteger (_cgfe ));return _eedf ;
};var _bggg float64 ;if _bda {_bggg =_gggc .Val ;}else {_bggg =float64 (_aaab .Val );};if _gba {_bggg *=_fgca .Val ;}else {_bggg *=float64 (_fbbe .Val );};_afe =_fbd .Push (MakeReal (_bggg ));return _afe ;};func (_gdc *PSInteger )Duplicate ()PSObject {_ff :=PSInteger {};
_ff .Val =_gdc .Val ;return &_ff };func (_aeeb *PSOperand )or (_ffge *PSStack )error {_efd ,_adfda :=_ffge .Pop ();if _adfda !=nil {return _adfda ;};_fecf ,_adfda :=_ffge .Pop ();if _adfda !=nil {return _adfda ;};if _fce ,_babe :=_efd .(*PSBoolean );_babe {_fae ,_gdac :=_fecf .(*PSBoolean );
if !_gdac {return ErrTypeCheck ;};_adfda =_ffge .Push (MakeBool (_fce .Val ||_fae .Val ));return _adfda ;};if _gbad ,_efe :=_efd .(*PSInteger );_efe {_dgf ,_bdab :=_fecf .(*PSInteger );if !_bdab {return ErrTypeCheck ;};_adfda =_ffge .Push (MakeInteger (_gbad .Val |_dgf .Val ));
return _adfda ;};return ErrTypeCheck ;};func (_gbf *PSOperand )idiv (_fee *PSStack )error {_fgc ,_eed :=_fee .Pop ();if _eed !=nil {return _eed ;};_gfef ,_eed :=_fee .Pop ();if _eed !=nil {return _eed ;};_gac ,_dgg :=_fgc .(*PSInteger );if !_dgg {return ErrTypeCheck ;
};if _gac .Val ==0{return ErrUndefinedResult ;};_fec ,_dgg :=_gfef .(*PSInteger );if !_dgg {return ErrTypeCheck ;};_daea :=_fec .Val /_gac .Val ;_eed =_fee .Push (MakeInteger (_daea ));return _eed ;};func (_cbb *PSParser )parseBool ()(*PSBoolean ,error ){_bga ,_dfea :=_cbb ._caeda .Peek (4);
if _dfea !=nil {return MakeBool (false ),_dfea ;};if (len (_bga )>=4)&&(string (_bga [:4])=="\u0074\u0072\u0075\u0065"){_cbb ._caeda .Discard (4);return MakeBool (true ),nil ;};_bga ,_dfea =_cbb ._caeda .Peek (5);if _dfea !=nil {return MakeBool (false ),_dfea ;
};if (len (_bga )>=5)&&(string (_bga [:5])=="\u0066\u0061\u006cs\u0065"){_cbb ._caeda .Discard (5);return MakeBool (false ),nil ;};return MakeBool (false ),_g .New ("\u0075n\u0065\u0078\u0070\u0065c\u0074\u0065\u0064\u0020\u0062o\u006fl\u0065a\u006e\u0020\u0073\u0074\u0072\u0069\u006eg");
};

// MakeReal returns a new PSReal object initialized with `val`.
func MakeReal (val float64 )*PSReal {_eagaf :=PSReal {};_eagaf .Val =val ;return &_eagaf };

// PSProgram defines a Postscript program which is a series of PS objects (arguments, commands, programs etc).
type PSProgram []PSObject ;

// Push pushes an object on top of the stack.
func (_edg *PSStack )Push (obj PSObject )error {if len (*_edg )> 100{return ErrStackOverflow ;};*_edg =append (*_edg ,obj );return nil ;};func (_bab *PSOperand )bitshift (_eeg *PSStack )error {_ddd ,_age :=_eeg .PopInteger ();if _age !=nil {return _age ;
};_fba ,_age :=_eeg .PopInteger ();if _age !=nil {return _age ;};var _edc int ;if _ddd >=0{_edc =_fba <<uint (_ddd );}else {_edc =_fba >>uint (-_ddd );};_age =_eeg .Push (MakeInteger (_edc ));return _age ;};

// PSOperand represents a Postscript operand (text string).
type PSOperand string ;func (_aba *PSOperand )lt (_afd *PSStack )error {_febb ,_cab :=_afd .PopNumberAsFloat64 ();if _cab !=nil {return _cab ;};_badf ,_cab :=_afd .PopNumberAsFloat64 ();if _cab !=nil {return _cab ;};if _f .Abs (_badf -_febb )< _eg {_aabg :=_afd .Push (MakeBool (false ));
return _aabg ;}else if _badf < _febb {_aaa :=_afd .Push (MakeBool (true ));return _aaa ;}else {_egg :=_afd .Push (MakeBool (false ));return _egg ;};};func (_eedc *PSOperand )mod (_cad *PSStack )error {_gaf ,_cfff :=_cad .Pop ();if _cfff !=nil {return _cfff ;
};_bebb ,_cfff :=_cad .Pop ();if _cfff !=nil {return _cfff ;};_caed ,_cdf :=_gaf .(*PSInteger );if !_cdf {return ErrTypeCheck ;};if _caed .Val ==0{return ErrUndefinedResult ;};_acab ,_cdf :=_bebb .(*PSInteger );if !_cdf {return ErrTypeCheck ;};_agca :=_acab .Val %_caed .Val ;
_cfff =_cad .Push (MakeInteger (_agca ));return _cfff ;};func (_bdb *PSOperand )dup (_fea *PSStack )error {_beb ,_add :=_fea .Pop ();if _add !=nil {return _add ;};_add =_fea .Push (_beb );if _add !=nil {return _add ;};_add =_fea .Push (_beb .Duplicate ());
return _add ;};

// PSBoolean represents a boolean value.
type PSBoolean struct{Val bool ;};func (_agb *PSOperand )exp (_abd *PSStack )error {_fgg ,_dddc :=_abd .PopNumberAsFloat64 ();if _dddc !=nil {return _dddc ;};_bfg ,_dddc :=_abd .PopNumberAsFloat64 ();if _dddc !=nil {return _dddc ;};if _f .Abs (_fgg )< 1&&_bfg < 0{return ErrUndefinedResult ;
};_ceg :=_f .Pow (_bfg ,_fgg );_dddc =_abd .Push (MakeReal (_ceg ));return _dddc ;};

// PSInteger represents an integer.
type PSInteger struct{Val int ;};func (_cfg *PSOperand )ifelse (_aff *PSStack )error {_gaee ,_eddf :=_aff .Pop ();if _eddf !=nil {return _eddf ;};_fcc ,_eddf :=_aff .Pop ();if _eddf !=nil {return _eddf ;};_bbdd ,_eddf :=_aff .Pop ();if _eddf !=nil {return _eddf ;
};_babg ,_faf :=_gaee .(*PSProgram );if !_faf {return ErrTypeCheck ;};_fde ,_faf :=_fcc .(*PSProgram );if !_faf {return ErrTypeCheck ;};_bfb ,_faf :=_bbdd .(*PSBoolean );if !_faf {return ErrTypeCheck ;};if _bfb .Val {_adfb :=_fde .Exec (_aff );return _adfb ;
};_eddf =_babg .Exec (_aff );return _eddf ;};

// Parse parses the postscript and store as a program that can be executed.
func (_dbag *PSParser )Parse ()(*PSProgram ,error ){_dbag .skipSpaces ();_bcbf ,_fbff :=_dbag ._caeda .Peek (2);if _fbff !=nil {return nil ,_fbff ;};if _bcbf [0]!='{'{return nil ,_g .New ("\u0069\u006e\u0076\u0061\u006c\u0069\u0064\u0020\u0050\u0053\u0020\u0050\u0072\u006f\u0067\u0072\u0061\u006d\u0020\u006e\u006f\u0074\u0020\u0073t\u0061\u0072\u0074\u0069\u006eg\u0020\u0077i\u0074\u0068\u0020\u007b");
};_gaac ,_fbff :=_dbag .parseFunction ();if _fbff !=nil &&_fbff !=_a .EOF {return nil ,_fbff ;};return _gaac ,_fbff ;};func (_gefc *PSOperand )roll (_gedg *PSStack )error {_bfgc ,_efec :=_gedg .Pop ();if _efec !=nil {return _efec ;};_ebc ,_efec :=_gedg .Pop ();
if _efec !=nil {return _efec ;};_cbed ,_bcf :=_bfgc .(*PSInteger );if !_bcf {return ErrTypeCheck ;};_bgb ,_bcf :=_ebc .(*PSInteger );if !_bcf {return ErrTypeCheck ;};if _bgb .Val < 0{return ErrRangeCheck ;};if _bgb .Val ==0||_bgb .Val ==1{return nil ;};
if _bgb .Val > len (*_gedg ){return ErrStackUnderflow ;};for _acag :=0;_acag < _gacf (_cbed .Val );_acag ++{var _cfb []PSObject ;_cfb =(*_gedg )[len (*_gedg )-(_bgb .Val ):len (*_gedg )];if _cbed .Val > 0{_eeff :=_cfb [len (_cfb )-1];_cfb =append ([]PSObject {_eeff },_cfb [0:len (_cfb )-1]...);
}else {_ccgf :=_cfb [len (_cfb )-_bgb .Val ];_cfb =append (_cfb [1:],_ccgf );};_agd :=append ((*_gedg )[0:len (*_gedg )-_bgb .Val ],_cfb ...);_gedg =&_agd ;};return nil ;};func (_dca *PSParser )parseOperand ()(*PSOperand ,error ){var _ace []byte ;for {_fgf ,_dafc :=_dca ._caeda .Peek (1);
if _dafc !=nil {if _dafc ==_a .EOF {break ;};return nil ,_dafc ;};if _gc .IsDelimiter (_fgf [0]){break ;};if _gc .IsWhiteSpace (_fgf [0]){break ;};_ggc ,_ :=_dca ._caeda .ReadByte ();_ace =append (_ace ,_ggc );};if len (_ace )==0{return nil ,_g .New ("\u0069\u006e\u0076al\u0069\u0064\u0020\u006f\u0070\u0065\u0072\u0061\u006e\u0064\u0020\u0028\u0065\u006d\u0070\u0074\u0079\u0029");
};return MakeOperand (string (_ace )),nil ;};func (_ccc *PSParser )parseFunction ()(*PSProgram ,error ){_eab ,_ :=_ccc ._caeda .ReadByte ();if _eab !='{'{return nil ,_g .New ("\u0069\u006ev\u0061\u006c\u0069d\u0020\u0066\u0075\u006e\u0063\u0074\u0069\u006f\u006e");
};_gdcb :=NewPSProgram ();for {_ccc .skipSpaces ();_ccc .skipComments ();_dgbd ,_dbb :=_ccc ._caeda .Peek (2);if _dbb !=nil {if _dbb ==_a .EOF {break ;};return nil ,_dbb ;};if _gge .Log .IsLogLevel (_gge .LogLevelTrace ){_gge .Log .Trace ("\u0050e\u0065k\u0020\u0073\u0074\u0072\u0069\u006e\u0067\u003a\u0020\u0025\u0073",string (_dgbd ));
};if _dgbd [0]=='}'{if _gge .Log .IsLogLevel (_gge .LogLevelTrace ){_gge .Log .Trace ("\u0045\u004f\u0046 \u0066\u0075\u006e\u0063\u0074\u0069\u006f\u006e");};_ccc ._caeda .ReadByte ();break ;}else if _dgbd [0]=='{'{if _gge .Log .IsLogLevel (_gge .LogLevelTrace ){_gge .Log .Trace ("\u0046u\u006e\u0063\u0074\u0069\u006f\u006e!");
};_gdef ,_fdc :=_ccc .parseFunction ();if _fdc !=nil {return nil ,_fdc ;};_gdcb .Append (_gdef );}else if _gc .IsDecimalDigit (_dgbd [0])||(_dgbd [0]=='-'&&_gc .IsDecimalDigit (_dgbd [1])){if _gge .Log .IsLogLevel (_gge .LogLevelTrace ){_gge .Log .Trace ("\u002d>\u004e\u0075\u006d\u0062\u0065\u0072!");
};_gdeg ,_fffa :=_ccc .parseNumber ();if _fffa !=nil {return nil ,_fffa ;};_gdcb .Append (_gdeg );}else {if _gge .Log .IsLogLevel (_gge .LogLevelTrace ){_gge .Log .Trace ("\u002d>\u004fp\u0065\u0072\u0061\u006e\u0064 \u006f\u0072 \u0062\u006f\u006f\u006c\u003f");
};_dgbd ,_ =_ccc ._caeda .Peek (5);_febe :=string (_dgbd );if _gge .Log .IsLogLevel (_gge .LogLevelTrace ){_gge .Log .Trace ("\u0050\u0065\u0065k\u0020\u0073\u0074\u0072\u003a\u0020\u0025\u0073",_febe );};if (len (_febe )> 4)&&(_febe [:5]=="\u0066\u0061\u006cs\u0065"){_dbc ,_adg :=_ccc .parseBool ();
if _adg !=nil {return nil ,_adg ;};_gdcb .Append (_dbc );}else if (len (_febe )> 3)&&(_febe [:4]=="\u0074\u0072\u0075\u0065"){_bfc ,_aagdc :=_ccc .parseBool ();if _aagdc !=nil {return nil ,_aagdc ;};_gdcb .Append (_bfc );}else {_aeeda ,_ebee :=_ccc .parseOperand ();
if _ebee !=nil {return nil ,_ebee ;};_gdcb .Append (_aeeda );};};};return _gdcb ,nil ;};func (_ccfa *PSOperand )floor (_cfd *PSStack )error {_ccbg ,_ggfd :=_cfd .Pop ();if _ggfd !=nil {return _ggfd ;};if _cffa ,_dae :=_ccbg .(*PSReal );_dae {_ggfd =_cfd .Push (MakeReal (_f .Floor (_cffa .Val )));
}else if _gca ,_fbbbc :=_ccbg .(*PSInteger );_fbbbc {_ggfd =_cfd .Push (MakeInteger (_gca .Val ));}else {return ErrTypeCheck ;};return _ggfd ;};

// Execute executes the program for an input parameters `objects` and returns a slice of output objects.
func (_fe *PSExecutor )Execute (objects []PSObject )([]PSObject ,error ){for _ ,_ae :=range objects {_bg :=_fe .Stack .Push (_ae );if _bg !=nil {return nil ,_bg ;};};_cf :=_fe ._b .Exec (_fe .Stack );if _cf !=nil {_gge .Log .Debug ("\u0045x\u0065c\u0020\u0066\u0061\u0069\u006c\u0065\u0064\u003a\u0020\u0025\u0076",_cf );
return nil ,_cf ;};_ggd :=[]PSObject (*_fe .Stack );_fe .Stack .Empty ();return _ggd ,nil ;};func (_dfc *PSOperand )ge (_bcc *PSStack )error {_ffg ,_cgcg :=_bcc .PopNumberAsFloat64 ();if _cgcg !=nil {return _cgcg ;};_afc ,_cgcg :=_bcc .PopNumberAsFloat64 ();
if _cgcg !=nil {return _cgcg ;};if _f .Abs (_afc -_ffg )< _eg {_gcge :=_bcc .Push (MakeBool (true ));return _gcge ;}else if _afc > _ffg {_ddgg :=_bcc .Push (MakeBool (true ));return _ddgg ;}else {_gded :=_bcc .Push (MakeBool (false ));return _gded ;};};


// PSExecutor has its own execution stack and is used to executre a PS routine (program).
type PSExecutor struct{Stack *PSStack ;_b *PSProgram ;};func (_eef *PSOperand )ceiling (_bbf *PSStack )error {_cd ,_edb :=_bbf .Pop ();if _edb !=nil {return _edb ;};if _afa ,_cdc :=_cd .(*PSReal );_cdc {_edb =_bbf .Push (MakeReal (_f .Ceil (_afa .Val )));
}else if _da ,_ddda :=_cd .(*PSInteger );_ddda {_edb =_bbf .Push (MakeInteger (_da .Val ));}else {_edb =ErrTypeCheck ;};return _edb ;};

// Pop pops an object from the top of the stack.
func (_bag *PSStack )Pop ()(PSObject ,error ){if len (*_bag )< 1{return nil ,ErrStackUnderflow ;};_aagg :=(*_bag )[len (*_bag )-1];*_bag =(*_bag )[0:len (*_bag )-1];return _aagg ,nil ;};

// DebugString returns a descriptive string representation of the stack - intended for debugging.
func (_geeb *PSStack )DebugString ()string {_bdc :="\u005b\u0020";for _ ,_gfc :=range *_geeb {_bdc +=_gfc .DebugString ();_bdc +="\u0020";};_bdc +="\u005d";return _bdc ;};var ErrRangeCheck =_g .New ("\u0072\u0061\u006e\u0067\u0065\u0020\u0063\u0068\u0065\u0063\u006b\u0020e\u0072\u0072\u006f\u0072");
func (_fg *PSOperand )and (_aae *PSStack )error {_geae ,_gbd :=_aae .Pop ();if _gbd !=nil {return _gbd ;};_ccd ,_gbd :=_aae .Pop ();if _gbd !=nil {return _gbd ;};if _dce ,_fbb :=_geae .(*PSBoolean );_fbb {_bee ,_bbg :=_ccd .(*PSBoolean );if !_bbg {return ErrTypeCheck ;
};_gbd =_aae .Push (MakeBool (_dce .Val &&_bee .Val ));return _gbd ;};if _bec ,_bcg :=_geae .(*PSInteger );_bcg {_cb ,_ccf :=_ccd .(*PSInteger );if !_ccf {return ErrTypeCheck ;};_gbd =_aae .Push (MakeInteger (_bec .Val &_cb .Val ));return _gbd ;};return ErrTypeCheck ;
};var ErrTypeCheck =_g .New ("\u0074\u0079p\u0065\u0020\u0063h\u0065\u0063\u006b\u0020\u0065\u0072\u0072\u006f\u0072");func (_ddb *PSProgram )Duplicate ()PSObject {_bad :=&PSProgram {};for _ ,_cfe :=range *_ddb {_bad .Append (_cfe .Duplicate ());};return _bad ;
};func (_fa *PSReal )String ()string {return _e .Sprintf ("\u0025\u002e\u0035\u0066",_fa .Val )};func (_dcc *PSOperand )cvr (_baf *PSStack )error {_fbg ,_febd :=_baf .Pop ();if _febd !=nil {return _febd ;};if _edd ,_aagd :=_fbg .(*PSReal );_aagd {_febd =_baf .Push (MakeReal (_edd .Val ));
}else if _cdb ,_fef :=_fbg .(*PSInteger );_fef {_febd =_baf .Push (MakeReal (float64 (_cdb .Val )));}else {return ErrTypeCheck ;};return _febd ;};func (_eec *PSOperand )le (_ebfg *PSStack )error {_gee ,_ddce :=_ebfg .PopNumberAsFloat64 ();if _ddce !=nil {return _ddce ;
};_fcce ,_ddce :=_ebfg .PopNumberAsFloat64 ();if _ddce !=nil {return _ddce ;};if _f .Abs (_fcce -_gee )< _eg {_abf :=_ebfg .Push (MakeBool (true ));return _abf ;}else if _fcce < _gee {_aga :=_ebfg .Push (MakeBool (true ));return _aga ;}else {_cgg :=_ebfg .Push (MakeBool (false ));
return _cgg ;};};func (_cac *PSOperand )gt (_ffc *PSStack )error {_gged ,_ggfb :=_ffc .PopNumberAsFloat64 ();if _ggfb !=nil {return _ggfb ;};_dfa ,_ggfb :=_ffc .PopNumberAsFloat64 ();if _ggfb !=nil {return _ggfb ;};if _f .Abs (_dfa -_gged )< _eg {_bggde :=_ffc .Push (MakeBool (false ));
return _bggde ;}else if _dfa > _gged {_bdbe :=_ffc .Push (MakeBool (true ));return _bdbe ;}else {_eca :=_ffc .Push (MakeBool (false ));return _eca ;};};func _gacf (_gfgb int )int {if _gfgb < 0{return -_gfgb ;};return _gfgb ;};var ErrUndefinedResult =_g .New ("\u0075\u006e\u0064\u0065fi\u006e\u0065\u0064\u0020\u0072\u0065\u0073\u0075\u006c\u0074\u0020\u0065\u0072\u0072o\u0072");
func (_fgeg *PSOperand )cos (_ec *PSStack )error {_cff ,_bgc :=_ec .PopNumberAsFloat64 ();if _bgc !=nil {return _bgc ;};_cae :=_f .Cos (_cff *_f .Pi /180.0);_bgc =_ec .Push (MakeReal (_cae ));return _bgc ;};func (_geac *PSOperand )eq (_ged *PSStack )error {_fadg ,_dad :=_ged .Pop ();
if _dad !=nil {return _dad ;};_gbdf ,_dad :=_ged .Pop ();if _dad !=nil {return _dad ;};_cbe ,_addb :=_fadg .(*PSBoolean );_gcg ,_dba :=_gbdf .(*PSBoolean );if _addb ||_dba {var _bffg error ;if _addb &&_dba {_bffg =_ged .Push (MakeBool (_cbe .Val ==_gcg .Val ));
}else {_bffg =_ged .Push (MakeBool (false ));};return _bffg ;};var _ced float64 ;var _ccg float64 ;if _fcae ,_fbbb :=_fadg .(*PSInteger );_fbbb {_ced =float64 (_fcae .Val );}else if _dbae ,_daf :=_fadg .(*PSReal );_daf {_ced =_dbae .Val ;}else {return ErrTypeCheck ;
};if _adff ,_agf :=_gbdf .(*PSInteger );_agf {_ccg =float64 (_adff .Val );}else if _cec ,_ddg :=_gbdf .(*PSReal );_ddg {_ccg =_cec .Val ;}else {return ErrTypeCheck ;};if _f .Abs (_ccg -_ced )< _eg {_dad =_ged .Push (MakeBool (true ));}else {_dad =_ged .Push (MakeBool (false ));
};return _dad ;};var ErrStackOverflow =_g .New ("\u0073\u0074\u0061\u0063\u006b\u0020\u006f\u0076\u0065r\u0066\u006c\u006f\u0077");func (_gea *PSInteger )String ()string {return _e .Sprintf ("\u0025\u0064",_gea .Val )};func (_bf *PSProgram )DebugString ()string {_acd :="\u007b\u0020";
for _ ,_fad :=range *_bf {_acd +=_fad .DebugString ();_acd +="\u0020";};_acd +="\u007d";return _acd ;};func (_gbca *PSOperand )copy (_gcc *PSStack )error {_fcd ,_febc :=_gcc .PopInteger ();if _febc !=nil {return _febc ;};if _fcd < 0{return ErrRangeCheck ;
};if _fcd > len (*_gcc ){return ErrRangeCheck ;};*_gcc =append (*_gcc ,(*_gcc )[len (*_gcc )-_fcd :]...);return nil ;};func (_dgc *PSParser )skipComments ()error {if _ ,_geed :=_dgc .skipSpaces ();_geed !=nil {return _geed ;};_ebg :=true ;for {_aaad ,_fbe :=_dgc ._caeda .Peek (1);
if _fbe !=nil {_gge .Log .Debug ("\u0045\u0072\u0072\u006f\u0072\u0020\u0025\u0073",_fbe .Error ());return _fbe ;};if _ebg &&_aaad [0]!='%'{return nil ;};_ebg =false ;if (_aaad [0]!='\r')&&(_aaad [0]!='\n'){_dgc ._caeda .ReadByte ();}else {break ;};};return _dgc .skipComments ();
};

// NewPSStack returns an initialized PSStack.
func NewPSStack ()*PSStack {return &PSStack {}};

// Exec executes the operand `op` in the state specified by `stack`.
func (_abe *PSOperand )Exec (stack *PSStack )error {_cfc :=ErrUnsupportedOperand ;switch *_abe {case "\u0061\u0062\u0073":_cfc =_abe .abs (stack );case "\u0061\u0064\u0064":_cfc =_abe .add (stack );case "\u0061\u006e\u0064":_cfc =_abe .and (stack );case "\u0061\u0074\u0061\u006e":_cfc =_abe .atan (stack );
case "\u0062\u0069\u0074\u0073\u0068\u0069\u0066\u0074":_cfc =_abe .bitshift (stack );case "\u0063e\u0069\u006c\u0069\u006e\u0067":_cfc =_abe .ceiling (stack );case "\u0063\u006f\u0070\u0079":_cfc =_abe .copy (stack );case "\u0063\u006f\u0073":_cfc =_abe .cos (stack );
case "\u0063\u0076\u0069":_cfc =_abe .cvi (stack );case "\u0063\u0076\u0072":_cfc =_abe .cvr (stack );case "\u0064\u0069\u0076":_cfc =_abe .div (stack );case "\u0064\u0075\u0070":_cfc =_abe .dup (stack );case "\u0065\u0071":_cfc =_abe .eq (stack );case "\u0065\u0078\u0063\u0068":_cfc =_abe .exch (stack );
case "\u0065\u0078\u0070":_cfc =_abe .exp (stack );case "\u0066\u006c\u006fo\u0072":_cfc =_abe .floor (stack );case "\u0067\u0065":_cfc =_abe .ge (stack );case "\u0067\u0074":_cfc =_abe .gt (stack );case "\u0069\u0064\u0069\u0076":_cfc =_abe .idiv (stack );
case "\u0069\u0066":_cfc =_abe .ifCondition (stack );case "\u0069\u0066\u0065\u006c\u0073\u0065":_cfc =_abe .ifelse (stack );case "\u0069\u006e\u0064e\u0078":_cfc =_abe .index (stack );case "\u006c\u0065":_cfc =_abe .le (stack );case "\u006c\u006f\u0067":_cfc =_abe .log (stack );
case "\u006c\u006e":_cfc =_abe .ln (stack );case "\u006c\u0074":_cfc =_abe .lt (stack );case "\u006d\u006f\u0064":_cfc =_abe .mod (stack );case "\u006d\u0075\u006c":_cfc =_abe .mul (stack );case "\u006e\u0065":_cfc =_abe .ne (stack );case "\u006e\u0065\u0067":_cfc =_abe .neg (stack );
case "\u006e\u006f\u0074":_cfc =_abe .not (stack );case "\u006f\u0072":_cfc =_abe .or (stack );case "\u0070\u006f\u0070":_cfc =_abe .pop (stack );case "\u0072\u006f\u0075n\u0064":_cfc =_abe .round (stack );case "\u0072\u006f\u006c\u006c":_cfc =_abe .roll (stack );
case "\u0073\u0069\u006e":_cfc =_abe .sin (stack );case "\u0073\u0071\u0072\u0074":_cfc =_abe .sqrt (stack );case "\u0073\u0075\u0062":_cfc =_abe .sub (stack );case "\u0074\u0072\u0075\u006e\u0063\u0061\u0074\u0065":_cfc =_abe .truncate (stack );case "\u0078\u006f\u0072":_cfc =_abe .xor (stack );
};return _cfc ;};func (_eggf *PSOperand )ne (_ddf *PSStack )error {_gdcc :=_eggf .eq (_ddf );if _gdcc !=nil {return _gdcc ;};_gdcc =_eggf .not (_ddf );return _gdcc ;};func (_adc *PSOperand )atan (_geaad *PSStack )error {_ea ,_fge :=_geaad .PopNumberAsFloat64 ();
if _fge !=nil {return _fge ;};_dg ,_fge :=_geaad .PopNumberAsFloat64 ();if _fge !=nil {return _fge ;};if _ea ==0{var _fgef error ;if _dg < 0{_fgef =_geaad .Push (MakeReal (270));}else {_fgef =_geaad .Push (MakeReal (90));};return _fgef ;};_eaa :=_dg /_ea ;
_acf :=_f .Atan (_eaa )*180/_f .Pi ;_fge =_geaad .Push (MakeReal (_acf ));return _fge ;};func (_fb *PSOperand )DebugString ()string {return _e .Sprintf ("\u006fp\u003a\u0027\u0025\u0073\u0027",*_fb );};

// Empty empties the stack.
func (_ccgd *PSStack )Empty (){*_ccgd =[]PSObject {}};func (_gaacc *PSParser )skipSpaces ()(int ,error ){_bfgca :=0;for {_bcfb ,_abeb :=_gaacc ._caeda .Peek (1);if _abeb !=nil {return 0,_abeb ;};if _gc .IsWhiteSpace (_bcfb [0]){_gaacc ._caeda .ReadByte ();
_bfgca ++;}else {break ;};};return _bfgca ,nil ;};

// Exec executes the program, typically leaving output values on the stack.
func (_ga *PSProgram )Exec (stack *PSStack )error {for _ ,_cg :=range *_ga {var _gdd error ;switch _de :=_cg .(type ){case *PSInteger :_gde :=_de ;_gdd =stack .Push (_gde );case *PSReal :_aa :=_de ;_gdd =stack .Push (_aa );case *PSBoolean :_ddc :=_de ;
_gdd =stack .Push (_ddc );case *PSProgram :_cc :=_de ;_gdd =stack .Push (_cc );case *PSOperand :_aag :=_de ;_gdd =_aag .Exec (stack );default:return ErrTypeCheck ;};if _gdd !=nil {return _gdd ;};};return nil ;};

// MakeBool returns a new PSBoolean object initialized with `val`.
func MakeBool (val bool )*PSBoolean {_afcg :=PSBoolean {};_afcg .Val =val ;return &_afcg };func (_aedf *PSOperand )exch (_cbeb *PSStack )error {_eda ,_bbb :=_cbeb .Pop ();if _bbb !=nil {return _bbb ;};_ebf ,_bbb :=_cbeb .Pop ();if _bbb !=nil {return _bbb ;
};_bbb =_cbeb .Push (_eda );if _bbb !=nil {return _bbb ;};_bbb =_cbeb .Push (_ebf );return _bbb ;};func (_fcg *PSOperand )add (_aca *PSStack )error {_bgg ,_gb :=_aca .Pop ();if _gb !=nil {return _gb ;};_cgc ,_gb :=_aca .Pop ();if _gb !=nil {return _gb ;
};_bggd ,_eb :=_bgg .(*PSReal );_bde ,_fff :=_bgg .(*PSInteger );if !_eb &&!_fff {return ErrTypeCheck ;};_bc ,_dbf :=_cgc .(*PSReal );_gbc ,_fd :=_cgc .(*PSInteger );if !_dbf &&!_fd {return ErrTypeCheck ;};if _fff &&_fd {_gef :=_bde .Val +_gbc .Val ;_aab :=_aca .Push (MakeInteger (_gef ));
return _aab ;};var _gf float64 ;if _eb {_gf =_bggd .Val ;}else {_gf =float64 (_bde .Val );};if _dbf {_gf +=_bc .Val ;}else {_gf +=float64 (_gbc .Val );};_gb =_aca .Push (MakeReal (_gf ));return _gb ;};

// MakeOperand returns a new PSOperand object based on string `val`.
func MakeOperand (val string )*PSOperand {_afgg :=PSOperand (val );return &_afgg };var ErrUnsupportedOperand =_g .New ("\u0075\u006e\u0073\u0075pp\u006f\u0072\u0074\u0065\u0064\u0020\u006f\u0070\u0065\u0072\u0061\u006e\u0064");func (_egd *PSOperand )not (_gff *PSStack )error {_geaadd ,_aef :=_gff .Pop ();
if _aef !=nil {return _aef ;};if _fecc ,_gfbbb :=_geaadd .(*PSBoolean );_gfbbb {_aef =_gff .Push (MakeBool (!_fecc .Val ));return _aef ;}else if _ef ,_dcg :=_geaadd .(*PSInteger );_dcg {_aef =_gff .Push (MakeInteger (^_ef .Val ));return _aef ;}else {return ErrTypeCheck ;
};};func (_eeba *PSOperand )pop (_ebe *PSStack )error {_ ,_feba :=_ebe .Pop ();if _feba !=nil {return _feba ;};return nil ;};func (_bdee *PSOperand )sqrt (_abff *PSStack )error {_cagc ,_aaba :=_abff .PopNumberAsFloat64 ();if _aaba !=nil {return _aaba ;
};if _cagc < 0{return ErrRangeCheck ;};_eaga :=_f .Sqrt (_cagc );_aaba =_abff .Push (MakeReal (_eaga ));return _aaba ;};func (_bbgf *PSOperand )ifCondition (_bgce *PSStack )error {_cga ,_cagb :=_bgce .Pop ();if _cagb !=nil {return _cagb ;};_gae ,_cagb :=_bgce .Pop ();
if _cagb !=nil {return _cagb ;};_bgd ,_cbef :=_cga .(*PSProgram );if !_cbef {return ErrTypeCheck ;};_gfbb ,_cbef :=_gae .(*PSBoolean );if !_cbef {return ErrTypeCheck ;};if _gfbb .Val {_bfff :=_bgd .Exec (_bgce );return _bfff ;};return nil ;};func (_ad *PSBoolean )Duplicate ()PSObject {_feb :=PSBoolean {};
_feb .Val =_ad .Val ;return &_feb };

// PSObjectArrayToFloat64Array converts []PSObject into a []float64 array. Each PSObject must represent a number,
// otherwise a ErrTypeCheck error occurs.
func PSObjectArrayToFloat64Array (objects []PSObject )([]float64 ,error ){var _db []float64 ;for _ ,_ce :=range objects {if _gd ,_ac :=_ce .(*PSInteger );_ac {_db =append (_db ,float64 (_gd .Val ));}else if _gdg ,_fc :=_ce .(*PSReal );_fc {_db =append (_db ,_gdg .Val );
}else {return nil ,ErrTypeCheck ;};};return _db ,nil ;};func (_agc *PSOperand )abs (_ade *PSStack )error {_ggg ,_fca :=_ade .Pop ();if _fca !=nil {return _fca ;};if _aeb ,_bd :=_ggg .(*PSReal );_bd {_be :=_aeb .Val ;if _be < 0{_fca =_ade .Push (MakeReal (-_be ));
}else {_fca =_ade .Push (MakeReal (_be ));};}else if _gag ,_ee :=_ggg .(*PSInteger );_ee {_ca :=_gag .Val ;if _ca < 0{_fca =_ade .Push (MakeInteger (-_ca ));}else {_fca =_ade .Push (MakeInteger (_ca ));};}else {return ErrTypeCheck ;};return _fca ;};

// NewPSProgram returns an empty, initialized PSProgram.
func NewPSProgram ()*PSProgram {return &PSProgram {}};

// NewPSExecutor returns an initialized PSExecutor for an input `program`.
func NewPSExecutor (program *PSProgram )*PSExecutor {_ggf :=&PSExecutor {};_ggf .Stack =NewPSStack ();_ggf ._b =program ;return _ggf ;};func (_ed *PSOperand )Duplicate ()PSObject {_adf :=*_ed ;return &_adf };func (_gaa *PSOperand )log (_fgeb *PSStack )error {_feg ,_gcd :=_fgeb .PopNumberAsFloat64 ();
if _gcd !=nil {return _gcd ;};_bdec :=_f .Log10 (_feg );_gcd =_fgeb .Push (MakeReal (_bdec ));return _gcd ;};

// PopInteger specificially pops an integer from the top of the stack, returning the value as an int.
func (_caf *PSStack )PopInteger ()(int ,error ){_fega ,_dfg :=_caf .Pop ();if _dfg !=nil {return 0,_dfg ;};if _bgga ,_faec :=_fega .(*PSInteger );_faec {return _bgga .Val ,nil ;};return 0,ErrTypeCheck ;};func (_efef *PSParser )parseNumber ()(PSObject ,error ){_gec ,_efb :=_gc .ParseNumber (_efef ._caeda );
if _efb !=nil {return nil ,_efb ;};switch _cabd :=_gec .(type ){case *_gc .PdfObjectFloat :return MakeReal (float64 (*_cabd )),nil ;case *_gc .PdfObjectInteger :return MakeInteger (int (*_cabd )),nil ;};return nil ,_e .Errorf ("\u0075n\u0068\u0061\u006e\u0064\u006c\u0065\u0064\u0020\u006e\u0075\u006db\u0065\u0072\u0020\u0074\u0079\u0070\u0065\u0020\u0025\u0054",_gec );
};

// PSStack defines a stack of PSObjects. PSObjects can be pushed on or pull from the stack.
type PSStack []PSObject ;func (_ddgge *PSOperand )truncate (_ggeg *PSStack )error {_cee ,_ecab :=_ggeg .Pop ();if _ecab !=nil {return _ecab ;};if _gfg ,_bdaa :=_cee .(*PSReal );_bdaa {_fdb :=int (_gfg .Val );_ecab =_ggeg .Push (MakeReal (float64 (_fdb )));
}else if _fab ,_gbeb :=_cee .(*PSInteger );_gbeb {_ecab =_ggeg .Push (MakeInteger (_fab .Val ));}else {return ErrTypeCheck ;};return _ecab ;};

// String returns a string representation of the stack.
func (_bafd *PSStack )String ()string {_fag :="\u005b\u0020";for _ ,_dgba :=range *_bafd {_fag +=_dgba .String ();_fag +="\u0020";};_fag +="\u005d";return _fag ;};const _eg =0.000001;func (_ebd *PSOperand )xor (_dcb *PSStack )error {_gdge ,_ccff :=_dcb .Pop ();
if _ccff !=nil {return _ccff ;};_afcf ,_ccff :=_dcb .Pop ();if _ccff !=nil {return _ccff ;};if _bcb ,_aebdg :=_gdge .(*PSBoolean );_aebdg {_fbdd ,_aaf :=_afcf .(*PSBoolean );if !_aaf {return ErrTypeCheck ;};_ccff =_dcb .Push (MakeBool (_bcb .Val !=_fbdd .Val ));
return _ccff ;};if _dfe ,_dfd :=_gdge .(*PSInteger );_dfd {_fabg ,_eggfe :=_afcf .(*PSInteger );if !_eggfe {return ErrTypeCheck ;};_ccff =_dcb .Push (MakeInteger (_dfe .Val ^_fabg .Val ));return _ccff ;};return ErrTypeCheck ;};func (_cfad *PSOperand )neg (_aaec *PSStack )error {_ecg ,_bgf :=_aaec .Pop ();
if _bgf !=nil {return _bgf ;};if _dfb ,_ggga :=_ecg .(*PSReal );_ggga {_bgf =_aaec .Push (MakeReal (-_dfb .Val ));return _bgf ;}else if _cef ,_ecag :=_ecg .(*PSInteger );_ecag {_bgf =_aaec .Push (MakeInteger (-_cef .Val ));return _bgf ;}else {return ErrTypeCheck ;
};};