//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package basic ;import _e "github.com/unidoc/unipdf/v4/internal/jbig2/errors";func (_bg *NumSlice )AddInt (v int ){*_bg =append (*_bg ,float32 (v ))};func (_d IntsMap )Get (key uint64 )(int ,bool ){_cb ,_cg :=_d [key ];if !_cg {return 0,false ;};if len (_cb )==0{return 0,false ;
};return _cb [0],true ;};type IntsMap map[uint64 ][]int ;func (_gd NumSlice )GetInt (i int )(int ,error ){const _fb ="\u0047\u0065\u0074\u0049\u006e\u0074";if i < 0||i > len (_gd )-1{return 0,_e .Errorf (_fb ,"\u0069n\u0064\u0065\u0078\u003a\u0020\u0027\u0025\u0064\u0027\u0020\u006fu\u0074\u0020\u006f\u0066\u0020\u0072\u0061\u006e\u0067\u0065",i );
};_ff :=_gd [i ];return int (_ff +Sign (_ff )*0.5),nil ;};func (_ggc NumSlice )Get (i int )(float32 ,error ){if i < 0||i > len (_ggc )-1{return 0,_e .Errorf ("\u004e\u0075\u006dS\u006c\u0069\u0063\u0065\u002e\u0047\u0065\u0074","\u0069n\u0064\u0065\u0078\u003a\u0020\u0027\u0025\u0064\u0027\u0020\u006fu\u0074\u0020\u006f\u0066\u0020\u0072\u0061\u006e\u0067\u0065",i );
};return _ggc [i ],nil ;};func (_gg *IntSlice )Add (v int )error {if _gg ==nil {return _e .Error ("\u0049\u006e\u0074S\u006c\u0069\u0063\u0065\u002e\u0041\u0064\u0064","\u0073\u006c\u0069\u0063\u0065\u0020\u006e\u006f\u0074\u0020\u0064\u0065f\u0069\u006e\u0065\u0064");
};*_gg =append (*_gg ,v );return nil ;};func Ceil (numerator ,denominator int )int {if numerator %denominator ==0{return numerator /denominator ;};return (numerator /denominator )+1;};func (_ea IntSlice )Get (index int )(int ,error ){if index > len (_ea )-1{return 0,_e .Errorf ("\u0049\u006e\u0074S\u006c\u0069\u0063\u0065\u002e\u0047\u0065\u0074","\u0069\u006e\u0064\u0065x:\u0020\u0025\u0064\u0020\u006f\u0075\u0074\u0020\u006f\u0066\u0020\u0072\u0061\u006eg\u0065",index );
};return _ea [index ],nil ;};func (_bcb NumSlice )GetIntSlice ()[]int {_db :=make ([]int ,len (_bcb ));for _fe ,_eg :=range _bcb {_db [_fe ]=int (_eg );};return _db ;};func (_dd *Stack )peek ()(interface{},bool ){_cgf :=_dd .top ();if _cgf ==-1{return nil ,false ;
};return _dd .Data [_cgf ],true ;};func Sign (v float32 )float32 {if v >=0.0{return 1.0;};return -1.0;};func (_bbb *Stack )top ()int {return len (_bbb .Data )-1};func NewIntSlice (i int )*IntSlice {_bb :=IntSlice (make ([]int ,i ));return &_bb };func (_g IntsMap )Delete (key uint64 ){delete (_g ,key )};
func (_dg *Stack )Peek ()(_ce interface{},_dbf bool ){return _dg .peek ()};func Min (x ,y int )int {if x < y {return x ;};return y ;};type IntSlice []int ;func (_fa IntSlice )Size ()int {return len (_fa )};func Max (x ,y int )int {if x > y {return x ;};
return y ;};func (_a *IntSlice )Copy ()*IntSlice {_bc :=IntSlice (make ([]int ,len (*_a )));copy (_bc ,*_a );return &_bc ;};func (_bbg *Stack )Pop ()(_ed interface{},_de bool ){_ed ,_de =_bbg .peek ();if !_de {return nil ,_de ;};_bbg .Data =_bbg .Data [:_bbg .top ()];
return _ed ,true ;};func (_bcc *Stack )Len ()int {return len (_bcc .Data )};func (_cf IntsMap )Add (key uint64 ,value int ){_cf [key ]=append (_cf [key ],value )};func (_b IntsMap )GetSlice (key uint64 )([]int ,bool ){_f ,_fc :=_b [key ];if !_fc {return nil ,false ;
};return _f ,true ;};func Abs (v int )int {if v > 0{return v ;};return -v ;};type NumSlice []float32 ;type Stack struct{Data []interface{};Aux *Stack ;};func NewNumSlice (i int )*NumSlice {_fae :=NumSlice (make ([]float32 ,i ));return &_fae };func (_cc *Stack )Push (v interface{}){_cc .Data =append (_cc .Data ,v )};
func (_ba *NumSlice )Add (v float32 ){*_ba =append (*_ba ,v )};